'use strict';function t(k,m,d,h){k.h.Z(k.A,m,d,h,void 0)}function x(k,m,d,h){k.h.j?t(k,m,d,h):k.h.mb()._OnMessageFromDOM({type:"event",component:k.A,handler:m,dispatchOpts:h||null,data:d,responseId:null})}function D(k,m,d){k.h.a(k.A,m,d)}function E(k,m){for(const [d,h]of m)D(k,d,h)}window.X=class{constructor(k,m){this.h=k;this.A=m}ta(){}};
window.ab=class{constructor(k,m){this.La=k;this.Ub=m;this.s=-1;this.S=-Infinity;this.Zb=()=>{this.s=-1;this.S=Date.now();this.B=!0;this.La();this.B=!1};this.Ma=this.B=!1}};"use strict";function F(k,m){const d=m.elementId,h=k.wa(d,m);k.f.set(d,h);m.isVisible||(h.style.display="none");h.addEventListener("focus",()=>{G(k,"elem-focused",d)});h.addEventListener("blur",()=>{G(k,"elem-blurred",d)});k.P&&document.body.appendChild(h)}
function H(k,m,d){D(k,m,h=>{const n=k.f.get(h.elementId);return d(n,h)})}function G(k,m,d,h){h||(h={});h.elementId=d;t(k,m,h)}function I(k,m,d){var h;h||(h={});h.elementId=d;x(k,m,h)}
window.Va=class extends self.X{constructor(k,m){super(k,m);this.f=new Map;this.P=!0;E(this,[["create",d=>F(this,d)],["destroy",d=>{{d=d.elementId;const h=this.f.get(d);this.P&&h.parentElement.removeChild(h);this.f.delete(d)}}],["set-visible",d=>{this.P&&(this.f.get(d.elementId).style.display=d.isVisible?"":"none")}],["update-position",d=>{if(this.P){var h=this.f.get(d.elementId);h.style.left=d.left+"px";h.style.top=d.top+"px";h.style.width=d.width+"px";h.style.height=d.height+"px";d=d.fontSize;null!==
d&&(h.style.fontSize=d+"em")}}],["update-state",d=>{{const h=this.f.get(d.elementId);this.$(h,d)}}],["focus",d=>{{const h=this.f.get(d.elementId);d.focus?h.focus():h.blur()}}],["set-css-style",d=>{this.f.get(d.elementId).style[d.prop]=d.val}],["set-attribute",d=>{this.f.get(d.elementId).setAttribute(d.name,d.val)}],["remove-attribute",d=>{this.f.get(d.elementId).removeAttribute(d.name)}]]);H(this,"get-element",d=>d)}wa(){throw Error("required override");}$(){throw Error("required override");}};"use strict";
{const k=/(iphone|ipod|ipad|macos|macintosh|mac os x)/i.test(navigator.userAgent);function m(q){if(q.bc){const c=document.createElement("script");c.async=!1;c.textContent=q.ec;document.head.appendChild(c)}else return new Promise((c,f)=>{const a=document.createElement("script");a.onload=c;a.onerror=f;a.async=!1;a.src=q;document.head.appendChild(a)})}let d=new Audio;const h={"audio/webm; codecs=opus":!!d.canPlayType("audio/webm; codecs=opus"),"audio/ogg; codecs=opus":!!d.canPlayType("audio/ogg; codecs=opus"),
"audio/webm; codecs=vorbis":!!d.canPlayType("audio/webm; codecs=vorbis"),"audio/ogg; codecs=vorbis":!!d.canPlayType("audio/ogg; codecs=vorbis"),"audio/mp4":!!d.canPlayType("audio/mp4"),"audio/mpeg":!!d.canPlayType("audio/mpeg")};d=null;async function n(q){q=await w(q);return(new TextDecoder("utf-8")).decode(q)}function w(q){return new Promise((c,f)=>{const a=new FileReader;a.onload=b=>c(b.target.result);a.onerror=b=>f(b);a.readAsArrayBuffer(q)})}const u=[];let y=0;window.RealFile=window.File;const v=
[],z=new Map,A=new Map;let B=0;const C=[];self.pc=function(q){if("function"!==typeof q)throw Error("runOnStartup called without a function");C.push(q)};const r=new Set(["cordova","playable-ad","instant-games"]);window.J=class q{constructor(c){this.j=c.hc;this.D=null;this.b="";this.qa=c.dc;this.H={};this.ma=this.Ra=null;this.R=[];this.C=this.c=this.pa=null;this.m=-1;this.Yb=()=>this.Gb();this.Pa=[];this.g=c.Sa;!this.j||"undefined"!==typeof OffscreenCanvas&&navigator.userActivation||(this.j=!1);r.has(this.g)&&
this.j&&(console.warn("[C3 runtime] Worker mode is enabled and supported, but is disabled in WebViews due to crbug.com/923007. Reverting to DOM mode."),this.j=!1);this.Qa=!1;this.T=this.i=null;"html5"!==this.g&&"playable-ad"!==this.g||"file"!==location.protocol.substr(0,4)||alert("Exported games won't work until you upload them. (When running on the file: protocol, browsers block many features from working for security reasons.)");this.a("runtime","cordova-fetch-local-file",f=>this.tb(f));this.a("runtime",
"create-job-worker",()=>this.ub());"cordova"===this.g?document.addEventListener("deviceready",()=>this.Ca(c)):this.Ca(c)}xa(){return k&&"cordova"===this.g}I(){return k&&r.has(this.g)||navigator.standalone}async Ca(c){if("playable-ad"===this.g){this.i=self.c3_base64files;this.T={};await this.hb();for(let a=0,b=c.u.length;a<b;++a){var f=c.u[a].toLowerCase();this.T.hasOwnProperty(f)?c.u[a]={bc:!0,ec:this.T[f]}:this.i.hasOwnProperty(f)&&(c.u[a]=URL.createObjectURL(this.i[f]))}}c.$b?this.b=c.$b:(f=location.origin,
this.b=("null"===f?"file:///":f)+location.pathname,f=this.b.lastIndexOf("/"),-1!==f&&(this.b=this.b.substr(0,f+1)));if(c.jc)for(const [a,b]of Object.entries(c.jc))this.H[a]=URL.createObjectURL(b);f=new MessageChannel;this.D=f.port1;this.D.onmessage=a=>this._OnMessageFromRuntime(a.data);window.c3_addPortMessageHandler&&window.c3_addPortMessageHandler(a=>this.Db(a));this.C=new self.Za(this);await this.C.Ya();this.ya();"object"===typeof window.StatusBar&&window.StatusBar.hide();"object"===typeof window.AndroidFullScreen&&
window.AndroidFullScreen.immersiveMode();await this.Rb();this.j?await this.ob(c,f.port2):await this.nb(c,f.port2)}ba(c){return this.H.hasOwnProperty(c)?this.H[c]:c.endsWith("/workermain.js")&&this.H.hasOwnProperty("workermain.js")?this.H["workermain.js"]:"playable-ad"===this.g&&this.i.hasOwnProperty(c.toLowerCase())?URL.createObjectURL(this.i[c.toLowerCase()]):c}async W(c,f,a){if(c.startsWith("blob:"))return new Worker(c,a);if(this.xa()&&"file:"===location.protocol)return c=await this.va(this.qa+
c),new Worker(URL.createObjectURL(new Blob([c],{type:"application/javascript"})),a);c=new URL(c,f);if(location.origin!==c.origin){c=await fetch(c);if(!c.ok)throw Error("failed to fetch worker script");c=await c.blob();return new Worker(URL.createObjectURL(c),a)}return new Worker(c,a)}ya(){if(this.I()){const c=document.documentElement.style,f=document.body.style,a=window.innerWidth<window.innerHeight,b=a?window.screen.width:window.screen.height;f.height=c.height=(a?window.screen.height:window.screen.width)+
"px";f.width=c.width=b+"px"}}Ba(c){return{baseUrl:this.b,windowInnerWidth:window.innerWidth,windowInnerHeight:window.innerHeight,devicePixelRatio:window.devicePixelRatio,isFullscreen:q.Y(),projectData:c.oc,previewImageBlobs:window.cr_previewImageBlobs||this.i,previewProjectFileBlobs:window.cr_previewProjectFileBlobs,exportType:c.Sa,isDebug:-1<self.location.search.indexOf("debug"),ife:!!self.nc,jobScheduler:this.C.Wa(),supportedAudioFormats:h,opusWasmScriptUrl:window.cr_opusWasmScriptUrl||this.qa+
"opus.wasm.js",opusWasmBinaryUrl:window.cr_opusWasmBinaryUrl||this.qa+"opus.wasm.wasm",isiOSCordova:this.xa(),isiOSWebView:this.I(),isFBInstantAvailable:"undefined"!==typeof self.FBInstant}}async ob(c,f){var a=this.ba(c.ic);this.Ra=await this.W(a,this.b,{name:"Runtime"});this.c=document.createElement("canvas");this.c.style.display="none";a=this.c.transferControlToOffscreen();document.body.appendChild(this.c);window.c3canvas=this.c;this.Ra.postMessage(Object.assign(this.Ba(c),{type:"init-runtime",
isInWorker:!0,messagePort:f,canvas:a,workerDependencyScripts:c.sa||[],engineScripts:c.u,projectScripts:window.mc,projectScriptsStatus:self.C3_ProjectScriptsStatus}),[f,a,...this.C.Xa()]);this.R=v.map(b=>new b(this));this.Aa();self.c3_callFunction=(b,e)=>this.pa.pb(b,e);"preview"===this.g&&(self.goToLastErrorScript=()=>this.Z("runtime","go-to-last-error-script"))}async nb(c,f){this.c=document.createElement("canvas");this.c.style.display="none";document.body.appendChild(this.c);window.c3canvas=this.c;
this.R=v.map(b=>new b(this));this.Aa();const a=c.u.map(b=>"string"===typeof b?(new URL(b,this.b)).toString():b);Array.isArray(c.sa)&&a.unshift(...c.sa);await Promise.all(a.map(b=>m(b)));if(c.Ta&&0<c.Ta.length){const b=self.C3_ProjectScriptsStatus;try{if(await Promise.all(c.Ta.map(e=>m(e[1]))),Object.values(b).some(e=>!e)){self.setTimeout(()=>this.Ha(b),100);return}}catch(e){console.error("[Preview] Error loading project scripts: ",e);self.setTimeout(()=>this.Ha(b),100);return}}"preview"===this.g&&
"object"!==typeof self.kc.lc?(console.error("[C3 runtime] Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax."),alert("Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax.")):(c=Object.assign(this.Ba(c),{isInWorker:!1,messagePort:f,canvas:this.c,runOnStartupFunctions:C}),this.ma=self.C3_CreateRuntime(c),await self.C3_InitRuntime(this.ma,c))}Ha(c){c=`Failed to load project script '${Object.entries(c).filter(f=>!f[1]).map(f=>
f[0])[0]}'. Check all your JavaScript code has valid syntax.`;console.error("[Preview] "+c);alert(c)}async ub(){const c=await this.C.za();return{outputPort:c,transferables:[c]}}mb(){if(this.j)throw Error("not available in worker mode");return this.ma}Z(c,f,a,b,e){this.D.postMessage({type:"event",component:c,handler:f,dispatchOpts:b||null,data:a,responseId:null},this.Qa?void 0:e)}$a(c,f){const a=B++,b=new Promise((e,g)=>{A.set(a,{resolve:e,reject:g})});this.D.postMessage({type:"event",component:c,
handler:"js-invoke-function",dispatchOpts:null,data:f,responseId:a},void 0);return b}["_OnMessageFromRuntime"](c){const f=c.type;if("event"===f)return this.zb(c);if("result"===f)this.Jb(c);else if("runtime-ready"===f)this.Kb();else if("alert"===f)alert(c.message);else throw Error(`unknown message '${f}'`);}zb(c){const f=c.component,a=c.handler,b=c.data,e=c.responseId;if(c=z.get(f))if(c=c.get(a)){var g=null;try{g=c(b)}catch(l){console.error(`Exception in '${f}' handler '${a}':`,l);null!==e&&this.N(e,
!1,""+l);return}if(null===e)return g;g&&g.then?g.then(l=>this.N(e,!0,l)).catch(l=>{console.error(`Rejection from '${f}' handler '${a}':`,l);this.N(e,!1,""+l)}):this.N(e,!0,g)}else console.warn(`[DOM] No handler '${a}' for component '${f}'`);else console.warn(`[DOM] No event handlers for component '${f}'`)}N(c,f,a){let b;a&&a.transferables&&(b=a.transferables);this.D.postMessage({type:"result",responseId:c,isOk:f,result:a},b)}Jb(c){const f=c.responseId,a=c.isOk;c=c.result;const b=A.get(f);a?b.resolve(c):
b.reject(c);A.delete(f)}a(c,f,a){let b=z.get(c);b||(b=new Map,z.set(c,b));if(b.has(f))throw Error(`[DOM] Component '${c}' already has handler '${f}'`);b.set(f,a)}static V(c){if(v.includes(c))throw Error("DOM handler already added");v.push(c)}Aa(){for(const c of this.R)if("runtime"===c.A){this.pa=c;return}throw Error("cannot find runtime DOM handler");}Db(c){this.Z("debugger","message",c)}Kb(){for(const c of this.R)c.ta()}static Y(){return!!(document.fullscreenElement||document.webkitFullscreenElement||
document.mozFullScreenElement)}Ia(){-1===this.m&&this.Pa.length&&(this.m=requestAnimationFrame(this.Yb))}fb(){-1!==this.m&&(cancelAnimationFrame(this.m),this.m=-1)}Gb(){this.m=-1;for(const c of this.Pa)c();this.Ia()}ia(){this.pa.ia()}async tb(c){const f=c.filename;switch(c.as){case "text":return await this.Ua(f);case "buffer":return await this.va(f);default:throw Error("unsupported type");}}ua(c){const f=window.cordova.file.applicationDirectory+"www/"+c.toLowerCase();return new Promise((a,b)=>{window.resolveLocalFileSystemURL(f,
e=>{e.file(a,b)},b)})}async Ua(c){c=await this.ua(c);return await n(c)}aa(){if(u.length&&!(8<=y)){y++;var c=u.shift();this.ib(c.filename,c.fc,c.ac)}}va(c){return new Promise((f,a)=>{u.push({filename:c,fc:b=>{y--;this.aa();f(b)},ac:b=>{y--;this.aa();a(b)}});this.aa()})}async ib(c,f,a){try{const b=await this.ua(c),e=await w(b);f(e)}catch(b){a(b)}}async hb(){const c=[];for(const [f,a]of Object.entries(this.i))c.push(this.gb(f,a));await Promise.all(c)}async gb(c,f){if("object"===typeof f)this.i[c]=new Blob([f.str],
{type:f.type}),this.T[c]=f.str;else{let a=await this.lb(f);a||(a=this.jb(f));this.i[c]=a}}async lb(c){try{return await (await fetch(c)).blob()}catch(f){return console.warn("Failed to fetch a data: URI. Falling back to a slower workaround. This is probably because the Content Security Policy unnecessarily blocked it. Allow data: URIs in your CSP to avoid this.",f),null}}jb(c){c=this.Pb(c);return this.eb(c.data,c.cc)}Pb(c){var f=c.indexOf(",");if(0>f)throw new URIError("expected comma in data: uri");
var a=c.substring(f+1);f=c.substring(5,f).split(";");c=f[0]||"";const b=f[2];a="base64"===f[1]||"base64"===b?atob(a):decodeURIComponent(a);return{cc:c,data:a}}eb(c,f){var a=c.length;let b=a>>2,e=new Uint8Array(a),g=new Uint32Array(e.buffer,0,b),l,p;for(p=l=0;l<b;++l)g[l]=c.charCodeAt(p++)|c.charCodeAt(p++)<<8|c.charCodeAt(p++)<<16|c.charCodeAt(p++)<<24;for(a&=3;a--;)e[p]=c.charCodeAt(p),++p;return new Blob([e],{type:f})}Rb(){let c=null;const f=new Promise(e=>c=e),a=new ArrayBuffer(1),b=new MessageChannel;
b.port2.onmessage=e=>{e.data&&e.data.arrayBuffer||(this.Qa=!0,console.warn("MessageChannel transfers determined to be broken. Disabling transferables."));c()};b.port1.postMessage({arrayBuffer:a},[a]);return f}}}"use strict";
{const k=self.J;function m(a){return a.sourceCapabilities&&a.sourceCapabilities.firesTouchEvents||a.originalEvent&&a.originalEvent.sourceCapabilities&&a.originalEvent.sourceCapabilities.firesTouchEvents}const d=new Map([["OSLeft","MetaLeft"],["OSRight","MetaRight"]]),h={dispatchRuntimeEvent:!0,dispatchUserScriptEvent:!0},n={dispatchUserScriptEvent:!0},w={dispatchRuntimeEvent:!0};function u(a){return new Promise((b,e)=>{const g=document.createElement("link");g.onload=()=>b(g);g.onerror=l=>e(l);g.rel=
"stylesheet";g.href=a;document.head.appendChild(g)})}function y(a){return new Promise((b,e)=>{const g=new Image;g.onload=()=>b(g);g.onerror=l=>e(l);g.src=a})}async function v(a){a=URL.createObjectURL(a);try{return await y(a)}finally{URL.revokeObjectURL(a)}}function z(a){return new Promise((b,e)=>{let g=new FileReader;g.onload=l=>b(l.target.result);g.onerror=l=>e(l);g.readAsText(a)})}async function A(a,b,e){if(!/firefox/i.test(navigator.userAgent))return await v(a);var g=await z(a);g=(new DOMParser).parseFromString(g,
"image/svg+xml");const l=g.documentElement;if(l.hasAttribute("width")&&l.hasAttribute("height")){const p=l.getAttribute("width"),K=l.getAttribute("height");if(!p.includes("%")&&!K.includes("%"))return await v(a)}l.setAttribute("width",b+"px");l.setAttribute("height",e+"px");g=(new XMLSerializer).serializeToString(g);a=new Blob([g],{type:"image/svg+xml"});return await v(a)}function B(a){do{if(a.parentNode&&a.hasAttribute("contenteditable"))return!0;a=a.parentNode}while(a);return!1}const C=new Set(["canvas",
"body","html"]);function r(a){C.has(a.target.tagName.toLowerCase())&&a.preventDefault()}function q(a){(a.metaKey||a.ctrlKey)&&a.preventDefault()}self.C3_GetSvgImageSize=async function(a){a=await v(a);if(0<a.width&&0<a.height)return[a.width,a.height];{a.style.position="absolute";a.style.left="0px";a.style.top="0px";a.style.visibility="hidden";document.body.appendChild(a);const b=a.getBoundingClientRect();document.body.removeChild(a);return[b.width,b.height]}};self.C3_RasterSvgImageBlob=async function(a,
b,e,g,l){a=await A(a,b,e);const p=document.createElement("canvas");p.width=g;p.height=l;p.getContext("2d").drawImage(a,0,0,b,e);return p};let c=!1;document.addEventListener("pause",()=>c=!0);document.addEventListener("resume",()=>c=!1);function f(){try{return window.parent&&window.parent.document.hasFocus()}catch(a){return!1}}k.V(class extends self.X{constructor(a){super(a,"runtime");this.Na=!0;this.o=-1;this.ra="any";this.Ja=this.Ka=!1;this.la=this.G=this.l=null;a.a("canvas","update-size",g=>this.Nb(g));
a.a("runtime","invoke-download",g=>this.Cb(g));a.a("runtime","raster-svg-image",g=>this.Hb(g));a.a("runtime","get-svg-image-size",g=>this.Ab(g));a.a("runtime","set-target-orientation",g=>this.Mb(g));a.a("runtime","register-sw",()=>this.Ib());a.a("runtime","post-to-debugger",g=>this.Fa(g));a.a("runtime","go-to-script",g=>this.Fa(g));a.a("runtime","before-start-ticking",()=>this.sb());a.a("runtime","debug-highlight",g=>this.vb(g));a.a("runtime","enable-device-orientation",()=>this.cb());a.a("runtime",
"enable-device-motion",()=>this.bb());a.a("runtime","add-stylesheet",g=>this.qb(g));a.a("runtime","alert",g=>this.rb(g));a.a("runtime","hide-cordova-splash",()=>this.Bb());const b=new Set(["input","textarea","datalist"]);window.addEventListener("contextmenu",g=>{const l=g.target;b.has(l.tagName.toLowerCase())||B(l)||g.preventDefault()});const e=a.c;window.addEventListener("selectstart",r);window.addEventListener("gesturehold",r);e.addEventListener("selectstart",r);e.addEventListener("gesturehold",
r);window.addEventListener("touchstart",r,{passive:!1});"undefined"!==typeof PointerEvent?(window.addEventListener("pointerdown",r,{passive:!1}),e.addEventListener("pointerdown",r)):e.addEventListener("touchstart",r);this.F=0;window.addEventListener("mousedown",g=>{1===g.button&&g.preventDefault()});window.addEventListener("mousewheel",q,{passive:!1});window.addEventListener("wheel",q,{passive:!1});window.addEventListener("resize",()=>this.Ob());a.I()&&window.addEventListener("focusout",()=>{{const p=
document.activeElement;if(p){var g=p.tagName.toLowerCase();var l=new Set("email number password search tel text url".split(" "));g="textarea"===g?!0:"input"===g?l.has(p.type.toLowerCase()||"text"):B(p)}else g=!1}g||(document.scrollingElement.scrollTop=0)});this.na=new Set;this.Xb=new WeakSet;this.Vb=!1}sb(){"cordova"===this.h.g?(document.addEventListener("pause",()=>this.ha(!0)),document.addEventListener("resume",()=>this.ha(!1))):document.addEventListener("visibilitychange",()=>this.ha(document.hidden));
return{isSuspended:!(!document.hidden&&!c)}}ta(){window.addEventListener("focus",()=>this.O("window-focus"));window.addEventListener("blur",()=>{this.O("window-blur",{parentHasFocus:f()});this.F=0});window.addEventListener("fullscreenchange",()=>this.da());window.addEventListener("webkitfullscreenchange",()=>this.da());window.addEventListener("mozfullscreenchange",()=>this.da());window.addEventListener("fullscreenerror",b=>this.ea(b));window.addEventListener("webkitfullscreenerror",b=>this.ea(b));
window.addEventListener("mozfullscreenerror",b=>this.ea(b));window.addEventListener("keydown",b=>this.Ea("keydown",b));window.addEventListener("keyup",b=>this.Ea("keyup",b));window.addEventListener("dblclick",b=>this.fa("dblclick",b,h));window.addEventListener("wheel",b=>this.Eb(b));"undefined"!==typeof PointerEvent?(window.addEventListener("pointerdown",b=>{this.ca(b);this.v("pointerdown",b)}),this.h.j&&"undefined"!==typeof window.onpointerrawupdate&&self===self.top?(this.G=new self.ab(()=>this.kb(),
5),this.G.Ma=!0,window.addEventListener("pointerrawupdate",b=>this.Fb(b))):window.addEventListener("pointermove",b=>this.v("pointermove",b)),window.addEventListener("pointerup",b=>this.v("pointerup",b)),window.addEventListener("pointercancel",b=>this.v("pointercancel",b))):(window.addEventListener("mousedown",b=>{this.ca(b);this.ga("pointerdown",b)}),window.addEventListener("mousemove",b=>this.ga("pointermove",b)),window.addEventListener("mouseup",b=>this.ga("pointerup",b)),window.addEventListener("touchstart",
b=>{this.ca(b);this.M("pointerdown",b)}),window.addEventListener("touchmove",b=>this.M("pointermove",b)),window.addEventListener("touchend",b=>this.M("pointerup",b)),window.addEventListener("touchcancel",b=>this.M("pointercancel",b)));const a=()=>this.ia();window.addEventListener("pointerup",a,!0);window.addEventListener("touchend",a,!0);window.addEventListener("click",a,!0);window.addEventListener("keydown",a,!0);window.addEventListener("gamepadconnected",a,!0)}O(a,b){t(this,a,b||null,w)}L(){return Math.max(window.innerWidth,
1)}K(){return Math.max(window.innerHeight,1)}Ob(){const a=this.L(),b=this.K();this.O("window-resize",{innerWidth:a,innerHeight:b,devicePixelRatio:window.devicePixelRatio});this.h.I()&&(-1!==this.o&&clearTimeout(this.o),this.Ga(a,b,0))}Qb(a,b,e){-1!==this.o&&clearTimeout(this.o);this.o=setTimeout(()=>this.Ga(a,b,e),48)}Ga(a,b,e){const g=this.L(),l=this.K();this.o=-1;g!=a||l!=b?this.O("window-resize",{innerWidth:g,innerHeight:l,devicePixelRatio:window.devicePixelRatio}):10>e&&this.Qb(g,l,e+1)}Mb(a){this.ra=
a.targetOrientation}Sb(){const a=this.ra;if(screen.orientation&&screen.orientation.lock)screen.orientation.lock(a).catch(b=>console.warn("[Construct 3] Failed to lock orientation: ",b));else try{let b=!1;screen.lockOrientation?b=screen.lockOrientation(a):screen.webkitLockOrientation?b=screen.webkitLockOrientation(a):screen.mozLockOrientation?b=screen.mozLockOrientation(a):screen.msLockOrientation&&(b=screen.msLockOrientation(a));b||console.warn("[Construct 3] Failed to lock orientation")}catch(b){console.warn("[Construct 3] Failed to lock orientation: ",
b)}}da(){const a=k.Y();a&&"any"!==this.ra&&this.Sb();t(this,"fullscreenchange",{isFullscreen:a,innerWidth:this.L(),innerHeight:this.K()})}ea(a){console.warn("[Construct 3] Fullscreen request failed: ",a);t(this,"fullscreenerror",{isFullscreen:k.Y(),innerWidth:this.L(),innerHeight:this.K()})}ha(a){a?this.h.fb():this.h.Ia();t(this,"visibilitychange",{hidden:a})}Ea(a,b){"Backspace"===b.key&&r(b);const e=d.get(b.code)||b.code;x(this,a,{code:e,key:b.key,which:b.which,repeat:b.repeat,altKey:b.altKey,ctrlKey:b.ctrlKey,
metaKey:b.metaKey,shiftKey:b.shiftKey,timeStamp:b.timeStamp},h)}Eb(a){t(this,"wheel",{clientX:a.clientX,clientY:a.clientY,pageX:a.pageX,pageY:a.pageY,deltaX:a.deltaX,deltaY:a.deltaY,deltaZ:a.deltaZ,deltaMode:a.deltaMode,timeStamp:a.timeStamp},h)}fa(a,b,e){m(b)||x(this,a,{button:b.button,buttons:b.buttons,clientX:b.clientX,clientY:b.clientY,pageX:b.pageX,pageY:b.pageY,timeStamp:b.timeStamp},e)}ga(a,b){if(!m(b)){var e=this.F;"pointerdown"===a&&0!==e?a="pointermove":"pointerup"===a&&0!==b.buttons&&(a=
"pointermove");x(this,a,{pointerId:1,pointerType:"mouse",button:b.button,buttons:b.buttons,lastButtons:e,clientX:b.clientX,clientY:b.clientY,pageX:b.pageX,pageY:b.pageY,width:0,height:0,pressure:0,tangentialPressure:0,tiltX:0,tiltY:0,twist:0,timeStamp:b.timeStamp},h);this.F=b.buttons;this.fa(b.type,b,n)}}v(a,b){if(this.G&&"pointermove"!==a){var e=this.G;e.B||(-1!==e.s&&(self.clearTimeout(e.s),e.s=-1),e.S=Date.now())}e=0;"mouse"===b.pointerType&&(e=this.F);x(this,a,{pointerId:b.pointerId,pointerType:b.pointerType,
button:b.button,buttons:b.buttons,lastButtons:e,clientX:b.clientX,clientY:b.clientY,pageX:b.pageX,pageY:b.pageY,width:b.width||0,height:b.height||0,pressure:b.pressure||0,tangentialPressure:b.tangentialPressure||0,tiltX:b.tiltX||0,tiltY:b.tiltY||0,twist:b.twist||0,timeStamp:b.timeStamp},h);"mouse"===b.pointerType&&(e="mousemove","pointerdown"===a?e="mousedown":"pointerup"===a&&(e="pointerup"),this.fa(e,b,n),this.F=b.buttons)}Fb(a){this.la=a;a=this.G;if(-1===a.s){var b=Date.now(),e=b-a.S,g=a.Ub;e>=
g&&a.Ma?(a.S=b,a.B=!0,a.La(),a.B=!1):a.s=self.setTimeout(a.Zb,Math.max(g-e,4))}}kb(){this.v("pointermove",this.la);this.la=null}M(a,b){for(let e=0,g=b.changedTouches.length;e<g;++e){const l=b.changedTouches[e];x(this,a,{pointerId:l.identifier,pointerType:"touch",button:0,buttons:0,lastButtons:0,clientX:l.clientX,clientY:l.clientY,pageX:l.pageX,pageY:l.pageY,width:2*(l.radiusX||l.webkitRadiusX||0),height:2*(l.radiusY||l.webkitRadiusY||0),pressure:l.force||l.webkitForce||0,tangentialPressure:0,tiltX:0,
tiltY:0,twist:l.rotationAngle||0,timeStamp:b.timeStamp},h)}}ca(a){window!==window.top&&window.focus();this.Da(a.target)&&document.activeElement&&!this.Da(document.activeElement)&&document.activeElement.blur()}Da(a){return!a||a===document||a===window||a===document.body||"canvas"===a.tagName.toLowerCase()}cb(){this.Ka||(this.Ka=!0,window.addEventListener("deviceorientation",a=>this.xb(a)),window.addEventListener("deviceorientationabsolute",a=>this.yb(a)))}bb(){this.Ja||(this.Ja=!0,window.addEventListener("devicemotion",
a=>this.wb(a)))}xb(a){t(this,"deviceorientation",{absolute:!!a.absolute,alpha:a.alpha||0,beta:a.beta||0,gamma:a.gamma||0,timeStamp:a.timeStamp,webkitCompassHeading:a.webkitCompassHeading,webkitCompassAccuracy:a.webkitCompassAccuracy},h)}yb(a){t(this,"deviceorientationabsolute",{absolute:!!a.absolute,alpha:a.alpha||0,beta:a.beta||0,gamma:a.gamma||0,timeStamp:a.timeStamp},h)}wb(a){let b=null;var e=a.acceleration;e&&(b={x:e.x||0,y:e.y||0,z:e.z||0});e=null;var g=a.accelerationIncludingGravity;g&&(e={x:g.x||
0,y:g.y||0,z:g.z||0});g=null;const l=a.rotationRate;l&&(g={alpha:l.alpha||0,beta:l.beta||0,gamma:l.gamma||0});t(this,"devicemotion",{acceleration:b,accelerationIncludingGravity:e,rotationRate:g,interval:a.interval,timeStamp:a.timeStamp},h)}Nb(a){const b=this.h,e=b.c;e.style.width=a.styleWidth+"px";e.style.height=a.styleHeight+"px";e.style.marginLeft=a.marginLeft+"px";e.style.marginTop=a.marginTop+"px";b.ya();this.Na&&(e.style.display="",this.Na=!1)}Cb(a){const b=a.url;a=a.filename;const e=document.createElement("a"),
g=document.body;e.textContent=a;e.href=b;e.download=a;g.appendChild(e);e.click();g.removeChild(e)}async Hb(a){var b=a.imageBitmapOpts;a=await self.C3_RasterSvgImageBlob(a.blob,a.imageWidth,a.imageHeight,a.surfaceWidth,a.surfaceHeight);b=b?await createImageBitmap(a,b):await createImageBitmap(a);return{imageBitmap:b,transferables:[b]}}async Ab(a){return await self.C3_GetSvgImageSize(a.blob)}async qb(a){await u(a.url)}ia(){var a=[...this.na];this.na.clear();if(!this.Vb)for(const b of a)(a=b.play())&&
a.catch(()=>{this.Xb.has(b)||this.na.add(b)})}Bb(){navigator.splashscreen&&navigator.splashscreen.hide&&navigator.splashscreen.hide()}vb(a){if(a.show){this.l||(this.l=document.createElement("div"),this.l.id="inspectOutline",document.body.appendChild(this.l));var b=this.l;b.style.display="";b.style.left=a.left-1+"px";b.style.top=a.top-1+"px";b.style.width=a.width+2+"px";b.style.height=a.height+2+"px";b.textContent=a.name}else this.l&&(this.l.style.display="none")}Ib(){window.C3_RegisterSW&&window.C3_RegisterSW()}Fa(a){window.c3_postToMessagePort&&
(a.from="runtime",window.c3_postToMessagePort(a))}pb(a,b){return this.h.$a(this.A,{name:a,params:b})}rb(a){alert(a.message)}})}"use strict";
{const k=document.currentScript.src;self.Za=class{constructor(m){this.U=m;this.b=k?k.substr(0,k.lastIndexOf("/")+1):m.b;this.Wb=Math.min(navigator.hardwareConcurrency||2,16);this.ja=null;this.Oa=[];this.oa=this.ka=null}async Ya(){if(this.Tb)throw Error("already initialised");this.Tb=!0;var m=this.U.ba("dispatchworker.js");this.ja=await this.U.W(m,this.b,{name:"DispatchWorker"});m=new MessageChannel;this.ka=m.port1;this.ja.postMessage({type:"_init","in-port":m.port2},[m.port2]);this.oa=await this.za()}async za(){const m=
this.Oa.length;var d=this.U.ba("jobworker.js");d=await this.U.W(d,this.b,{name:"JobWorker"+m});const h=new MessageChannel,n=new MessageChannel;this.ja.postMessage({type:"_addJobWorker",port:h.port1},[h.port1]);d.postMessage({type:"init",number:m,"dispatch-port":h.port2,"output-port":n.port2},[h.port2,n.port2]);this.Oa.push(d);return n.port1}Wa(){return{inputPort:this.ka,outputPort:this.oa,maxNumWorkers:this.Wb}}Xa(){return[this.ka,this.oa]}}}"use strict";
window.C3_IsSupported&&(window.c3_runtimeInterface=new self.J({hc:!0,ic:"workermain.js",u:["scripts/c3runtime.js"],dc:"scripts/",sa:[],Sa:"html5"}));"use strict";async function L(k,m){m=m.type;let d=!0;0===m?d=await M():1===m&&(d=await N());t(k,"permission-result",{type:m,result:d})}
async function M(){if(!self.DeviceOrientationEvent||!self.DeviceOrientationEvent.requestPermission)return!0;try{return"granted"===await self.DeviceOrientationEvent.requestPermission()}catch(k){return console.warn("[Touch] Failed to request orientation permission: ",k),!1}}
async function N(){if(!self.DeviceMotionEvent||!self.DeviceMotionEvent.requestPermission)return!0;try{return"granted"===await self.DeviceMotionEvent.requestPermission()}catch(k){return console.warn("[Touch] Failed to request motion permission: ",k),!1}}self.J.V(class extends self.X{constructor(k){super(k,"touch");D(this,"request-permission",m=>L(this,m))}});"use strict";
{function k(d){d.stopPropagation()}function m(d){13!==d.which&&27!==d.which&&d.stopPropagation()}self.J.V(class extends self.Va{constructor(d){super(d,"text-input");H(this,"scroll-to-bottom",h=>this.Lb(h))}wa(d,h){let n;const w=h.type;"textarea"===w?(n=document.createElement("textarea"),n.style.resize="none"):(n=document.createElement("input"),n.type=w);n.style.position="absolute";n.autocomplete="off";n.addEventListener("touchstart",k);n.addEventListener("touchmove",k);n.addEventListener("touchend",
k);n.addEventListener("mousedown",k);n.addEventListener("mouseup",k);n.addEventListener("keydown",m);n.addEventListener("keyup",m);n.addEventListener("click",u=>{u.stopPropagation();I(this,"click",d)});n.addEventListener("dblclick",u=>{u.stopPropagation();I(this,"dblclick",d)});n.addEventListener("input",()=>G(this,"change",d,{text:n.value}));h.id&&(n.id=h.id);this.$(n,h);return n}$(d,h){d.value=h.text;d.placeholder=h.placeholder;d.title=h.title;d.disabled=!h.isEnabled;d.readOnly=h.isReadOnly;d.spellcheck=
h.spellCheck;h=h.maxLength;0>h?d.removeAttribute("maxlength"):d.setAttribute("maxlength",h)}Lb(d){d.scrollTop=d.scrollHeight}})};