'use strict';function u(g,e,c,h){g.f.ja(g.K,e,c,h,void 0)}function z(g,e,c,h){g.f.i?u(g,e,c,h):g.f.vb()._OnMessageFromDOM({type:"event",component:g.K,handler:e,dispatchOpts:h||null,data:c,responseId:null})}function B(g,e,c){g.f.b(g.K,e,c)}function G(g,e){for(const [c,h]of e)B(g,c,h)}window.T=class{constructor(g,e){this.f=g;this.K=e}Ia(){}};
window.kb=class{constructor(g,e){this.Xa=g;this.ic=e;this.D=-1;this.aa=-Infinity;this.nc=()=>{this.D=-1;this.aa=Date.now();this.L=!0;this.Xa();this.L=!1};this.Ya=this.L=!1}};"use strict";function I(g,e){const c=e.elementId,h=g.S(c,e);g.h.set(c,h);e.isVisible||(h.style.display="none");e=g.ma(h);e.addEventListener("focus",()=>{M(g,"elem-focused",c)});e.addEventListener("blur",()=>{M(g,"elem-blurred",c)});g.Y&&document.body.appendChild(h)}
function O(g,e,c){B(g,e,h=>{const m=g.h.get(h.elementId);return c(m,h)})}function M(g,e,c,h){h||(h={});h.elementId=c;u(g,e,h)}function P(g,e,c,h){h||(h={});h.elementId=c;z(g,e,h)}
window.ha=class extends self.T{constructor(g,e){super(g,e);this.h=new Map;this.Y=!0;G(this,[["create",c=>I(this,c)],["destroy",c=>{{c=c.elementId;const h=this.h.get(c);this.Y&&h.parentElement.removeChild(h);this.h.delete(c)}}],["set-visible",c=>{this.Y&&(this.h.get(c.elementId).style.display=c.isVisible?"":"none")}],["update-position",c=>{if(this.Y){var h=this.h.get(c.elementId);h.style.left=c.left+"px";h.style.top=c.top+"px";h.style.width=c.width+"px";h.style.height=c.height+"px";c=c.fontSize;null!==
c&&(h.style.fontSize=c+"em")}}],["update-state",c=>{{const h=this.h.get(c.elementId);this.m(h,c)}}],["focus",c=>this.ua(c)],["set-css-style",c=>{this.h.get(c.elementId).style[c.prop]=c.val}],["set-attribute",c=>{this.h.get(c.elementId).setAttribute(c.name,c.val)}],["remove-attribute",c=>{this.h.get(c.elementId).removeAttribute(c.name)}]]);O(this,"get-element",c=>c)}S(){throw Error("required override");}m(){throw Error("required override");}ma(g){return g}ua(g){const e=this.ma(this.h.get(g.elementId));
g.focus?e.focus():e.blur()}};"use strict";
{const g=/(iphone|ipod|ipad|macos|macintosh|mac os x)/i.test(navigator.userAgent);let e=0;function c(l){const a=document.createElement("script");a.async=!1;a.type="module";return l.sc?new Promise(f=>{const k="c3_resolve_"+e;++e;self[k]=f;a.textContent=l.vc+`\n\nself["${k}"]();`;document.head.appendChild(a)}):new Promise((f,k)=>{a.onload=f;a.onerror=k;a.src=l;document.head.appendChild(a)})}let h=!1,m=!1;function y(){if(!h){try{new Worker("blob://",{get type(){m=!0}})}catch(l){}h=!0}return m}const q=
/safari\//i.test(navigator.userAgent)&&!/chrome\/|chromium\/|edg\//i.test(navigator.userAgent);let v=new Audio;const C={"audio/webm; codecs=opus":!!v.canPlayType("audio/webm; codecs=opus")&&!q,"audio/ogg; codecs=opus":!!v.canPlayType("audio/ogg; codecs=opus"),"audio/webm; codecs=vorbis":!!v.canPlayType("audio/webm; codecs=vorbis"),"audio/ogg; codecs=vorbis":!!v.canPlayType("audio/ogg; codecs=vorbis"),"audio/mp4":!!v.canPlayType("audio/mp4"),"audio/mpeg":!!v.canPlayType("audio/mpeg")};v=null;async function N(l){l=
await J(l);return(new TextDecoder("utf-8")).decode(l)}function J(l){return new Promise((a,f)=>{const k=new FileReader;k.onload=n=>a(n.target.result);k.onerror=n=>f(n);k.readAsArrayBuffer(l)})}const A=[];let D=0;window.RealFile=window.File;const E=[],w=new Map,F=new Map;let H=0;const K=[];self.runOnStartup=function(l){if("function"!==typeof l)throw Error("runOnStartup called without a function");K.push(l)};const b=new Set(["cordova","playable-ad","instant-games"]);let d=!1;window.j=class l{constructor(a){this.i=
a.xc;this.N=null;this.c="";this.da=a.uc;this.R={};this.Ba=this.bb=null;this.Z=[];this.M=this.g=this.Ea=null;this.B=-1;this.mc=()=>this.Rb();this.ab=[];this.a=a.cb;this.$="file"===location.protocol.substr(0,4);!this.i||"undefined"!==typeof OffscreenCanvas&&navigator.userActivation&&y()||(this.i=!1);if("playable-ad"===this.a||"instant-games"===this.a)this.i=!1;if("cordova"===this.a&&this.i)if(/android/i.test(navigator.userAgent)){const f=/Chrome\/(\d+)/i.exec(navigator.userAgent);f&&90<=parseInt(f[1],
10)||(this.i=!1)}else this.i=!1;this.ba=this.l=null;"html5"!==this.a&&"playable-ad"!==this.a||!this.$||alert("Exported games won't work until you upload them. (When running on the file: protocol, browsers block many features from working for security reasons.)");this.b("runtime","cordova-fetch-local-file",f=>this.Db(f));this.b("runtime","create-job-worker",()=>this.Eb());"cordova"===this.a?document.addEventListener("deviceready",()=>this.Na(a)):this.Na(a)}hb(){return g&&"cordova"===this.a}ia(){const a=
navigator.userAgent;return g&&b.has(this.a)||navigator.standalone||/crios\/|fxios\/|edgios\//i.test(a)}async Na(a){"macos-wkwebview"===this.a&&this.xa({type:"ready"});if("playable-ad"===this.a){this.l=self.c3_base64files;this.ba={};await this.qb();for(let k=0,n=a.F.length;k<n;++k){var f=a.F[k].toLowerCase();this.ba.hasOwnProperty(f)?a.F[k]={sc:!0,vc:this.ba[f]}:this.l.hasOwnProperty(f)&&(a.F[k]=URL.createObjectURL(this.l[f]))}}a.oc?this.c=a.oc:(f=location.origin,this.c=("null"===f?"file:///":f)+location.pathname,
f=this.c.lastIndexOf("/"),-1!==f&&(this.c=this.c.substr(0,f+1)));a.zc&&(this.R=a.zc);f=new MessageChannel;this.N=f.port1;this.N.onmessage=k=>this._OnMessageFromRuntime(k.data);window.c3_addPortMessageHandler&&window.c3_addPortMessageHandler(k=>this.Ob(k));this.M=new self.ib(this);await Q(this.M);"object"===typeof window.StatusBar&&window.StatusBar.hide();"object"===typeof window.AndroidFullScreen&&window.AndroidFullScreen.immersiveMode();this.i?await this.xb(a,f.port2):await this.wb(a,f.port2)}oa(a){a=
this.R.hasOwnProperty(a)?this.R[a]:a.endsWith("/workermain.js")&&this.R.hasOwnProperty("workermain.js")?this.R["workermain.js"]:"playable-ad"===this.a&&this.l.hasOwnProperty(a.toLowerCase())?this.l[a.toLowerCase()]:a;a instanceof Blob&&(a=URL.createObjectURL(a));return a}async ga(a,f,k){if(a.startsWith("blob:"))return new Worker(a,k);if("cordova"===this.a&&this.$)return a=await this.fa(k.rc?a:this.da+a),new Worker(URL.createObjectURL(new Blob([a],{type:"application/javascript"})),k);a=new URL(a,f);
if(location.origin!==a.origin){a=await fetch(a);if(!a.ok)throw Error("failed to fetch worker script");a=await a.blob();return new Worker(URL.createObjectURL(a),k)}return new Worker(a,k)}s(){return Math.max(window.innerWidth,1)}o(){return Math.max(window.innerHeight,1)}La(a){var f=this.M;return{baseUrl:this.c,windowInnerWidth:this.s(),windowInnerHeight:this.o(),devicePixelRatio:window.devicePixelRatio,isFullscreen:l.G(),projectData:a.Fc,previewImageBlobs:window.cr_previewImageBlobs||this.l,previewProjectFileBlobs:window.cr_previewProjectFileBlobs,
previewProjectFileSWUrls:window.cr_previewProjectFiles,swClientId:window.Dc||"",exportType:a.cb,isDebug:-1<self.location.search.indexOf("debug"),ife:!!self.Ec,jobScheduler:{inputPort:f.za,outputPort:f.Da,maxNumWorkers:f.kc},supportedAudioFormats:C,opusWasmScriptUrl:window.cr_opusWasmScriptUrl||this.da+"opus.wasm.js",opusWasmBinaryUrl:window.cr_opusWasmBinaryUrl||this.da+"opus.wasm.wasm",isFileProtocol:this.$,isiOSCordova:this.hb(),isiOSWebView:this.ia(),isFBInstantAvailable:"undefined"!==typeof self.FBInstant}}async xb(a,
f){var k=this.oa(a.yc);this.bb=await this.ga(k,this.c,{type:"module",name:"Runtime",rc:!0});this.g=document.createElement("canvas");this.g.style.display="none";k=this.g.transferControlToOffscreen();document.body.appendChild(this.g);window.c3canvas=this.g;let n=a.Ha||[],t=a.F;n=await Promise.all(n.map(p=>this.A(p)));t=await Promise.all(t.map(p=>this.A(p)));if("cordova"===this.a)for(let p=0,r=a.ea.length;p<r;++p){const x=a.ea[p],L=x[0];if(L===a.Ga||"scriptsInEvents.js"===L||L.endsWith("/scriptsInEvents.js"))x[1]=
await this.A(L)}this.bb.postMessage(Object.assign(this.La(a),{type:"init-runtime",isInWorker:!0,messagePort:f,canvas:k,workerDependencyScripts:n,engineScripts:t,projectScripts:a.ea,mainProjectScript:a.Ga,projectScriptsStatus:self.C3_ProjectScriptsStatus}),[f,k,...R(this.M)]);this.Z=E.map(p=>new p(this));this.Ka();self.c3_callFunction=(p,r)=>this.Ea.yb(p,r);"preview"===this.a&&(self.goToLastErrorScript=()=>this.ja("runtime","go-to-last-error-script"))}async wb(a,f){this.g=document.createElement("canvas");
this.g.style.display="none";document.body.appendChild(this.g);window.c3canvas=this.g;this.Z=E.map(p=>new p(this));this.Ka();var k=a.F.map(p=>"string"===typeof p?(new URL(p,this.c)).toString():p);Array.isArray(a.Ha)&&k.unshift(...a.Ha);k=await Promise.all(k.map(p=>this.A(p)));await Promise.all(k.map(p=>c(p)));k=self.C3_ProjectScriptsStatus;const n=a.Ga,t=a.ea;for(let [p,r]of t)if(r||(r=p),p===n)try{r=await this.A(r),await c(r),"preview"!==this.a||k[p]||this.Ta(p,"main script did not run to completion")}catch(x){this.Ta(p,
x)}else if("scriptsInEvents.js"===p||p.endsWith("/scriptsInEvents.js"))r=await this.A(r),await c(r);"preview"===this.a&&"object"!==typeof self.Ac.Bc?(this.W(),console.error("[C3 runtime] Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax."),alert("Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax.")):(a=Object.assign(this.La(a),{isInWorker:!1,messagePort:f,canvas:this.g,runOnStartupFunctions:K}),this.Pa(),this.Ba=
self.C3_CreateRuntime(a),await self.C3_InitRuntime(this.Ba,a))}Ta(a,f){this.W();console.error(`[Preview] Failed to load project main script (${a}): `,f);alert(`Failed to load project main script (${a}). Check all your JavaScript code has valid syntax. Press F12 and check the console for error details.`)}Pa(){this.W()}W(){const a=window.pc;a&&(a.parentElement.removeChild(a),window.pc=null)}async Eb(){const a=await S(this.M);return{outputPort:a,transferables:[a]}}vb(){if(this.i)throw Error("not available in worker mode");
return this.Ba}ja(a,f,k,n,t){this.N.postMessage({type:"event",component:a,handler:f,dispatchOpts:n||null,data:k,responseId:null},t)}jb(a,f){const k=H++,n=new Promise((t,p)=>{F.set(k,{resolve:t,reject:p})});this.N.postMessage({type:"event",component:a,handler:"js-invoke-function",dispatchOpts:null,data:f,responseId:k},void 0);return n}["_OnMessageFromRuntime"](a){const f=a.type;if("event"===f)return this.Jb(a);if("result"===f)this.Vb(a);else if("runtime-ready"===f)this.Wb();else if("alert-error"===
f)this.W(),alert(a.message);else if("creating-runtime"===f)this.Pa();else throw Error(`unknown message '${f}'`);}Jb(a){const f=a.component,k=a.handler,n=a.data,t=a.responseId;if(a=w.get(f))if(a=a.get(k)){var p=null;try{p=a(n)}catch(r){console.error(`Exception in '${f}' handler '${k}':`,r);null!==t&&this.V(t,!1,""+r);return}if(null===t)return p;p&&p.then?p.then(r=>this.V(t,!0,r)).catch(r=>{console.error(`Rejection from '${f}' handler '${k}':`,r);this.V(t,!1,""+r)}):this.V(t,!0,p)}else console.warn(`[DOM] No handler '${k}' for component '${f}'`);
else console.warn(`[DOM] No event handlers for component '${f}'`)}V(a,f,k){let n;k&&k.transferables&&(n=k.transferables);this.N.postMessage({type:"result",responseId:a,isOk:f,result:k},n)}Vb(a){const f=a.responseId,k=a.isOk;a=a.result;const n=F.get(f);k?n.resolve(a):n.reject(a);F.delete(f)}b(a,f,k){let n=w.get(a);n||(n=new Map,w.set(a,n));if(n.has(f))throw Error(`[DOM] Component '${a}' already has handler '${f}'`);n.set(f,k)}static v(a){if(E.includes(a))throw Error("DOM handler already added");E.push(a)}Ka(){for(const a of this.Z)if("runtime"===
a.K){this.Ea=a;return}throw Error("cannot find runtime DOM handler");}Ob(a){this.ja("debugger","message",a)}Wb(){for(const a of this.Z)a.Ia()}static G(){return!!(document.fullscreenElement||document.webkitFullscreenElement||document.mozFullScreenElement||d)}static X(a){d=!!a}Ua(){-1===this.B&&this.ab.length&&(this.B=requestAnimationFrame(this.mc))}ob(){-1!==this.B&&(cancelAnimationFrame(this.B),this.B=-1)}Rb(){this.B=-1;for(const a of this.ab)a();this.Ua()}wa(){this.Ea.wa()}fb(a){return/^(?:[a-z\-]+:)?\/\//.test(a)||
"data:"===a.substr(0,5)||"blob:"===a.substr(0,5)}gb(a){return!this.fb(a)}async A(a){return"cordova"===this.a&&(a.startsWith("file:")||this.$&&this.gb(a))?(a.startsWith(this.c)&&(a=a.substr(this.c.length)),a=await this.fa(a),URL.createObjectURL(new Blob([a],{type:"application/javascript"}))):a}async Db(a){const f=a.filename;switch(a.as){case "text":return await this.eb(f);case "buffer":return await this.fa(f);default:throw Error("unsupported type");}}Ja(a){const f=window.cordova.file.applicationDirectory+
"www/"+a.toLowerCase();return new Promise((k,n)=>{window.resolveLocalFileSystemURL(f,t=>{t.file(k,n)},n)})}async eb(a){a=await this.Ja(a);return await N(a)}ka(){if(A.length&&!(8<=D)){D++;var a=A.shift();this.rb(a.filename,a.wc,a.qc)}}fa(a){return new Promise((f,k)=>{A.push({filename:a,wc:n=>{D--;this.ka();f(n)},qc:n=>{D--;this.ka();k(n)}});this.ka()})}async rb(a,f,k){try{const n=await this.Ja(a),t=await J(n);f(t)}catch(n){k(n)}}xa(a){if("windows-webview2"===this.a)window.chrome.webview.postMessage(JSON.stringify(a));
else if("macos-wkwebview"===this.a)window.webkit.messageHandlers.C3Wrapper.postMessage(JSON.stringify(a));else throw Error("cannot send wrapper message");}async qb(){const a=[];for(const [f,k]of Object.entries(this.l))a.push(this.pb(f,k));await Promise.all(a)}async pb(a,f){if("object"===typeof f)this.l[a]=new Blob([f.str],{type:f.type}),this.ba[a]=f.str;else{let k=await this.ub(f);k||(k=this.sb(f));this.l[a]=k}}async ub(a){try{return await (await fetch(a)).blob()}catch(f){return console.warn("Failed to fetch a data: URI. Falling back to a slower workaround. This is probably because the Content Security Policy unnecessarily blocked it. Allow data: URIs in your CSP to avoid this.",
f),null}}sb(a){a=this.dc(a);return this.nb(a.data,a.tc)}dc(a){var f=a.indexOf(",");if(0>f)throw new URIError("expected comma in data: uri");var k=a.substring(f+1);f=a.substring(5,f).split(";");a=f[0]||"";const n=f[2];k="base64"===f[1]||"base64"===n?atob(k):decodeURIComponent(k);return{tc:a,data:k}}nb(a,f){var k=a.length;let n=k>>2,t=new Uint8Array(k),p=new Uint32Array(t.buffer,0,n),r,x;for(x=r=0;r<n;++r)p[r]=a.charCodeAt(x++)|a.charCodeAt(x++)<<8|a.charCodeAt(x++)<<16|a.charCodeAt(x++)<<24;for(k&=
3;k--;)t[x]=a.charCodeAt(x),++x;return new Blob([t],{type:f})}}}"use strict";
{const g=self.j;function e(b){return b.sourceCapabilities&&b.sourceCapabilities.firesTouchEvents||b.originalEvent&&b.originalEvent.sourceCapabilities&&b.originalEvent.sourceCapabilities.firesTouchEvents}const c=new Map([["OSLeft","MetaLeft"],["OSRight","MetaRight"]]),h={dispatchRuntimeEvent:!0,dispatchUserScriptEvent:!0},m={dispatchUserScriptEvent:!0},y={dispatchRuntimeEvent:!0};function q(b){return new Promise((d,l)=>{const a=document.createElement("link");a.onload=()=>d(a);a.onerror=f=>l(f);a.rel=
"stylesheet";a.href=b;document.head.appendChild(a)})}function v(b){return new Promise((d,l)=>{const a=new Image;a.onload=()=>d(a);a.onerror=f=>l(f);a.src=b})}async function C(b){b=URL.createObjectURL(b);try{return await v(b)}finally{URL.revokeObjectURL(b)}}function N(b){return new Promise((d,l)=>{let a=new FileReader;a.onload=f=>d(f.target.result);a.onerror=f=>l(f);a.readAsText(b)})}async function J(b,d,l){if(!/firefox/i.test(navigator.userAgent))return await C(b);var a=await N(b);a=(new DOMParser).parseFromString(a,
"image/svg+xml");const f=a.documentElement;if(f.hasAttribute("width")&&f.hasAttribute("height")){const k=f.getAttribute("width"),n=f.getAttribute("height");if(!k.includes("%")&&!n.includes("%"))return await C(b)}f.setAttribute("width",d+"px");f.setAttribute("height",l+"px");a=(new XMLSerializer).serializeToString(a);b=new Blob([a],{type:"image/svg+xml"});return await C(b)}function A(b){do{if(b.parentNode&&b.hasAttribute("contenteditable"))return!0;b=b.parentNode}while(b);return!1}const D=new Set(["input",
"textarea","datalist","select"]),E=new Set(["canvas","body","html"]);function w(b){E.has(b.target.tagName.toLowerCase())&&b.preventDefault()}function F(b){(b.metaKey||b.ctrlKey)&&b.preventDefault()}self.C3_GetSvgImageSize=async function(b){b=await C(b);if(0<b.width&&0<b.height)return[b.width,b.height];{b.style.position="absolute";b.style.left="0px";b.style.top="0px";b.style.visibility="hidden";document.body.appendChild(b);const d=b.getBoundingClientRect();document.body.removeChild(b);return[d.width,
d.height]}};self.C3_RasterSvgImageBlob=async function(b,d,l,a,f){b=await J(b,d,l);const k=document.createElement("canvas");k.width=a;k.height=f;k.getContext("2d").drawImage(b,0,0,d,l);return k};let H=!1;document.addEventListener("pause",()=>H=!0);document.addEventListener("resume",()=>H=!1);function K(){try{return window.parent&&window.parent.document.hasFocus()}catch(b){return!1}}g.v(class extends self.T{constructor(b){super(b,"runtime");this.Za=!0;this.C=-1;this.Fa="any";this.Va=this.Wa=!1;this.Aa=
this.P=this.u=null;b.b("canvas","update-size",a=>this.ac(a));b.b("runtime","invoke-download",a=>this.Mb(a));b.b("runtime","raster-svg-image",a=>this.Sb(a));b.b("runtime","get-svg-image-size",a=>this.Kb(a));b.b("runtime","set-target-orientation",a=>this.$b(a));b.b("runtime","register-sw",()=>this.Tb());b.b("runtime","post-to-debugger",a=>this.Ra(a));b.b("runtime","go-to-script",a=>this.Ra(a));b.b("runtime","before-start-ticking",()=>this.Bb());b.b("runtime","debug-highlight",a=>this.Fb(a));b.b("runtime",
"enable-device-orientation",()=>this.mb());b.b("runtime","enable-device-motion",()=>this.lb());b.b("runtime","add-stylesheet",a=>this.Ab(a));b.b("runtime","alert",a=>this.qa(a));b.b("runtime","hide-cordova-splash",()=>this.Lb());const d=new Set(["input","textarea","datalist"]);window.addEventListener("contextmenu",a=>{const f=a.target;d.has(f.tagName.toLowerCase())||A(f)||a.preventDefault()});const l=b.g;window.addEventListener("selectstart",w);window.addEventListener("gesturehold",w);l.addEventListener("selectstart",
w);l.addEventListener("gesturehold",w);window.addEventListener("touchstart",w,{passive:!1});"undefined"!==typeof PointerEvent?(window.addEventListener("pointerdown",w,{passive:!1}),l.addEventListener("pointerdown",w)):l.addEventListener("touchstart",w);this.O=0;window.addEventListener("mousedown",a=>{1===a.button&&a.preventDefault()});window.addEventListener("mousewheel",F,{passive:!1});window.addEventListener("wheel",F,{passive:!1});window.addEventListener("resize",()=>this.bc());window.addEventListener("fullscreenchange",
()=>this.H());window.addEventListener("webkitfullscreenchange",()=>this.H());window.addEventListener("mozfullscreenchange",()=>this.H());window.addEventListener("fullscreenerror",a=>this.ra(a));window.addEventListener("webkitfullscreenerror",a=>this.ra(a));window.addEventListener("mozfullscreenerror",a=>this.ra(a));b.ia()&&window.addEventListener("focusout",()=>{{const k=document.activeElement;if(k){var a=k.tagName.toLowerCase();var f=new Set("email number password search tel text url".split(" "));
a="textarea"===a?!0:"input"===a?f.has(k.type.toLowerCase()||"text"):A(k)}else a=!1}a||(document.scrollingElement.scrollTop=0)});self.C3WrapperOnMessage=a=>this.cc(a);this.Ca=new Set;this.lc=new WeakSet;this.jc=!1}Bb(){"cordova"===this.f.a?(document.addEventListener("pause",()=>this.va(!0)),document.addEventListener("resume",()=>this.va(!1))):document.addEventListener("visibilitychange",()=>this.va(document.hidden));return{isSuspended:!(!document.hidden&&!H)}}Ia(){window.addEventListener("focus",()=>
this.J("window-focus"));window.addEventListener("blur",()=>{this.J("window-blur",{parentHasFocus:K()});this.O=0});window.addEventListener("focusin",d=>{d=d.target;(D.has(d.tagName.toLowerCase())||A(d))&&this.J("keyboard-blur")});window.addEventListener("keydown",d=>this.Qa("keydown",d));window.addEventListener("keyup",d=>this.Qa("keyup",d));window.addEventListener("dblclick",d=>this.sa("dblclick",d,h));window.addEventListener("wheel",d=>this.Pb(d));"undefined"!==typeof PointerEvent?(window.addEventListener("pointerdown",
d=>{this.pa(d);this.I("pointerdown",d)}),this.f.i&&"undefined"!==typeof window.onpointerrawupdate&&self===self.top?(this.P=new self.kb(()=>this.tb(),5),this.P.Ya=!0,window.addEventListener("pointerrawupdate",d=>this.Qb(d))):window.addEventListener("pointermove",d=>this.I("pointermove",d)),window.addEventListener("pointerup",d=>this.I("pointerup",d)),window.addEventListener("pointercancel",d=>this.I("pointercancel",d))):(window.addEventListener("mousedown",d=>{this.pa(d);this.ta("pointerdown",d)}),
window.addEventListener("mousemove",d=>this.ta("pointermove",d)),window.addEventListener("mouseup",d=>this.ta("pointerup",d)),window.addEventListener("touchstart",d=>{this.pa(d);this.U("pointerdown",d)}),window.addEventListener("touchmove",d=>this.U("pointermove",d)),window.addEventListener("touchend",d=>this.U("pointerup",d)),window.addEventListener("touchcancel",d=>this.U("pointercancel",d)));const b=()=>this.wa();window.addEventListener("pointerup",b,!0);window.addEventListener("touchend",b,!0);
window.addEventListener("click",b,!0);window.addEventListener("keydown",b,!0);window.addEventListener("gamepadconnected",b,!0)}J(b,d){u(this,b,d||null,y)}s(){return this.f.s()}o(){return this.f.o()}bc(){const b=this.s(),d=this.o();this.J("window-resize",{innerWidth:b,innerHeight:d,devicePixelRatio:window.devicePixelRatio,isFullscreen:g.G()});this.f.ia()&&(-1!==this.C&&clearTimeout(this.C),this.Sa(b,d,0))}ec(b,d,l){-1!==this.C&&clearTimeout(this.C);this.C=setTimeout(()=>this.Sa(b,d,l),48)}Sa(b,d,l){const a=
this.s(),f=this.o();this.C=-1;a!=b||f!=d?this.J("window-resize",{innerWidth:a,innerHeight:f,devicePixelRatio:window.devicePixelRatio,isFullscreen:g.G()}):10>l&&this.ec(a,f,l+1)}$b(b){this.Fa=b.targetOrientation}fc(){const b=this.Fa;if(screen.orientation&&screen.orientation.lock)screen.orientation.lock(b).catch(d=>console.warn("[Construct 3] Failed to lock orientation: ",d));else try{let d=!1;screen.lockOrientation?d=screen.lockOrientation(b):screen.webkitLockOrientation?d=screen.webkitLockOrientation(b):
screen.mozLockOrientation?d=screen.mozLockOrientation(b):screen.msLockOrientation&&(d=screen.msLockOrientation(b));d||console.warn("[Construct 3] Failed to lock orientation")}catch(d){console.warn("[Construct 3] Failed to lock orientation: ",d)}}H(){const b=g.G();b&&"any"!==this.Fa&&this.fc();u(this,"fullscreenchange",{isFullscreen:b,innerWidth:this.s(),innerHeight:this.o()})}ra(b){console.warn("[Construct 3] Fullscreen request failed: ",b);u(this,"fullscreenerror",{isFullscreen:g.G(),innerWidth:this.s(),
innerHeight:this.o()})}va(b){b?this.f.ob():this.f.Ua();u(this,"visibilitychange",{hidden:b})}Qa(b,d){"Backspace"===d.key&&w(d);const l=c.get(d.code)||d.code;z(this,b,{code:l,key:d.key,which:d.which,repeat:d.repeat,altKey:d.altKey,ctrlKey:d.ctrlKey,metaKey:d.metaKey,shiftKey:d.shiftKey,timeStamp:d.timeStamp},h)}Pb(b){u(this,"wheel",{clientX:b.clientX,clientY:b.clientY,pageX:b.pageX,pageY:b.pageY,deltaX:b.deltaX,deltaY:b.deltaY,deltaZ:b.deltaZ,deltaMode:b.deltaMode,timeStamp:b.timeStamp},h)}sa(b,d,
l){e(d)||z(this,b,{button:d.button,buttons:d.buttons,clientX:d.clientX,clientY:d.clientY,pageX:d.pageX,pageY:d.pageY,timeStamp:d.timeStamp},l)}ta(b,d){if(!e(d)){var l=this.O;"pointerdown"===b&&0!==l?b="pointermove":"pointerup"===b&&0!==d.buttons&&(b="pointermove");z(this,b,{pointerId:1,pointerType:"mouse",button:d.button,buttons:d.buttons,lastButtons:l,clientX:d.clientX,clientY:d.clientY,pageX:d.pageX,pageY:d.pageY,width:0,height:0,pressure:0,tangentialPressure:0,tiltX:0,tiltY:0,twist:0,timeStamp:d.timeStamp},
h);this.O=d.buttons;this.sa(d.type,d,m)}}I(b,d){if(this.P&&"pointermove"!==b){var l=this.P;l.L||(-1!==l.D&&(self.clearTimeout(l.D),l.D=-1),l.aa=Date.now())}l=0;"mouse"===d.pointerType&&(l=this.O);z(this,b,{pointerId:d.pointerId,pointerType:d.pointerType,button:d.button,buttons:d.buttons,lastButtons:l,clientX:d.clientX,clientY:d.clientY,pageX:d.pageX,pageY:d.pageY,width:d.width||0,height:d.height||0,pressure:d.pressure||0,tangentialPressure:d.tangentialPressure||0,tiltX:d.tiltX||0,tiltY:d.tiltY||0,
twist:d.twist||0,timeStamp:d.timeStamp},h);"mouse"===d.pointerType&&(l="mousemove","pointerdown"===b?l="mousedown":"pointerup"===b&&(l="mouseup"),this.sa(l,d,m),this.O=d.buttons)}Qb(b){this.Aa=b;b=this.P;if(-1===b.D){var d=Date.now(),l=d-b.aa,a=b.ic;l>=a&&b.Ya?(b.aa=d,b.L=!0,b.Xa(),b.L=!1):b.D=self.setTimeout(b.nc,Math.max(a-l,4))}}tb(){this.I("pointermove",this.Aa);this.Aa=null}U(b,d){for(let l=0,a=d.changedTouches.length;l<a;++l){const f=d.changedTouches[l];z(this,b,{pointerId:f.identifier,pointerType:"touch",
button:0,buttons:0,lastButtons:0,clientX:f.clientX,clientY:f.clientY,pageX:f.pageX,pageY:f.pageY,width:2*(f.radiusX||f.webkitRadiusX||0),height:2*(f.radiusY||f.webkitRadiusY||0),pressure:f.force||f.webkitForce||0,tangentialPressure:0,tiltX:0,tiltY:0,twist:f.rotationAngle||0,timeStamp:d.timeStamp},h)}}pa(b){window!==window.top&&window.focus();this.Oa(b.target)&&document.activeElement&&!this.Oa(document.activeElement)&&document.activeElement.blur()}Oa(b){return!b||b===document||b===window||b===document.body||
"canvas"===b.tagName.toLowerCase()}mb(){this.Wa||(this.Wa=!0,window.addEventListener("deviceorientation",b=>this.Hb(b)),window.addEventListener("deviceorientationabsolute",b=>this.Ib(b)))}lb(){this.Va||(this.Va=!0,window.addEventListener("devicemotion",b=>this.Gb(b)))}Hb(b){u(this,"deviceorientation",{absolute:!!b.absolute,alpha:b.alpha||0,beta:b.beta||0,gamma:b.gamma||0,timeStamp:b.timeStamp,webkitCompassHeading:b.webkitCompassHeading,webkitCompassAccuracy:b.webkitCompassAccuracy},h)}Ib(b){u(this,
"deviceorientationabsolute",{absolute:!!b.absolute,alpha:b.alpha||0,beta:b.beta||0,gamma:b.gamma||0,timeStamp:b.timeStamp},h)}Gb(b){let d=null;var l=b.acceleration;l&&(d={x:l.x||0,y:l.y||0,z:l.z||0});l=null;var a=b.accelerationIncludingGravity;a&&(l={x:a.x||0,y:a.y||0,z:a.z||0});a=null;const f=b.rotationRate;f&&(a={alpha:f.alpha||0,beta:f.beta||0,gamma:f.gamma||0});u(this,"devicemotion",{acceleration:d,accelerationIncludingGravity:l,rotationRate:a,interval:b.interval,timeStamp:b.timeStamp},h)}ac(b){const d=
this.f.g;d.style.width=b.styleWidth+"px";d.style.height=b.styleHeight+"px";d.style.marginLeft=b.marginLeft+"px";d.style.marginTop=b.marginTop+"px";this.Za&&(d.style.display="",this.Za=!1)}Mb(b){const d=b.url;b=b.filename;const l=document.createElement("a"),a=document.body;l.textContent=b;l.href=d;l.download=b;a.appendChild(l);l.click();a.removeChild(l)}async Sb(b){var d=b.imageBitmapOpts;b=await self.C3_RasterSvgImageBlob(b.blob,b.imageWidth,b.imageHeight,b.surfaceWidth,b.surfaceHeight);d=d?await createImageBitmap(b,
d):await createImageBitmap(b);return{imageBitmap:d,transferables:[d]}}async Kb(b){return await self.C3_GetSvgImageSize(b.blob)}async Ab(b){await q(b.url)}wa(){var b=[...this.Ca];this.Ca.clear();if(!this.jc)for(const d of b)(b=d.play())&&b.catch(()=>{this.lc.has(d)||this.Ca.add(d)})}Lb(){navigator.splashscreen&&navigator.splashscreen.hide&&navigator.splashscreen.hide()}Fb(b){if(b.show){this.u||(this.u=document.createElement("div"),this.u.id="inspectOutline",document.body.appendChild(this.u));var d=
this.u;d.style.display="";d.style.left=b.left-1+"px";d.style.top=b.top-1+"px";d.style.width=b.width+2+"px";d.style.height=b.height+2+"px";d.textContent=b.name}else this.u&&(this.u.style.display="none")}Tb(){window.C3_RegisterSW&&window.C3_RegisterSW()}Ra(b){window.c3_postToMessagePort&&(b.from="runtime",window.c3_postToMessagePort(b))}yb(b,d){return this.f.jb(this.K,{name:b,params:d})}qa(b){alert(b.message)}cc(b){"entered-fullscreen"===b?(g.X(!0),this.H()):"exited-fullscreen"===b?(g.X(!1),this.H()):
console.warn("Unknown wrapper message: ",b)}})}"use strict";async function Q(g){if(g.hc)throw Error("already initialised");g.hc=!0;var e=g.ca.oa("dispatchworker.js");g.ya=await g.ca.ga(e,g.c,{name:"DispatchWorker"});e=new MessageChannel;g.za=e.port1;g.ya.postMessage({type:"_init","in-port":e.port2},[e.port2]);g.Da=await S(g)}function R(g){return[g.za,g.Da]}
async function S(g){const e=g.$a.length;var c=g.ca.oa("jobworker.js");c=await g.ca.ga(c,g.c,{name:"JobWorker"+e});const h=new MessageChannel,m=new MessageChannel;g.ya.postMessage({type:"_addJobWorker",port:h.port1},[h.port1]);c.postMessage({type:"init",number:e,"dispatch-port":h.port2,"output-port":m.port2},[h.port2,m.port2]);g.$a.push(c);return m.port1}
self.ib=class{constructor(g){this.ca=g;this.c=g.c;this.c="preview"===g.a?this.c+"workers/":this.c+g.da;this.kc=Math.min(navigator.hardwareConcurrency||2,16);this.ya=null;this.$a=[];this.Da=this.za=null}};"use strict";window.C3_IsSupported&&(window.c3_runtimeInterface=new self.j({xc:!1,yc:"workermain.js",F:["scripts/c3runtime.js"],ea:[],Ga:"",uc:"scripts/",Ha:[],cb:"html5"}));"use strict";
{function g(e){e.stopPropagation()}self.j.v(class extends self.ha{constructor(e){super(e,"button")}S(e,c){const h=document.createElement("input");var m=h;c.isCheckbox?(h.type="checkbox",m=document.createElement("label"),m.appendChild(h),m.appendChild(document.createTextNode("")),m.style.fontFamily="sans-serif",m.style.userSelect="none",m.style.webkitUserSelect="none",m.style.display="inline-block",m.style.color="black"):h.type="button";m.style.position="absolute";m.addEventListener("touchstart",g);
m.addEventListener("touchmove",g);m.addEventListener("touchend",g);m.addEventListener("mousedown",g);m.addEventListener("mouseup",g);m.addEventListener("keydown",g);m.addEventListener("keyup",g);h.addEventListener("click",()=>P(this,"click",e,{isChecked:h.checked}));c.id&&(h.id=c.id);this.m(m,c);return m}Ma(e){return"input"===e.tagName.toLowerCase()?e:e.firstChild}ma(e){return this.Ma(e)}m(e,c){const h=this.Ma(e);h.checked=c.isChecked;h.disabled=!c.isEnabled;e.title=c.title;e===h?h.value=c.text:e.lastChild.textContent=
c.text}})}"use strict";function U(g){window.C3_RegisterSW&&window.OfflineClientInfo&&window.OfflineClientInfo.SetMessageCallback(e=>u(g,"sw-message",e.data))}
function V(g){g=g.orientation;if(screen.orientation&&screen.orientation.lock)screen.orientation.lock(g).catch(e=>console.warn("[Construct 3] Failed to lock orientation: ",e));else try{let e=!1;screen.lockOrientation?e=screen.lockOrientation(g):screen.webkitLockOrientation?e=screen.webkitLockOrientation(g):screen.mozLockOrientation?e=screen.mozLockOrientation(g):screen.msLockOrientation&&(e=screen.msLockOrientation(g));e||console.warn("[Construct 3] Failed to lock orientation")}catch(e){console.warn("[Construct 3] Failed to lock orientation: ",
e)}}
self.j.v(class extends self.T{constructor(g){super(g,"browser");this.a="";G(this,[["get-initial-state",e=>{this.a=e.exportType;return{location:location.toString(),isOnline:!!navigator.onLine,referrer:document.referrer,title:document.title,isCookieEnabled:!!navigator.cookieEnabled,screenWidth:screen.width,screenHeight:screen.height,windowOuterWidth:window.outerWidth,windowOuterHeight:window.outerHeight,isScirraArcade:"undefined"!==typeof window.is_scirra_arcade}}],["ready-for-sw-messages",()=>U(this)],
["alert",e=>this.qa(e)],["close",()=>{navigator.app&&navigator.app.exitApp?navigator.app.exitApp():navigator.device&&navigator.device.exitApp?navigator.device.exitApp():window.close()}],["set-focus",e=>this.ua(e)],["vibrate",e=>{navigator.vibrate&&navigator.vibrate(e.pattern)}],["lock-orientation",e=>V(e)],["unlock-orientation",()=>{try{screen.orientation&&screen.orientation.unlock?screen.orientation.unlock():screen.unlockOrientation?screen.unlockOrientation():screen.webkitUnlockOrientation?screen.webkitUnlockOrientation():
screen.mozUnlockOrientation?screen.mozUnlockOrientation():screen.msUnlockOrientation&&screen.msUnlockOrientation()}catch(e){}}],["navigate",e=>{var c=e.type;if("back"===c)navigator.app&&navigator.app.backHistory?navigator.app.backHistory():window.history.back();else if("forward"===c)window.history.forward();else if("reload"===c)location.reload();else if("url"===c){c=e.url;const h=e.target;e=e.exportType;self.cordova&&self.cordova.InAppBrowser?self.cordova.InAppBrowser.open(c,"_system"):"preview"===
e||"windows-webview2"===e?window.open(c,"_blank"):this.Cc||(2===h?window.top.location=c:1===h?window.parent.location=c:window.location=c)}else"new-window"===c&&(c=e.url,e=e.tag,self.cordova&&self.cordova.InAppBrowser?self.cordova.InAppBrowser.open(c,"_system"):window.open(c,e))}],["request-fullscreen",e=>{if("windows-webview2"===this.a||"macos-wkwebview"===this.a)self.j.X(!0),this.f.xa({type:"set-fullscreen",fullscreen:!0});else{const c={navigationUI:"auto"};e=e.navUI;1===e?c.navigationUI="hide":
2===e&&(c.navigationUI="show");e=document.documentElement;e.requestFullscreen?e.requestFullscreen(c):e.mozRequestFullScreen?e.mozRequestFullScreen(c):e.msRequestFullscreen?e.msRequestFullscreen(c):e.webkitRequestFullScreen&&("undefined"!==typeof Element.ALLOW_KEYBOARD_INPUT?e.webkitRequestFullScreen(Element.ALLOW_KEYBOARD_INPUT):e.webkitRequestFullScreen())}}],["exit-fullscreen",()=>{"windows-webview2"===this.a||"macos-wkwebview"===this.a?(self.j.X(!1),this.f.xa({type:"set-fullscreen",fullscreen:!1})):
document.exitFullscreen?document.exitFullscreen():document.mozCancelFullScreen?document.mozCancelFullScreen():document.msExitFullscreen?document.msExitFullscreen():document.webkitCancelFullScreen&&document.webkitCancelFullScreen()}],["set-hash",e=>{location.hash=e.hash}]]);window.addEventListener("online",()=>{u(this,"online-state",{isOnline:!0})});window.addEventListener("offline",()=>{u(this,"online-state",{isOnline:!1})});window.addEventListener("hashchange",()=>{u(this,"hashchange",{location:location.toString()})});
document.addEventListener("backbutton",()=>{u(this,"backbutton")})}qa(g){alert(g.message)}ua(g){g=g.isFocus;if("nwjs"===this.a){const e="nwjs"===this.a?nw.Window.get():null;g?e.focus():e.blur()}else g?window.focus():window.blur()}});"use strict";
{function g(c){c.stopPropagation()}function e(c){13!==c.which&&27!==c.which&&c.stopPropagation()}self.j.v(class extends self.ha{constructor(c){super(c,"text-input");O(this,"scroll-to-bottom",h=>this.Xb(h))}S(c,h){let m;const y=h.type;"textarea"===y?(m=document.createElement("textarea"),m.style.resize="none"):(m=document.createElement("input"),m.type=y);m.style.position="absolute";m.autocomplete="off";m.addEventListener("touchstart",g);m.addEventListener("touchmove",g);m.addEventListener("touchend",
g);m.addEventListener("mousedown",g);m.addEventListener("mouseup",g);m.addEventListener("keydown",e);m.addEventListener("keyup",e);m.addEventListener("click",q=>{q.stopPropagation();P(this,"click",c)});m.addEventListener("dblclick",q=>{q.stopPropagation();P(this,"dblclick",c)});m.addEventListener("input",()=>M(this,"change",c,{text:m.value}));h.id&&(m.id=h.id);this.m(m,h);return m}m(c,h){c.value=h.text;c.placeholder=h.placeholder;c.title=h.title;c.disabled=!h.isEnabled;c.readOnly=h.isReadOnly;c.spellcheck=
h.spellCheck;h=h.maxLength;0>h?c.removeAttribute("maxlength"):c.setAttribute("maxlength",h)}Xb(c){c.scrollTop=c.scrollHeight}})}"use strict";
{function g(e){e.stopPropagation()}self.j.v(class extends self.ha{constructor(e){super(e,"list");O(this,"set-selected-index",(c,h)=>this.Zb(c,h.selectedIndex));O(this,"add-item",(c,h)=>this.zb(c,h));O(this,"remove-item",(c,h)=>this.Ub(c,h));O(this,"set-item",(c,h)=>this.Yb(c,h));O(this,"clear",c=>this.Cb(c));O(this,"load-state",(c,h)=>this.Nb(c,h))}S(e,c){const h=c.isDropdown,m=c.isMultiSelect,y=c.items,q=document.createElement("select");q.style.position="absolute";q.style.userSelect="none";q.style.webkitUserSelect=
"none";q.multiple=m;h||(q.size=2);for(const v of y)q.add(this.la(v));q.addEventListener("touchstart",g);q.addEventListener("touchmove",g);q.addEventListener("touchend",g);q.addEventListener("mousedown",g);q.addEventListener("mouseup",g);q.addEventListener("click",v=>{v.stopPropagation();P(this,"click",e,this.na(q))});q.addEventListener("dblclick",v=>{v.stopPropagation();P(this,"dblclick",e,this.na(q))});q.addEventListener("change",()=>M(this,"change",e,this.na(q)));c.id&&(q.id=c.id);this.m(q,c);return q}la(e){const c=
document.createElement("option");c.text=e;return c}na(e){const c=e.selectedIndex,h=[];for(let m=0,y=e.length;m<y;++m)e.options[m].selected&&h.push(m);return{selectedIndex:c,selectedIndices:h}}m(e,c){e.title=c.title;e.disabled=!c.isEnabled;e.multiple=!!c.isMultiSelect}Zb(e,c){e.selectedIndex=c}zb(e,c){const h=c.index;c=this.la(c.text);0>h?e.add(c):e.add(c,h)}Ub(e,c){e.remove(c.index)}Yb(e,c){e.options[c.index].text=c.text}Cb(e){e.innerHTML=""}Nb(e,c){e.innerHTML="";for(const h of c.items)e.add(this.la(h));
e.selectedIndex=c.selectedIndex;for(const h of c.selectedIndices)if(c=e.options[h])c.selected=!0}})}"use strict";async function W(g,e){e=e.type;let c=!0;0===e?c=await X():1===e&&(c=await Y());u(g,"permission-result",{type:e,result:c})}
async function X(){if(!self.DeviceOrientationEvent||!self.DeviceOrientationEvent.requestPermission)return!0;try{return"granted"===await self.DeviceOrientationEvent.requestPermission()}catch(g){return console.warn("[Touch] Failed to request orientation permission: ",g),!1}}
async function Y(){if(!self.DeviceMotionEvent||!self.DeviceMotionEvent.requestPermission)return!0;try{return"granted"===await self.DeviceMotionEvent.requestPermission()}catch(g){return console.warn("[Touch] Failed to request motion permission: ",g),!1}}self.j.v(class extends self.T{constructor(g){super(g,"touch");B(this,"request-permission",e=>W(this,e))}});
