'use strict';function t(g,f,d,k){g.f.na(g.N,f,d,k,void 0)}function y(g,f,d,k){g.f.j?t(g,f,d,k):g.f.zb()._OnMessageFromDOM({type:"event",component:g.N,handler:f,dispatchOpts:k||null,data:d,responseId:null})}function A(g,f,d){g.f.b(g.N,f,d)}function E(g,f){for(const [d,k]of f)A(g,d,k)}window.I=class{constructor(g,f){this.f=g;this.N=f}Ma(){}};
window.ob=class{constructor(g,f){this.ab=g;this.mc=f;this.G=-1;this.ca=-Infinity;this.rc=()=>{this.G=-1;this.ca=Date.now();this.O=!0;this.ab();this.O=!1};this.bb=this.O=!1}};"use strict";function H(g,f){const d=f.elementId,k=g.V(d,f);g.h.set(d,k);k.style.boxSizing="border-box";f.isVisible||(k.style.display="none");f=g.qa(k);f.addEventListener("focus",()=>{M(g,"elem-focused",d)});f.addEventListener("blur",()=>{M(g,"elem-blurred",d)});g.$&&document.body.appendChild(k)}
function N(g,f,d){A(g,f,k=>{const l=g.h.get(k.elementId);return d(l,k)})}function M(g,f,d,k){k||(k={});k.elementId=d;t(g,f,k)}function P(g,f,d,k){k||(k={});k.elementId=d;y(g,f,k)}
window.la=class extends self.I{constructor(g,f){super(g,f);this.h=new Map;this.$=!0;E(this,[["create",d=>H(this,d)],["destroy",d=>{{d=d.elementId;const k=this.h.get(d);this.$&&k.parentElement.removeChild(k);this.h.delete(d)}}],["set-visible",d=>{this.$&&(this.h.get(d.elementId).style.display=d.isVisible?"":"none")}],["update-position",d=>{if(this.$){var k=this.h.get(d.elementId);k.style.left=d.left+"px";k.style.top=d.top+"px";k.style.width=d.width+"px";k.style.height=d.height+"px";d=d.fontSize;null!==
d&&(k.style.fontSize=d+"em")}}],["update-state",d=>{{const k=this.h.get(d.elementId);this.o(k,d)}}],["focus",d=>this.za(d)],["set-css-style",d=>{this.h.get(d.elementId).style[d.prop]=d.val}],["set-attribute",d=>{this.h.get(d.elementId).setAttribute(d.name,d.val)}],["remove-attribute",d=>{this.h.get(d.elementId).removeAttribute(d.name)}]]);N(this,"get-element",d=>d)}V(){throw Error("required override");}o(){throw Error("required override");}qa(g){return g}za(g){const f=this.qa(this.h.get(g.elementId));
g.focus?f.focus():f.blur()}};"use strict";
{const g=/(iphone|ipod|ipad|macos|macintosh|mac os x)/i.test(navigator.userAgent);let f=0;function d(c){const a=document.createElement("script");a.async=!1;a.type="module";return c.wc?new Promise(e=>{const h="c3_resolve_"+f;++f;self[h]=e;a.textContent=c.zc+`\n\nself["${h}"]();`;document.head.appendChild(a)}):new Promise((e,h)=>{a.onload=e;a.onerror=h;a.src=c;document.head.appendChild(a)})}let k=!1,l=!1;function w(){if(!k){try{new Worker("blob://",{get type(){l=!0}})}catch(c){}k=!0}return l}let p=
new Audio;const x={"audio/webm; codecs=opus":!!p.canPlayType("audio/webm; codecs=opus"),"audio/ogg; codecs=opus":!!p.canPlayType("audio/ogg; codecs=opus"),"audio/webm; codecs=vorbis":!!p.canPlayType("audio/webm; codecs=vorbis"),"audio/ogg; codecs=vorbis":!!p.canPlayType("audio/ogg; codecs=vorbis"),"audio/mp4":!!p.canPlayType("audio/mp4"),"audio/mpeg":!!p.canPlayType("audio/mpeg")};p=null;async function B(c){c=await J(c);return(new TextDecoder("utf-8")).decode(c)}function J(c){return new Promise((a,
e)=>{const h=new FileReader;h.onload=m=>a(m.target.result);h.onerror=m=>e(m);h.readAsArrayBuffer(c)})}const F=[];let z=0;window.RealFile=window.File;const C=[],G=new Map,u=new Map;let K=0;const D=[];self.runOnStartup=function(c){if("function"!==typeof c)throw Error("runOnStartup called without a function");D.push(c)};const O=new Set(["cordova","playable-ad","instant-games"]);let b=!1;window.i=class c{constructor(a){this.j=a.Bc;this.R=null;this.c="";this.ha=a.yc;this.U={};this.Fa=this.gb=null;this.aa=
[];this.P=this.g=this.Ia=null;this.D=-1;this.qc=()=>this.Vb();this.fb=[];this.a=a.hb;this.ba="file"===location.protocol.substr(0,4);!this.j||"undefined"!==typeof OffscreenCanvas&&navigator.userActivation&&w()||(this.j=!1);if("playable-ad"===this.a||"instant-games"===this.a)this.j=!1;if("cordova"===this.a&&this.j)if(/android/i.test(navigator.userAgent)){const e=/Chrome\/(\d+)/i.exec(navigator.userAgent);e&&90<=parseInt(e[1],10)||(this.j=!1)}else this.j=!1;this.da=this.l=null;"html5"!==this.a&&"playable-ad"!==
this.a||!this.ba||alert("Exported games won't work until you upload them. (When running on the file: protocol, browsers block many features from working for security reasons.)");"html5"!==this.a||window.isSecureContext||console.warn("[Construct 3] Warning: the browser indicates this is not a secure context. Some features may be unavailable. Use secure (HTTPS) hosting to ensure all features are available.");this.b("runtime","cordova-fetch-local-file",e=>this.Hb(e));this.b("runtime","create-job-worker",
()=>this.Ib());"cordova"===this.a?document.addEventListener("deviceready",()=>this.Ra(a)):this.Ra(a)}lb(){return g&&"cordova"===this.a}ma(){const a=navigator.userAgent;return g&&O.has(this.a)||navigator.standalone||/crios\/|fxios\/|edgios\//i.test(a)}async Ra(a){"macos-wkwebview"===this.a&&this.Ca({type:"ready"});if("playable-ad"===this.a){this.l=self.c3_base64files;this.da={};await this.ub();for(let h=0,m=a.H.length;h<m;++h){var e=a.H[h].toLowerCase();this.da.hasOwnProperty(e)?a.H[h]={wc:!0,zc:this.da[e]}:
this.l.hasOwnProperty(e)&&(a.H[h]=URL.createObjectURL(this.l[e]))}}a.sc?this.c=a.sc:(e=location.origin,this.c=("null"===e?"file:///":e)+location.pathname,e=this.c.lastIndexOf("/"),-1!==e&&(this.c=this.c.substr(0,e+1)));a.Dc&&(this.U=a.Dc);e=new MessageChannel;this.R=e.port1;this.R.onmessage=h=>this._OnMessageFromRuntime(h.data);window.c3_addPortMessageHandler&&window.c3_addPortMessageHandler(h=>this.Sb(h));this.P=new self.mb(this);await Q(this.P);"object"===typeof window.StatusBar&&window.StatusBar.hide();
"object"===typeof window.AndroidFullScreen&&window.AndroidFullScreen.immersiveMode();this.j?await this.Bb(a,e.port2):await this.Ab(a,e.port2)}sa(a){a=this.U.hasOwnProperty(a)?this.U[a]:a.endsWith("/workermain.js")&&this.U.hasOwnProperty("workermain.js")?this.U["workermain.js"]:"playable-ad"===this.a&&this.l.hasOwnProperty(a.toLowerCase())?this.l[a.toLowerCase()]:a;a instanceof Blob&&(a=URL.createObjectURL(a));return a}async ka(a,e,h){if(a.startsWith("blob:"))return new Worker(a,h);if("cordova"===
this.a&&this.ba)return a=await this.ja(h.vc?a:this.ha+a),new Worker(URL.createObjectURL(new Blob([a],{type:"application/javascript"})),h);a=new URL(a,e);if(location.origin!==a.origin){a=await fetch(a);if(!a.ok)throw Error("failed to fetch worker script");a=await a.blob();return new Worker(URL.createObjectURL(a),h)}return new Worker(a,h)}u(){return Math.max(window.innerWidth,1)}s(){return Math.max(window.innerHeight,1)}Pa(a){var e=this.P;return{baseUrl:this.c,windowInnerWidth:this.u(),windowInnerHeight:this.s(),
devicePixelRatio:window.devicePixelRatio,isFullscreen:c.J(),projectData:a.Jc,previewImageBlobs:window.cr_previewImageBlobs||this.l,previewProjectFileBlobs:window.cr_previewProjectFileBlobs,previewProjectFileSWUrls:window.cr_previewProjectFiles,swClientId:window.Hc||"",exportType:a.hb,isDebug:-1<self.location.search.indexOf("debug"),ife:!!self.Ic,jobScheduler:{inputPort:e.Ea,outputPort:e.Ha,maxNumWorkers:e.oc},supportedAudioFormats:x,opusWasmScriptUrl:window.cr_opusWasmScriptUrl||this.ha+"opus.wasm.js",
opusWasmBinaryUrl:window.cr_opusWasmBinaryUrl||this.ha+"opus.wasm.wasm",isFileProtocol:this.ba,isiOSCordova:this.lb(),isiOSWebView:this.ma(),isFBInstantAvailable:"undefined"!==typeof self.FBInstant}}async Bb(a,e){var h=this.sa(a.Cc);this.gb=await this.ka(h,this.c,{type:"module",name:"Runtime",vc:!0});this.g=document.createElement("canvas");this.g.style.display="none";h=this.g.transferControlToOffscreen();document.body.appendChild(this.g);window.c3canvas=this.g;let m=a.La||[],q=a.H;m=await Promise.all(m.map(n=>
this.B(n)));q=await Promise.all(q.map(n=>this.B(n)));if("cordova"===this.a)for(let n=0,r=a.ia.length;n<r;++n){const v=a.ia[n],L=v[0];if(L===a.Ka||"scriptsInEvents.js"===L||L.endsWith("/scriptsInEvents.js"))v[1]=await this.B(L)}this.gb.postMessage(Object.assign(this.Pa(a),{type:"init-runtime",isInWorker:!0,messagePort:e,canvas:h,workerDependencyScripts:m,engineScripts:q,projectScripts:a.ia,mainProjectScript:a.Ka,projectScriptsStatus:self.C3_ProjectScriptsStatus}),[e,h,...R(this.P)]);this.aa=C.map(n=>
new n(this));this.Oa();self.c3_callFunction=(n,r)=>this.Ia.Cb(n,r);"preview"===this.a&&(self.goToLastErrorScript=()=>this.na("runtime","go-to-last-error-script"))}async Ab(a,e){this.g=document.createElement("canvas");this.g.style.display="none";document.body.appendChild(this.g);window.c3canvas=this.g;this.aa=C.map(n=>new n(this));this.Oa();var h=a.H.map(n=>"string"===typeof n?(new URL(n,this.c)).toString():n);Array.isArray(a.La)&&h.unshift(...a.La);h=await Promise.all(h.map(n=>this.B(n)));await Promise.all(h.map(n=>
d(n)));h=self.C3_ProjectScriptsStatus;const m=a.Ka,q=a.ia;for(let [n,r]of q)if(r||(r=n),n===m)try{r=await this.B(r),await d(r),"preview"!==this.a||h[n]||this.Xa(n,"main script did not run to completion")}catch(v){this.Xa(n,v)}else if("scriptsInEvents.js"===n||n.endsWith("/scriptsInEvents.js"))r=await this.B(r),await d(r);"preview"===this.a&&"object"!==typeof self.Ec.Fc?(this.Y(),console.error("[C3 runtime] Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax."),
alert("Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax.")):(a=Object.assign(this.Pa(a),{isInWorker:!1,messagePort:e,canvas:this.g,runOnStartupFunctions:D}),this.Ta(),this.Fa=self.C3_CreateRuntime(a),await self.C3_InitRuntime(this.Fa,a))}Xa(a,e){this.Y();console.error(`[Preview] Failed to load project main script (${a}): `,e);alert(`Failed to load project main script (${a}). Check all your JavaScript code has valid syntax. Press F12 and check the console for error details.`)}Ta(){this.Y()}Y(){const a=
window.tc;a&&(a.parentElement.removeChild(a),window.tc=null)}async Ib(){const a=await S(this.P);return{outputPort:a,transferables:[a]}}zb(){if(this.j)throw Error("not available in worker mode");return this.Fa}na(a,e,h,m,q){this.R.postMessage({type:"event",component:a,handler:e,dispatchOpts:m||null,data:h,responseId:null},q)}nb(a,e){const h=K++,m=new Promise((q,n)=>{u.set(h,{resolve:q,reject:n})});this.R.postMessage({type:"event",component:a,handler:"js-invoke-function",dispatchOpts:null,data:e,responseId:h},
void 0);return m}["_OnMessageFromRuntime"](a){const e=a.type;if("event"===e)return this.Nb(a);if("result"===e)this.Zb(a);else if("runtime-ready"===e)this.$b();else if("alert-error"===e)this.Y(),alert(a.message);else if("creating-runtime"===e)this.Ta();else throw Error(`unknown message '${e}'`);}Nb(a){const e=a.component,h=a.handler,m=a.data,q=a.responseId;if(a=G.get(e))if(a=a.get(h)){var n=null;try{n=a(m)}catch(r){console.error(`Exception in '${e}' handler '${h}':`,r);null!==q&&this.X(q,!1,""+r);
return}if(null===q)return n;n&&n.then?n.then(r=>this.X(q,!0,r)).catch(r=>{console.error(`Rejection from '${e}' handler '${h}':`,r);this.X(q,!1,""+r)}):this.X(q,!0,n)}else console.warn(`[DOM] No handler '${h}' for component '${e}'`);else console.warn(`[DOM] No event handlers for component '${e}'`)}X(a,e,h){let m;h&&h.transferables&&(m=h.transferables);this.R.postMessage({type:"result",responseId:a,isOk:e,result:h},m)}Zb(a){const e=a.responseId,h=a.isOk;a=a.result;const m=u.get(e);h?m.resolve(a):m.reject(a);
u.delete(e)}b(a,e,h){let m=G.get(a);m||(m=new Map,G.set(a,m));if(m.has(e))throw Error(`[DOM] Component '${a}' already has handler '${e}'`);m.set(e,h)}static m(a){if(C.includes(a))throw Error("DOM handler already added");C.push(a)}Oa(){for(const a of this.aa)if("runtime"===a.N){this.Ia=a;return}throw Error("cannot find runtime DOM handler");}Sb(a){this.na("debugger","message",a)}$b(){for(const a of this.aa)a.Ma()}static J(){return!!(document.fullscreenElement||document.webkitFullscreenElement||document.mozFullScreenElement||
b)}static Z(a){b=!!a}Ya(){-1===this.D&&this.fb.length&&(this.D=requestAnimationFrame(this.qc))}sb(){-1!==this.D&&(cancelAnimationFrame(this.D),this.D=-1)}Vb(){this.D=-1;for(const a of this.fb)a();this.Ya()}Ba(){this.Ia.Ba()}jb(a){return/^(?:[a-z\-]+:)?\/\//.test(a)||"data:"===a.substr(0,5)||"blob:"===a.substr(0,5)}kb(a){return!this.jb(a)}async B(a){return"cordova"===this.a&&(a.startsWith("file:")||this.ba&&this.kb(a))?(a.startsWith(this.c)&&(a=a.substr(this.c.length)),a=await this.ja(a),URL.createObjectURL(new Blob([a],
{type:"application/javascript"}))):a}async Hb(a){const e=a.filename;switch(a.as){case "text":return await this.ib(e);case "buffer":return await this.ja(e);default:throw Error("unsupported type");}}Na(a){const e=window.cordova.file.applicationDirectory+"www/"+a.toLowerCase();return new Promise((h,m)=>{window.resolveLocalFileSystemURL(e,q=>{q.file(h,m)},m)})}async ib(a){a=await this.Na(a);return await B(a)}oa(){if(F.length&&!(8<=z)){z++;var a=F.shift();this.vb(a.filename,a.Ac,a.uc)}}ja(a){return new Promise((e,
h)=>{F.push({filename:a,Ac:m=>{z--;this.oa();e(m)},uc:m=>{z--;this.oa();h(m)}});this.oa()})}async vb(a,e,h){try{const m=await this.Na(a),q=await J(m);e(q)}catch(m){h(m)}}Ca(a){if("windows-webview2"===this.a)window.chrome.webview.postMessage(JSON.stringify(a));else if("macos-wkwebview"===this.a)window.webkit.messageHandlers.C3Wrapper.postMessage(JSON.stringify(a));else throw Error("cannot send wrapper message");}async ub(){const a=[];for(const [e,h]of Object.entries(this.l))a.push(this.tb(e,h));await Promise.all(a)}async tb(a,
e){if("object"===typeof e)this.l[a]=new Blob([e.str],{type:e.type}),this.da[a]=e.str;else{let h=await this.yb(e);h||(h=this.wb(e));this.l[a]=h}}async yb(a){try{return await (await fetch(a)).blob()}catch(e){return console.warn("Failed to fetch a data: URI. Falling back to a slower workaround. This is probably because the Content Security Policy unnecessarily blocked it. Allow data: URIs in your CSP to avoid this.",e),null}}wb(a){a=this.ic(a);return this.rb(a.data,a.xc)}ic(a){var e=a.indexOf(",");if(0>
e)throw new URIError("expected comma in data: uri");var h=a.substring(e+1);e=a.substring(5,e).split(";");a=e[0]||"";const m=e[2];h="base64"===e[1]||"base64"===m?atob(h):decodeURIComponent(h);return{xc:a,data:h}}rb(a,e){var h=a.length;let m=h>>2,q=new Uint8Array(h),n=new Uint32Array(q.buffer,0,m),r,v;for(v=r=0;r<m;++r)n[r]=a.charCodeAt(v++)|a.charCodeAt(v++)<<8|a.charCodeAt(v++)<<16|a.charCodeAt(v++)<<24;for(h&=3;h--;)q[v]=a.charCodeAt(v),++v;return new Blob([q],{type:e})}}}"use strict";
{const g=self.i;function f(b){return b.sourceCapabilities&&b.sourceCapabilities.firesTouchEvents||b.originalEvent&&b.originalEvent.sourceCapabilities&&b.originalEvent.sourceCapabilities.firesTouchEvents}const d=new Map([["OSLeft","MetaLeft"],["OSRight","MetaRight"]]),k={dispatchRuntimeEvent:!0,dispatchUserScriptEvent:!0},l={dispatchUserScriptEvent:!0},w={dispatchRuntimeEvent:!0};function p(b){return new Promise((c,a)=>{const e=document.createElement("link");e.onload=()=>c(e);e.onerror=h=>a(h);e.rel=
"stylesheet";e.href=b;document.head.appendChild(e)})}function x(b){return new Promise((c,a)=>{const e=new Image;e.onload=()=>c(e);e.onerror=h=>a(h);e.src=b})}async function B(b){b=URL.createObjectURL(b);try{return await x(b)}finally{URL.revokeObjectURL(b)}}function J(b){return new Promise((c,a)=>{let e=new FileReader;e.onload=h=>c(h.target.result);e.onerror=h=>a(h);e.readAsText(b)})}async function F(b,c,a){if(!/firefox/i.test(navigator.userAgent))return await B(b);var e=await J(b);e=(new DOMParser).parseFromString(e,
"image/svg+xml");const h=e.documentElement;if(h.hasAttribute("width")&&h.hasAttribute("height")){const m=h.getAttribute("width"),q=h.getAttribute("height");if(!m.includes("%")&&!q.includes("%"))return await B(b)}h.setAttribute("width",c+"px");h.setAttribute("height",a+"px");e=(new XMLSerializer).serializeToString(e);b=new Blob([e],{type:"image/svg+xml"});return await B(b)}function z(b){do{if(b.parentNode&&b.hasAttribute("contenteditable"))return!0;b=b.parentNode}while(b);return!1}const C=new Set(["input",
"textarea","datalist","select"]),G=new Set(["canvas","body","html"]);function u(b){G.has(b.target.tagName.toLowerCase())&&b.preventDefault()}function K(b){(b.metaKey||b.ctrlKey)&&b.preventDefault()}self.C3_GetSvgImageSize=async function(b){b=await B(b);if(0<b.width&&0<b.height)return[b.width,b.height];{b.style.position="absolute";b.style.left="0px";b.style.top="0px";b.style.visibility="hidden";document.body.appendChild(b);const c=b.getBoundingClientRect();document.body.removeChild(b);return[c.width,
c.height]}};self.C3_RasterSvgImageBlob=async function(b,c,a,e,h){b=await F(b,c,a);const m=document.createElement("canvas");m.width=e;m.height=h;m.getContext("2d").drawImage(b,0,0,c,a);return m};let D=!1;document.addEventListener("pause",()=>D=!0);document.addEventListener("resume",()=>D=!1);function O(){try{return window.parent&&window.parent.document.hasFocus()}catch(b){return!1}}g.m(class extends self.I{constructor(b){super(b,"runtime");this.cb=!0;this.F=-1;this.Ja="any";this.Za=this.$a=!1;this.C=
this.T=this.v=null;this.fa=this.ea=0;b.b("canvas","update-size",e=>this.ec(e));b.b("runtime","invoke-download",e=>this.Qb(e));b.b("runtime","raster-svg-image",e=>this.Wb(e));b.b("runtime","get-svg-image-size",e=>this.Ob(e));b.b("runtime","set-target-orientation",e=>this.dc(e));b.b("runtime","register-sw",()=>this.Xb());b.b("runtime","post-to-debugger",e=>this.Va(e));b.b("runtime","go-to-script",e=>this.Va(e));b.b("runtime","before-start-ticking",()=>this.Fb());b.b("runtime","debug-highlight",e=>this.Jb(e));
b.b("runtime","enable-device-orientation",()=>this.qb());b.b("runtime","enable-device-motion",()=>this.pb());b.b("runtime","add-stylesheet",e=>this.Eb(e));b.b("runtime","alert",e=>this.ua(e));b.b("runtime","hide-cordova-splash",()=>this.Pb());const c=new Set(["input","textarea","datalist"]);window.addEventListener("contextmenu",e=>{const h=e.target;c.has(h.tagName.toLowerCase())||z(h)||e.preventDefault()});const a=b.g;window.addEventListener("selectstart",u);window.addEventListener("gesturehold",
u);a.addEventListener("selectstart",u);a.addEventListener("gesturehold",u);window.addEventListener("touchstart",u,{passive:!1});"undefined"!==typeof PointerEvent?(window.addEventListener("pointerdown",u,{passive:!1}),a.addEventListener("pointerdown",u)):a.addEventListener("touchstart",u);this.S=0;window.addEventListener("mousedown",e=>{1===e.button&&e.preventDefault()});window.addEventListener("mousewheel",K,{passive:!1});window.addEventListener("wheel",K,{passive:!1});window.addEventListener("resize",
()=>this.fc());window.addEventListener("fullscreenchange",()=>this.K());window.addEventListener("webkitfullscreenchange",()=>this.K());window.addEventListener("mozfullscreenchange",()=>this.K());window.addEventListener("fullscreenerror",e=>this.va(e));window.addEventListener("webkitfullscreenerror",e=>this.va(e));window.addEventListener("mozfullscreenerror",e=>this.va(e));b.ma()&&window.addEventListener("focusout",()=>{{const m=document.activeElement;if(m){var e=m.tagName.toLowerCase();var h=new Set("email number password search tel text url".split(" "));
e="textarea"===e?!0:"input"===e?h.has(m.type.toLowerCase()||"text"):z(m)}else e=!1}e||(document.scrollingElement.scrollTop=0)});self.C3WrapperOnMessage=e=>this.hc(e);this.Ga=new Set;this.pc=new WeakSet;this.nc=!1}Fb(){"cordova"===this.f.a?(document.addEventListener("pause",()=>this.Aa(!0)),document.addEventListener("resume",()=>this.Aa(!1))):document.addEventListener("visibilitychange",()=>this.Aa(document.hidden));return{isSuspended:!(!document.hidden&&!D)}}Ma(){window.addEventListener("focus",()=>
this.M("window-focus"));window.addEventListener("blur",()=>{this.M("window-blur",{parentHasFocus:O()});this.S=0});window.addEventListener("focusin",c=>{c=c.target;(C.has(c.tagName.toLowerCase())||z(c))&&this.M("keyboard-blur")});window.addEventListener("keydown",c=>this.Ua("keydown",c));window.addEventListener("keyup",c=>this.Ua("keyup",c));window.addEventListener("dblclick",c=>this.xa("dblclick",c,k));window.addEventListener("wheel",c=>this.Tb(c));"undefined"!==typeof PointerEvent?(window.addEventListener("pointerdown",
c=>{this.ta(c);this.L("pointerdown",c)}),this.f.j&&"undefined"!==typeof window.onpointerrawupdate&&self===self.top?(this.T=new self.ob(()=>this.xb(),5),this.T.bb=!0,window.addEventListener("pointerrawupdate",c=>this.Ub(c))):window.addEventListener("pointermove",c=>this.L("pointermove",c)),window.addEventListener("pointerup",c=>this.L("pointerup",c)),window.addEventListener("pointercancel",c=>this.L("pointercancel",c))):(window.addEventListener("mousedown",c=>{this.ta(c);this.ya("pointerdown",c)}),
window.addEventListener("mousemove",c=>this.ya("pointermove",c)),window.addEventListener("mouseup",c=>this.ya("pointerup",c)),window.addEventListener("touchstart",c=>{this.ta(c);this.W("pointerdown",c)}),window.addEventListener("touchmove",c=>this.W("pointermove",c)),window.addEventListener("touchend",c=>this.W("pointerup",c)),window.addEventListener("touchcancel",c=>this.W("pointercancel",c)));const b=()=>this.Ba();window.addEventListener("pointerup",b,!0);window.addEventListener("touchend",b,!0);
window.addEventListener("click",b,!0);window.addEventListener("keydown",b,!0);window.addEventListener("gamepadconnected",b,!0)}M(b,c){t(this,b,c||null,w)}u(){return this.f.u()}s(){return this.f.s()}fc(){const b=this.u(),c=this.s();this.M("window-resize",{innerWidth:b,innerHeight:c,devicePixelRatio:window.devicePixelRatio,isFullscreen:g.J()});this.f.ma()&&(-1!==this.F&&clearTimeout(this.F),this.Wa(b,c,0))}jc(b,c,a){-1!==this.F&&clearTimeout(this.F);this.F=setTimeout(()=>this.Wa(b,c,a),48)}Wa(b,c,a){const e=
this.u(),h=this.s();this.F=-1;e!=b||h!=c?this.M("window-resize",{innerWidth:e,innerHeight:h,devicePixelRatio:window.devicePixelRatio,isFullscreen:g.J()}):10>a&&this.jc(e,h,a+1)}dc(b){this.Ja=b.targetOrientation}kc(){const b=this.Ja;if(screen.orientation&&screen.orientation.lock)screen.orientation.lock(b).catch(c=>console.warn("[Construct 3] Failed to lock orientation: ",c));else try{let c=!1;screen.lockOrientation?c=screen.lockOrientation(b):screen.webkitLockOrientation?c=screen.webkitLockOrientation(b):
screen.mozLockOrientation?c=screen.mozLockOrientation(b):screen.msLockOrientation&&(c=screen.msLockOrientation(b));c||console.warn("[Construct 3] Failed to lock orientation")}catch(c){console.warn("[Construct 3] Failed to lock orientation: ",c)}}K(){const b=g.J();b&&"any"!==this.Ja&&this.kc();t(this,"fullscreenchange",{isFullscreen:b,innerWidth:this.u(),innerHeight:this.s()})}va(b){console.warn("[Construct 3] Fullscreen request failed: ",b);t(this,"fullscreenerror",{isFullscreen:g.J(),innerWidth:this.u(),
innerHeight:this.s()})}Aa(b){b?this.f.sb():this.f.Ya();t(this,"visibilitychange",{hidden:b})}Ua(b,c){"Backspace"===c.key&&u(c);const a=d.get(c.code)||c.code;y(this,b,{code:a,key:c.key,which:c.which,repeat:c.repeat,altKey:c.altKey,ctrlKey:c.ctrlKey,metaKey:c.metaKey,shiftKey:c.shiftKey,timeStamp:c.timeStamp},k)}Tb(b){t(this,"wheel",{clientX:b.clientX,clientY:b.clientY,pageX:b.pageX,pageY:b.pageY,deltaX:b.deltaX,deltaY:b.deltaY,deltaZ:b.deltaZ,deltaMode:b.deltaMode,timeStamp:b.timeStamp},k)}xa(b,c,
a){f(c)||y(this,b,{button:c.button,buttons:c.buttons,clientX:c.clientX,clientY:c.clientY,pageX:c.pageX,pageY:c.pageY,movementX:c.movementX||0,movementY:c.movementY||0,timeStamp:c.timeStamp},a)}ya(b,c){if(!f(c)){var a=this.S;"pointerdown"===b&&0!==a?b="pointermove":"pointerup"===b&&0!==c.buttons&&(b="pointermove");y(this,b,{pointerId:1,pointerType:"mouse",button:c.button,buttons:c.buttons,lastButtons:a,clientX:c.clientX,clientY:c.clientY,pageX:c.pageX,pageY:c.pageY,movementX:c.movementX||0,movementY:c.movementY||
0,width:0,height:0,pressure:0,tangentialPressure:0,tiltX:0,tiltY:0,twist:0,timeStamp:c.timeStamp},k);this.S=c.buttons;this.xa(c.type,c,l)}}L(b,c){if(this.T&&"pointermove"!==b){var a=this.T;a.O||(-1!==a.G&&(self.clearTimeout(a.G),a.G=-1),a.ca=Date.now())}a=0;"mouse"===c.pointerType&&(a=this.S);y(this,b,{pointerId:c.pointerId,pointerType:c.pointerType,button:c.button,buttons:c.buttons,lastButtons:a,clientX:c.clientX,clientY:c.clientY,pageX:c.pageX,pageY:c.pageY,movementX:(c.movementX||0)+this.ea,movementY:(c.movementY||
0)+this.fa,width:c.width||0,height:c.height||0,pressure:c.pressure||0,tangentialPressure:c.tangentialPressure||0,tiltX:c.tiltX||0,tiltY:c.tiltY||0,twist:c.twist||0,timeStamp:c.timeStamp},k);this.fa=this.ea=0;"mouse"===c.pointerType&&(a="mousemove","pointerdown"===b?a="mousedown":"pointerup"===b&&(a="mouseup"),this.xa(a,c,l),this.S=c.buttons)}Ub(b){this.C&&(this.ea+=this.C.movementX||0,this.fa+=this.C.movementY||0);this.C=b;b=this.T;if(-1===b.G){var c=Date.now(),a=c-b.ca,e=b.mc;a>=e&&b.bb?(b.ca=c,
b.O=!0,b.ab(),b.O=!1):b.G=self.setTimeout(b.rc,Math.max(e-a,4))}}xb(){this.L("pointermove",this.C);this.C=null}W(b,c){for(let a=0,e=c.changedTouches.length;a<e;++a){const h=c.changedTouches[a];y(this,b,{pointerId:h.identifier,pointerType:"touch",button:0,buttons:0,lastButtons:0,clientX:h.clientX,clientY:h.clientY,pageX:h.pageX,pageY:h.pageY,movementX:c.movementX||0,movementY:c.movementY||0,width:2*(h.radiusX||h.webkitRadiusX||0),height:2*(h.radiusY||h.webkitRadiusY||0),pressure:h.force||h.webkitForce||
0,tangentialPressure:0,tiltX:0,tiltY:0,twist:h.rotationAngle||0,timeStamp:c.timeStamp},k)}}ta(b){window!==window.top&&window.focus();this.Sa(b.target)&&document.activeElement&&!this.Sa(document.activeElement)&&document.activeElement.blur()}Sa(b){return!b||b===document||b===window||b===document.body||"canvas"===b.tagName.toLowerCase()}qb(){this.$a||(this.$a=!0,window.addEventListener("deviceorientation",b=>this.Lb(b)),window.addEventListener("deviceorientationabsolute",b=>this.Mb(b)))}pb(){this.Za||
(this.Za=!0,window.addEventListener("devicemotion",b=>this.Kb(b)))}Lb(b){t(this,"deviceorientation",{absolute:!!b.absolute,alpha:b.alpha||0,beta:b.beta||0,gamma:b.gamma||0,timeStamp:b.timeStamp,webkitCompassHeading:b.webkitCompassHeading,webkitCompassAccuracy:b.webkitCompassAccuracy},k)}Mb(b){t(this,"deviceorientationabsolute",{absolute:!!b.absolute,alpha:b.alpha||0,beta:b.beta||0,gamma:b.gamma||0,timeStamp:b.timeStamp},k)}Kb(b){let c=null;var a=b.acceleration;a&&(c={x:a.x||0,y:a.y||0,z:a.z||0});
a=null;var e=b.accelerationIncludingGravity;e&&(a={x:e.x||0,y:e.y||0,z:e.z||0});e=null;const h=b.rotationRate;h&&(e={alpha:h.alpha||0,beta:h.beta||0,gamma:h.gamma||0});t(this,"devicemotion",{acceleration:c,accelerationIncludingGravity:a,rotationRate:e,interval:b.interval,timeStamp:b.timeStamp},k)}ec(b){const c=this.f.g;c.style.width=b.styleWidth+"px";c.style.height=b.styleHeight+"px";c.style.marginLeft=b.marginLeft+"px";c.style.marginTop=b.marginTop+"px";this.cb&&(c.style.display="",this.cb=!1)}Qb(b){const c=
b.url;b=b.filename;const a=document.createElement("a"),e=document.body;a.textContent=b;a.href=c;a.download=b;e.appendChild(a);a.click();e.removeChild(a)}async Wb(b){var c=b.imageBitmapOpts;b=await self.C3_RasterSvgImageBlob(b.blob,b.imageWidth,b.imageHeight,b.surfaceWidth,b.surfaceHeight);c=c?await createImageBitmap(b,c):await createImageBitmap(b);return{imageBitmap:c,transferables:[c]}}async Ob(b){return await self.C3_GetSvgImageSize(b.blob)}async Eb(b){await p(b.url)}Ba(){var b=[...this.Ga];this.Ga.clear();
if(!this.nc)for(const c of b)(b=c.play())&&b.catch(()=>{this.pc.has(c)||this.Ga.add(c)})}Pb(){navigator.splashscreen&&navigator.splashscreen.hide&&navigator.splashscreen.hide()}Jb(b){if(b.show){this.v||(this.v=document.createElement("div"),this.v.id="inspectOutline",document.body.appendChild(this.v));var c=this.v;c.style.display="";c.style.left=b.left-1+"px";c.style.top=b.top-1+"px";c.style.width=b.width+2+"px";c.style.height=b.height+2+"px";c.textContent=b.name}else this.v&&(this.v.style.display=
"none")}Xb(){window.C3_RegisterSW&&window.C3_RegisterSW()}Va(b){window.c3_postToMessagePort&&(b.from="runtime",window.c3_postToMessagePort(b))}Cb(b,c){return this.f.nb(this.N,{name:b,params:c})}ua(b){alert(b.message)}hc(b){"entered-fullscreen"===b?(g.Z(!0),this.K()):"exited-fullscreen"===b?(g.Z(!1),this.K()):console.warn("Unknown wrapper message: ",b)}})}"use strict";
async function Q(g){if(g.lc)throw Error("already initialised");g.lc=!0;var f=g.ga.sa("dispatchworker.js");g.Da=await g.ga.ka(f,g.c,{name:"DispatchWorker"});f=new MessageChannel;g.Ea=f.port1;g.Da.postMessage({type:"_init","in-port":f.port2},[f.port2]);g.Ha=await S(g)}function R(g){return[g.Ea,g.Ha]}
async function S(g){const f=g.eb.length;var d=g.ga.sa("jobworker.js");d=await g.ga.ka(d,g.c,{name:"JobWorker"+f});const k=new MessageChannel,l=new MessageChannel;g.Da.postMessage({type:"_addJobWorker",port:k.port1},[k.port1]);d.postMessage({type:"init",number:f,"dispatch-port":k.port2,"output-port":l.port2},[k.port2,l.port2]);g.eb.push(d);return l.port1}
self.mb=class{constructor(g){this.ga=g;this.c=g.c;this.c="preview"===g.a?this.c+"workers/":this.c+g.ha;this.oc=Math.min(navigator.hardwareConcurrency||2,16);this.Da=null;this.eb=[];this.Ha=this.Ea=null}};"use strict";window.C3_IsSupported&&(window.c3_runtimeInterface=new self.i({Bc:!1,Cc:"workermain.js",H:["scripts/c3runtime.js"],ia:[],Ka:"",yc:"scripts/",La:[],hb:"html5"}));"use strict";
{function g(f){f.stopPropagation()}self.i.m(class extends self.la{constructor(f){super(f,"button")}V(f,d){const k=document.createElement("input");var l=k;d.isCheckbox?(k.type="checkbox",l=document.createElement("label"),l.appendChild(k),l.appendChild(document.createTextNode("")),l.style.fontFamily="sans-serif",l.style.userSelect="none",l.style.webkitUserSelect="none",l.style.display="inline-block",l.style.color="black"):k.type="button";l.style.position="absolute";l.addEventListener("touchstart",g);
l.addEventListener("touchmove",g);l.addEventListener("touchend",g);l.addEventListener("mousedown",g);l.addEventListener("mouseup",g);l.addEventListener("keydown",g);l.addEventListener("keyup",g);k.addEventListener("click",()=>P(this,"click",f,{isChecked:k.checked}));d.id&&(k.id=d.id);this.o(l,d);return l}Qa(f){return"input"===f.tagName.toLowerCase()?f:f.firstChild}qa(f){return this.Qa(f)}o(f,d){const k=this.Qa(f);k.checked=d.isChecked;k.disabled=!d.isEnabled;f.title=d.title;f===k?k.value=d.text:f.lastChild.textContent=
d.text}})}"use strict";function T(g){window.C3_RegisterSW&&window.OfflineClientInfo&&window.OfflineClientInfo.SetMessageCallback(f=>t(g,"sw-message",f.data))}
function U(g){g=g.orientation;if(screen.orientation&&screen.orientation.lock)screen.orientation.lock(g).catch(f=>console.warn("[Construct 3] Failed to lock orientation: ",f));else try{let f=!1;screen.lockOrientation?f=screen.lockOrientation(g):screen.webkitLockOrientation?f=screen.webkitLockOrientation(g):screen.mozLockOrientation?f=screen.mozLockOrientation(g):screen.msLockOrientation&&(f=screen.msLockOrientation(g));f||console.warn("[Construct 3] Failed to lock orientation")}catch(f){console.warn("[Construct 3] Failed to lock orientation: ",
f)}}
self.i.m(class extends self.I{constructor(g){super(g,"browser");this.a="";E(this,[["get-initial-state",f=>this.wa(f)],["ready-for-sw-messages",()=>T(this)],["alert",f=>this.ua(f)],["close",()=>{navigator.app&&navigator.app.exitApp?navigator.app.exitApp():navigator.device&&navigator.device.exitApp?navigator.device.exitApp():window.close()}],["set-focus",f=>this.za(f)],["vibrate",f=>{navigator.vibrate&&navigator.vibrate(f.pattern)}],["lock-orientation",f=>U(f)],["unlock-orientation",()=>{try{screen.orientation&&screen.orientation.unlock?
screen.orientation.unlock():screen.unlockOrientation?screen.unlockOrientation():screen.webkitUnlockOrientation?screen.webkitUnlockOrientation():screen.mozUnlockOrientation?screen.mozUnlockOrientation():screen.msUnlockOrientation&&screen.msUnlockOrientation()}catch(f){}}],["navigate",f=>{var d=f.type;if("back"===d)navigator.app&&navigator.app.backHistory?navigator.app.backHistory():window.history.back();else if("forward"===d)window.history.forward();else if("reload"===d)location.reload();else if("url"===
d){d=f.url;const k=f.target;f=f.exportType;self.cordova&&self.cordova.InAppBrowser?self.cordova.InAppBrowser.open(d,"_system"):"preview"===f||"windows-webview2"===f?window.open(d,"_blank"):this.Gc||(2===k?window.top.location=d:1===k?window.parent.location=d:window.location=d)}else"new-window"===d&&(d=f.url,f=f.tag,self.cordova&&self.cordova.InAppBrowser?self.cordova.InAppBrowser.open(d,"_system"):window.open(d,f))}],["request-fullscreen",f=>{if("windows-webview2"===this.a||"macos-wkwebview"===this.a)self.i.Z(!0),
this.f.Ca({type:"set-fullscreen",fullscreen:!0});else{const d={navigationUI:"auto"};f=f.navUI;1===f?d.navigationUI="hide":2===f&&(d.navigationUI="show");f=document.documentElement;f.requestFullscreen?f.requestFullscreen(d):f.mozRequestFullScreen?f.mozRequestFullScreen(d):f.msRequestFullscreen?f.msRequestFullscreen(d):f.webkitRequestFullScreen&&("undefined"!==typeof Element.ALLOW_KEYBOARD_INPUT?f.webkitRequestFullScreen(Element.ALLOW_KEYBOARD_INPUT):f.webkitRequestFullScreen())}}],["exit-fullscreen",
()=>{"windows-webview2"===this.a||"macos-wkwebview"===this.a?(self.i.Z(!1),this.f.Ca({type:"set-fullscreen",fullscreen:!1})):document.exitFullscreen?document.exitFullscreen():document.mozCancelFullScreen?document.mozCancelFullScreen():document.msExitFullscreen?document.msExitFullscreen():document.webkitCancelFullScreen&&document.webkitCancelFullScreen()}],["set-hash",f=>{location.hash=f.hash}]]);window.addEventListener("online",()=>{t(this,"online-state",{isOnline:!0})});window.addEventListener("offline",
()=>{t(this,"online-state",{isOnline:!1})});window.addEventListener("hashchange",()=>{t(this,"hashchange",{location:location.toString()})});document.addEventListener("backbutton",()=>{t(this,"backbutton")})}wa(g){this.a=g.exportType;return{location:location.toString(),isOnline:!!navigator.onLine,referrer:document.referrer,title:document.title,isCookieEnabled:!!navigator.cookieEnabled,screenWidth:screen.width,screenHeight:screen.height,windowOuterWidth:window.outerWidth,windowOuterHeight:window.outerHeight,
isScirraArcade:"undefined"!==typeof window.is_scirra_arcade}}ua(g){alert(g.message)}za(g){g=g.isFocus;if("nwjs"===this.a){const f="nwjs"===this.a?nw.Window.get():null;g?f.focus():f.blur()}else g?window.focus():window.blur()}});"use strict";
{function g(d){d.stopPropagation()}function f(d){13!==d.which&&27!==d.which&&d.stopPropagation()}self.i.m(class extends self.la{constructor(d){super(d,"text-input");N(this,"scroll-to-bottom",k=>this.ac(k))}V(d,k){let l;const w=k.type;"textarea"===w?(l=document.createElement("textarea"),l.style.resize="none"):(l=document.createElement("input"),l.type=w);l.style.position="absolute";l.autocomplete="off";l.addEventListener("touchstart",g);l.addEventListener("touchmove",g);l.addEventListener("touchend",
g);l.addEventListener("mousedown",g);l.addEventListener("mouseup",g);l.addEventListener("keydown",f);l.addEventListener("keyup",f);l.addEventListener("click",p=>{p.stopPropagation();P(this,"click",d)});l.addEventListener("dblclick",p=>{p.stopPropagation();P(this,"dblclick",d)});l.addEventListener("input",()=>M(this,"change",d,{text:l.value}));k.id&&(l.id=k.id);this.o(l,k);return l}o(d,k){d.value=k.text;d.placeholder=k.placeholder;d.title=k.title;d.disabled=!k.isEnabled;d.readOnly=k.isReadOnly;d.spellcheck=
k.spellCheck;k=k.maxLength;0>k?d.removeAttribute("maxlength"):d.setAttribute("maxlength",k)}ac(d){d.scrollTop=d.scrollHeight}})}"use strict";
{function g(f){f.stopPropagation()}self.i.m(class extends self.la{constructor(f){super(f,"list");N(this,"set-selected-index",(d,k)=>this.cc(d,k.selectedIndex));N(this,"add-item",(d,k)=>this.Db(d,k));N(this,"remove-item",(d,k)=>this.Yb(d,k));N(this,"set-item",(d,k)=>this.bc(d,k));N(this,"clear",d=>this.Gb(d));N(this,"load-state",(d,k)=>this.Rb(d,k))}V(f,d){const k=d.isDropdown,l=d.isMultiSelect,w=d.items,p=document.createElement("select");p.style.position="absolute";p.style.userSelect="none";p.style.webkitUserSelect=
"none";p.multiple=l;k||(p.size=2);for(const x of w)p.add(this.pa(x));p.addEventListener("touchstart",g);p.addEventListener("touchmove",g);p.addEventListener("touchend",g);p.addEventListener("mousedown",g);p.addEventListener("mouseup",g);p.addEventListener("click",x=>{x.stopPropagation();P(this,"click",f,this.ra(p))});p.addEventListener("dblclick",x=>{x.stopPropagation();P(this,"dblclick",f,this.ra(p))});p.addEventListener("change",()=>M(this,"change",f,this.ra(p)));d.id&&(p.id=d.id);this.o(p,d);return p}pa(f){const d=
document.createElement("option");d.text=f;return d}ra(f){const d=f.selectedIndex,k=[];for(let l=0,w=f.length;l<w;++l)f.options[l].selected&&k.push(l);return{selectedIndex:d,selectedIndices:k}}o(f,d){f.title=d.title;f.disabled=!d.isEnabled;f.multiple=!!d.isMultiSelect}cc(f,d){f.selectedIndex=d}Db(f,d){const k=d.index;d=this.pa(d.text);0>k?f.add(d):f.add(d,k)}Yb(f,d){f.remove(d.index)}bc(f,d){f.options[d.index].text=d.text}Gb(f){f.innerHTML=""}Rb(f,d){f.innerHTML="";for(const k of d.items)f.add(this.pa(k));
f.selectedIndex=d.selectedIndex;for(const k of d.selectedIndices)if(d=f.options[k])d.selected=!0}})}"use strict";async function V(g,f){f=f.type;let d=!0;0===f?d=await W():1===f&&(d=await X());t(g,"permission-result",{type:f,result:d})}
async function W(){if(!self.DeviceOrientationEvent||!self.DeviceOrientationEvent.requestPermission)return!0;try{return"granted"===await self.DeviceOrientationEvent.requestPermission()}catch(g){return console.warn("[Touch] Failed to request orientation permission: ",g),!1}}
async function X(){if(!self.DeviceMotionEvent||!self.DeviceMotionEvent.requestPermission)return!0;try{return"granted"===await self.DeviceMotionEvent.requestPermission()}catch(g){return console.warn("[Touch] Failed to request motion permission: ",g),!1}}self.i.m(class extends self.I{constructor(g){super(g,"touch");A(this,"request-permission",f=>V(this,f))}});"use strict";
async function Y(g){if(!g.A)try{g.A=await navigator.wakeLock.request("screen"),g.A.addEventListener("release",()=>{console.log("[Construct 3] Screen wake lock released");g.A=null;t(g,"wake-lock-released")}),console.log("[Construct 3] Screen wake lock acquired"),t(g,"wake-lock-acquired")}catch(f){console.warn("[Construct 3] Failed to acquire screen wake lock: ",f),t(g,"wake-lock-error")}}
function Z(){var g=document.body;const f=g.style;f.setProperty("--temp-sai-top","env(safe-area-inset-top)");f.setProperty("--temp-sai-right","env(safe-area-inset-right)");f.setProperty("--temp-sai-bottom","env(safe-area-inset-bottom)");f.setProperty("--temp-sai-left","env(safe-area-inset-left)");g=getComputedStyle(g);g=[g.getPropertyValue("--temp-sai-top"),g.getPropertyValue("--temp-sai-right"),g.getPropertyValue("--temp-sai-bottom"),g.getPropertyValue("--temp-sai-left")].map(d=>{d=parseInt(d,10);
return isFinite(d)?d:0});f.removeProperty("--temp-sai-top");f.removeProperty("--temp-sai-right");f.removeProperty("--temp-sai-bottom");f.removeProperty("--temp-sai-left");return g}
self.i.m(class extends self.I{constructor(g){super(g,"platform-info");E(this,[["get-initial-state",()=>this.wa()],["request-wake-lock",()=>Y(this)],["release-wake-lock",()=>{this.A&&(this.A.release(),this.A=null)}]]);window.addEventListener("resize",()=>{t(this,"window-resize",{windowOuterWidth:window.outerWidth,windowOuterHeight:window.outerHeight,safeAreaInset:Z()})});this.A=null}wa(){return{screenWidth:screen.width,screenHeight:screen.height,windowOuterWidth:window.outerWidth,windowOuterHeight:window.outerHeight,
safeAreaInset:Z(),supportsWakeLock:!!navigator.wakeLock}}});
