'use strict';function u(f,d,c,h){f.f.ka(f.M,d,c,h,void 0)}function z(f,d,c,h){f.f.j?u(f,d,c,h):f.f.xb()._OnMessageFromDOM({type:"event",component:f.M,handler:d,dispatchOpts:h||null,data:c,responseId:null})}function B(f,d,c){f.f.b(f.M,d,c)}function G(f,d){for(const [c,h]of d)B(f,c,h)}window.H=class{constructor(f,d){this.f=f;this.M=d}Ka(){}};
window.mb=class{constructor(f,d){this.Za=f;this.kc=d;this.F=-1;this.ba=-Infinity;this.pc=()=>{this.F=-1;this.ba=Date.now();this.N=!0;this.Za();this.N=!1};this.$a=this.N=!1}};"use strict";function J(f,d){const c=d.elementId,h=f.U(c,d);f.h.set(c,h);d.isVisible||(h.style.display="none");d=f.na(h);d.addEventListener("focus",()=>{N(f,"elem-focused",c)});d.addEventListener("blur",()=>{N(f,"elem-blurred",c)});f.Z&&document.body.appendChild(h)}
function O(f,d,c){B(f,d,h=>{const m=f.h.get(h.elementId);return c(m,h)})}function N(f,d,c,h){h||(h={});h.elementId=c;u(f,d,h)}function Q(f,d,c,h){h||(h={});h.elementId=c;z(f,d,h)}
window.ia=class extends self.H{constructor(f,d){super(f,d);this.h=new Map;this.Z=!0;G(this,[["create",c=>J(this,c)],["destroy",c=>{{c=c.elementId;const h=this.h.get(c);this.Z&&h.parentElement.removeChild(h);this.h.delete(c)}}],["set-visible",c=>{this.Z&&(this.h.get(c.elementId).style.display=c.isVisible?"":"none")}],["update-position",c=>{if(this.Z){var h=this.h.get(c.elementId);h.style.left=c.left+"px";h.style.top=c.top+"px";h.style.width=c.width+"px";h.style.height=c.height+"px";c=c.fontSize;null!==
c&&(h.style.fontSize=c+"em")}}],["update-state",c=>{{const h=this.h.get(c.elementId);this.o(h,c)}}],["focus",c=>this.wa(c)],["set-css-style",c=>{this.h.get(c.elementId).style[c.prop]=c.val}],["set-attribute",c=>{this.h.get(c.elementId).setAttribute(c.name,c.val)}],["remove-attribute",c=>{this.h.get(c.elementId).removeAttribute(c.name)}]]);O(this,"get-element",c=>c)}U(){throw Error("required override");}o(){throw Error("required override");}na(f){return f}wa(f){const d=this.na(this.h.get(f.elementId));
f.focus?d.focus():d.blur()}};"use strict";
{const f=/(iphone|ipod|ipad|macos|macintosh|mac os x)/i.test(navigator.userAgent);let d=0;function c(l){const a=document.createElement("script");a.async=!1;a.type="module";return l.uc?new Promise(g=>{const k="c3_resolve_"+d;++d;self[k]=g;a.textContent=l.xc+`\n\nself["${k}"]();`;document.head.appendChild(a)}):new Promise((g,k)=>{a.onload=g;a.onerror=k;a.src=l;document.head.appendChild(a)})}let h=!1,m=!1;function y(){if(!h){try{new Worker("blob://",{get type(){m=!0}})}catch(l){}h=!0}return m}const q=
/safari\//i.test(navigator.userAgent)&&!/chrome\/|chromium\/|edg\//i.test(navigator.userAgent);let v=new Audio;const C={"audio/webm; codecs=opus":!!v.canPlayType("audio/webm; codecs=opus")&&!q,"audio/ogg; codecs=opus":!!v.canPlayType("audio/ogg; codecs=opus"),"audio/webm; codecs=vorbis":!!v.canPlayType("audio/webm; codecs=vorbis"),"audio/ogg; codecs=vorbis":!!v.canPlayType("audio/ogg; codecs=vorbis"),"audio/mp4":!!v.canPlayType("audio/mp4"),"audio/mpeg":!!v.canPlayType("audio/mpeg")};v=null;async function P(l){l=
await K(l);return(new TextDecoder("utf-8")).decode(l)}function K(l){return new Promise((a,g)=>{const k=new FileReader;k.onload=n=>a(n.target.result);k.onerror=n=>g(n);k.readAsArrayBuffer(l)})}const A=[];let D=0;window.RealFile=window.File;const E=[],w=new Map,F=new Map;let I=0;const L=[];self.runOnStartup=function(l){if("function"!==typeof l)throw Error("runOnStartup called without a function");L.push(l)};const b=new Set(["cordova","playable-ad","instant-games"]);let e=!1;window.i=class l{constructor(a){this.j=
a.zc;this.P=null;this.c="";this.ea=a.wc;this.T={};this.Da=this.eb=null;this.$=[];this.O=this.g=this.Ga=null;this.C=-1;this.oc=()=>this.Tb();this.cb=[];this.a=a.fb;this.aa="file"===location.protocol.substr(0,4);!this.j||"undefined"!==typeof OffscreenCanvas&&navigator.userActivation&&y()||(this.j=!1);if("playable-ad"===this.a||"instant-games"===this.a)this.j=!1;if("cordova"===this.a&&this.j)if(/android/i.test(navigator.userAgent)){const g=/Chrome\/(\d+)/i.exec(navigator.userAgent);g&&90<=parseInt(g[1],
10)||(this.j=!1)}else this.j=!1;this.ca=this.l=null;"html5"!==this.a&&"playable-ad"!==this.a||!this.aa||alert("Exported games won't work until you upload them. (When running on the file: protocol, browsers block many features from working for security reasons.)");this.b("runtime","cordova-fetch-local-file",g=>this.Fb(g));this.b("runtime","create-job-worker",()=>this.Gb());"cordova"===this.a?document.addEventListener("deviceready",()=>this.Pa(a)):this.Pa(a)}jb(){return f&&"cordova"===this.a}ja(){const a=
navigator.userAgent;return f&&b.has(this.a)||navigator.standalone||/crios\/|fxios\/|edgios\//i.test(a)}async Pa(a){"macos-wkwebview"===this.a&&this.za({type:"ready"});if("playable-ad"===this.a){this.l=self.c3_base64files;this.ca={};await this.sb();for(let k=0,n=a.G.length;k<n;++k){var g=a.G[k].toLowerCase();this.ca.hasOwnProperty(g)?a.G[k]={uc:!0,xc:this.ca[g]}:this.l.hasOwnProperty(g)&&(a.G[k]=URL.createObjectURL(this.l[g]))}}a.qc?this.c=a.qc:(g=location.origin,this.c=("null"===g?"file:///":g)+location.pathname,
g=this.c.lastIndexOf("/"),-1!==g&&(this.c=this.c.substr(0,g+1)));a.Bc&&(this.T=a.Bc);g=new MessageChannel;this.P=g.port1;this.P.onmessage=k=>this._OnMessageFromRuntime(k.data);window.c3_addPortMessageHandler&&window.c3_addPortMessageHandler(k=>this.Qb(k));this.O=new self.kb(this);await R(this.O);"object"===typeof window.StatusBar&&window.StatusBar.hide();"object"===typeof window.AndroidFullScreen&&window.AndroidFullScreen.immersiveMode();this.j?await this.zb(a,g.port2):await this.yb(a,g.port2)}pa(a){a=
this.T.hasOwnProperty(a)?this.T[a]:a.endsWith("/workermain.js")&&this.T.hasOwnProperty("workermain.js")?this.T["workermain.js"]:"playable-ad"===this.a&&this.l.hasOwnProperty(a.toLowerCase())?this.l[a.toLowerCase()]:a;a instanceof Blob&&(a=URL.createObjectURL(a));return a}async ha(a,g,k){if(a.startsWith("blob:"))return new Worker(a,k);if("cordova"===this.a&&this.aa)return a=await this.ga(k.tc?a:this.ea+a),new Worker(URL.createObjectURL(new Blob([a],{type:"application/javascript"})),k);a=new URL(a,
g);if(location.origin!==a.origin){a=await fetch(a);if(!a.ok)throw Error("failed to fetch worker script");a=await a.blob();return new Worker(URL.createObjectURL(a),k)}return new Worker(a,k)}u(){return Math.max(window.innerWidth,1)}s(){return Math.max(window.innerHeight,1)}Na(a){var g=this.O;return{baseUrl:this.c,windowInnerWidth:this.u(),windowInnerHeight:this.s(),devicePixelRatio:window.devicePixelRatio,isFullscreen:l.I(),projectData:a.Hc,previewImageBlobs:window.cr_previewImageBlobs||this.l,previewProjectFileBlobs:window.cr_previewProjectFileBlobs,
previewProjectFileSWUrls:window.cr_previewProjectFiles,swClientId:window.Fc||"",exportType:a.fb,isDebug:-1<self.location.search.indexOf("debug"),ife:!!self.Gc,jobScheduler:{inputPort:g.Ba,outputPort:g.Fa,maxNumWorkers:g.mc},supportedAudioFormats:C,opusWasmScriptUrl:window.cr_opusWasmScriptUrl||this.ea+"opus.wasm.js",opusWasmBinaryUrl:window.cr_opusWasmBinaryUrl||this.ea+"opus.wasm.wasm",isFileProtocol:this.aa,isiOSCordova:this.jb(),isiOSWebView:this.ja(),isFBInstantAvailable:"undefined"!==typeof self.FBInstant}}async zb(a,
g){var k=this.pa(a.Ac);this.eb=await this.ha(k,this.c,{type:"module",name:"Runtime",tc:!0});this.g=document.createElement("canvas");this.g.style.display="none";k=this.g.transferControlToOffscreen();document.body.appendChild(this.g);window.c3canvas=this.g;let n=a.Ja||[],t=a.G;n=await Promise.all(n.map(p=>this.B(p)));t=await Promise.all(t.map(p=>this.B(p)));if("cordova"===this.a)for(let p=0,r=a.fa.length;p<r;++p){const x=a.fa[p],M=x[0];if(M===a.Ia||"scriptsInEvents.js"===M||M.endsWith("/scriptsInEvents.js"))x[1]=
await this.B(M)}this.eb.postMessage(Object.assign(this.Na(a),{type:"init-runtime",isInWorker:!0,messagePort:g,canvas:k,workerDependencyScripts:n,engineScripts:t,projectScripts:a.fa,mainProjectScript:a.Ia,projectScriptsStatus:self.C3_ProjectScriptsStatus}),[g,k,...S(this.O)]);this.$=E.map(p=>new p(this));this.Ma();self.c3_callFunction=(p,r)=>this.Ga.Ab(p,r);"preview"===this.a&&(self.goToLastErrorScript=()=>this.ka("runtime","go-to-last-error-script"))}async yb(a,g){this.g=document.createElement("canvas");
this.g.style.display="none";document.body.appendChild(this.g);window.c3canvas=this.g;this.$=E.map(p=>new p(this));this.Ma();var k=a.G.map(p=>"string"===typeof p?(new URL(p,this.c)).toString():p);Array.isArray(a.Ja)&&k.unshift(...a.Ja);k=await Promise.all(k.map(p=>this.B(p)));await Promise.all(k.map(p=>c(p)));k=self.C3_ProjectScriptsStatus;const n=a.Ia,t=a.fa;for(let [p,r]of t)if(r||(r=p),p===n)try{r=await this.B(r),await c(r),"preview"!==this.a||k[p]||this.Va(p,"main script did not run to completion")}catch(x){this.Va(p,
x)}else if("scriptsInEvents.js"===p||p.endsWith("/scriptsInEvents.js"))r=await this.B(r),await c(r);"preview"===this.a&&"object"!==typeof self.Cc.Dc?(this.X(),console.error("[C3 runtime] Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax."),alert("Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax.")):(a=Object.assign(this.Na(a),{isInWorker:!1,messagePort:g,canvas:this.g,runOnStartupFunctions:L}),this.Ra(),this.Da=
self.C3_CreateRuntime(a),await self.C3_InitRuntime(this.Da,a))}Va(a,g){this.X();console.error(`[Preview] Failed to load project main script (${a}): `,g);alert(`Failed to load project main script (${a}). Check all your JavaScript code has valid syntax. Press F12 and check the console for error details.`)}Ra(){this.X()}X(){const a=window.rc;a&&(a.parentElement.removeChild(a),window.rc=null)}async Gb(){const a=await T(this.O);return{outputPort:a,transferables:[a]}}xb(){if(this.j)throw Error("not available in worker mode");
return this.Da}ka(a,g,k,n,t){this.P.postMessage({type:"event",component:a,handler:g,dispatchOpts:n||null,data:k,responseId:null},t)}lb(a,g){const k=I++,n=new Promise((t,p)=>{F.set(k,{resolve:t,reject:p})});this.P.postMessage({type:"event",component:a,handler:"js-invoke-function",dispatchOpts:null,data:g,responseId:k},void 0);return n}["_OnMessageFromRuntime"](a){const g=a.type;if("event"===g)return this.Lb(a);if("result"===g)this.Xb(a);else if("runtime-ready"===g)this.Yb();else if("alert-error"===
g)this.X(),alert(a.message);else if("creating-runtime"===g)this.Ra();else throw Error(`unknown message '${g}'`);}Lb(a){const g=a.component,k=a.handler,n=a.data,t=a.responseId;if(a=w.get(g))if(a=a.get(k)){var p=null;try{p=a(n)}catch(r){console.error(`Exception in '${g}' handler '${k}':`,r);null!==t&&this.W(t,!1,""+r);return}if(null===t)return p;p&&p.then?p.then(r=>this.W(t,!0,r)).catch(r=>{console.error(`Rejection from '${g}' handler '${k}':`,r);this.W(t,!1,""+r)}):this.W(t,!0,p)}else console.warn(`[DOM] No handler '${k}' for component '${g}'`);
else console.warn(`[DOM] No event handlers for component '${g}'`)}W(a,g,k){let n;k&&k.transferables&&(n=k.transferables);this.P.postMessage({type:"result",responseId:a,isOk:g,result:k},n)}Xb(a){const g=a.responseId,k=a.isOk;a=a.result;const n=F.get(g);k?n.resolve(a):n.reject(a);F.delete(g)}b(a,g,k){let n=w.get(a);n||(n=new Map,w.set(a,n));if(n.has(g))throw Error(`[DOM] Component '${a}' already has handler '${g}'`);n.set(g,k)}static m(a){if(E.includes(a))throw Error("DOM handler already added");E.push(a)}Ma(){for(const a of this.$)if("runtime"===
a.M){this.Ga=a;return}throw Error("cannot find runtime DOM handler");}Qb(a){this.ka("debugger","message",a)}Yb(){for(const a of this.$)a.Ka()}static I(){return!!(document.fullscreenElement||document.webkitFullscreenElement||document.mozFullScreenElement||e)}static Y(a){e=!!a}Wa(){-1===this.C&&this.cb.length&&(this.C=requestAnimationFrame(this.oc))}qb(){-1!==this.C&&(cancelAnimationFrame(this.C),this.C=-1)}Tb(){this.C=-1;for(const a of this.cb)a();this.Wa()}ya(){this.Ga.ya()}hb(a){return/^(?:[a-z\-]+:)?\/\//.test(a)||
"data:"===a.substr(0,5)||"blob:"===a.substr(0,5)}ib(a){return!this.hb(a)}async B(a){return"cordova"===this.a&&(a.startsWith("file:")||this.aa&&this.ib(a))?(a.startsWith(this.c)&&(a=a.substr(this.c.length)),a=await this.ga(a),URL.createObjectURL(new Blob([a],{type:"application/javascript"}))):a}async Fb(a){const g=a.filename;switch(a.as){case "text":return await this.gb(g);case "buffer":return await this.ga(g);default:throw Error("unsupported type");}}La(a){const g=window.cordova.file.applicationDirectory+
"www/"+a.toLowerCase();return new Promise((k,n)=>{window.resolveLocalFileSystemURL(g,t=>{t.file(k,n)},n)})}async gb(a){a=await this.La(a);return await P(a)}la(){if(A.length&&!(8<=D)){D++;var a=A.shift();this.tb(a.filename,a.yc,a.sc)}}ga(a){return new Promise((g,k)=>{A.push({filename:a,yc:n=>{D--;this.la();g(n)},sc:n=>{D--;this.la();k(n)}});this.la()})}async tb(a,g,k){try{const n=await this.La(a),t=await K(n);g(t)}catch(n){k(n)}}za(a){if("windows-webview2"===this.a)window.chrome.webview.postMessage(JSON.stringify(a));
else if("macos-wkwebview"===this.a)window.webkit.messageHandlers.C3Wrapper.postMessage(JSON.stringify(a));else throw Error("cannot send wrapper message");}async sb(){const a=[];for(const [g,k]of Object.entries(this.l))a.push(this.rb(g,k));await Promise.all(a)}async rb(a,g){if("object"===typeof g)this.l[a]=new Blob([g.str],{type:g.type}),this.ca[a]=g.str;else{let k=await this.wb(g);k||(k=this.ub(g));this.l[a]=k}}async wb(a){try{return await (await fetch(a)).blob()}catch(g){return console.warn("Failed to fetch a data: URI. Falling back to a slower workaround. This is probably because the Content Security Policy unnecessarily blocked it. Allow data: URIs in your CSP to avoid this.",
g),null}}ub(a){a=this.fc(a);return this.pb(a.data,a.vc)}fc(a){var g=a.indexOf(",");if(0>g)throw new URIError("expected comma in data: uri");var k=a.substring(g+1);g=a.substring(5,g).split(";");a=g[0]||"";const n=g[2];k="base64"===g[1]||"base64"===n?atob(k):decodeURIComponent(k);return{vc:a,data:k}}pb(a,g){var k=a.length;let n=k>>2,t=new Uint8Array(k),p=new Uint32Array(t.buffer,0,n),r,x;for(x=r=0;r<n;++r)p[r]=a.charCodeAt(x++)|a.charCodeAt(x++)<<8|a.charCodeAt(x++)<<16|a.charCodeAt(x++)<<24;for(k&=
3;k--;)t[x]=a.charCodeAt(x),++x;return new Blob([t],{type:g})}}}"use strict";
{const f=self.i;function d(b){return b.sourceCapabilities&&b.sourceCapabilities.firesTouchEvents||b.originalEvent&&b.originalEvent.sourceCapabilities&&b.originalEvent.sourceCapabilities.firesTouchEvents}const c=new Map([["OSLeft","MetaLeft"],["OSRight","MetaRight"]]),h={dispatchRuntimeEvent:!0,dispatchUserScriptEvent:!0},m={dispatchUserScriptEvent:!0},y={dispatchRuntimeEvent:!0};function q(b){return new Promise((e,l)=>{const a=document.createElement("link");a.onload=()=>e(a);a.onerror=g=>l(g);a.rel=
"stylesheet";a.href=b;document.head.appendChild(a)})}function v(b){return new Promise((e,l)=>{const a=new Image;a.onload=()=>e(a);a.onerror=g=>l(g);a.src=b})}async function C(b){b=URL.createObjectURL(b);try{return await v(b)}finally{URL.revokeObjectURL(b)}}function P(b){return new Promise((e,l)=>{let a=new FileReader;a.onload=g=>e(g.target.result);a.onerror=g=>l(g);a.readAsText(b)})}async function K(b,e,l){if(!/firefox/i.test(navigator.userAgent))return await C(b);var a=await P(b);a=(new DOMParser).parseFromString(a,
"image/svg+xml");const g=a.documentElement;if(g.hasAttribute("width")&&g.hasAttribute("height")){const k=g.getAttribute("width"),n=g.getAttribute("height");if(!k.includes("%")&&!n.includes("%"))return await C(b)}g.setAttribute("width",e+"px");g.setAttribute("height",l+"px");a=(new XMLSerializer).serializeToString(a);b=new Blob([a],{type:"image/svg+xml"});return await C(b)}function A(b){do{if(b.parentNode&&b.hasAttribute("contenteditable"))return!0;b=b.parentNode}while(b);return!1}const D=new Set(["input",
"textarea","datalist","select"]),E=new Set(["canvas","body","html"]);function w(b){E.has(b.target.tagName.toLowerCase())&&b.preventDefault()}function F(b){(b.metaKey||b.ctrlKey)&&b.preventDefault()}self.C3_GetSvgImageSize=async function(b){b=await C(b);if(0<b.width&&0<b.height)return[b.width,b.height];{b.style.position="absolute";b.style.left="0px";b.style.top="0px";b.style.visibility="hidden";document.body.appendChild(b);const e=b.getBoundingClientRect();document.body.removeChild(b);return[e.width,
e.height]}};self.C3_RasterSvgImageBlob=async function(b,e,l,a,g){b=await K(b,e,l);const k=document.createElement("canvas");k.width=a;k.height=g;k.getContext("2d").drawImage(b,0,0,e,l);return k};let I=!1;document.addEventListener("pause",()=>I=!0);document.addEventListener("resume",()=>I=!1);function L(){try{return window.parent&&window.parent.document.hasFocus()}catch(b){return!1}}f.m(class extends self.H{constructor(b){super(b,"runtime");this.ab=!0;this.D=-1;this.Ha="any";this.Xa=this.Ya=!1;this.Ca=
this.S=this.v=null;b.b("canvas","update-size",a=>this.cc(a));b.b("runtime","invoke-download",a=>this.Ob(a));b.b("runtime","raster-svg-image",a=>this.Ub(a));b.b("runtime","get-svg-image-size",a=>this.Mb(a));b.b("runtime","set-target-orientation",a=>this.bc(a));b.b("runtime","register-sw",()=>this.Vb());b.b("runtime","post-to-debugger",a=>this.Ta(a));b.b("runtime","go-to-script",a=>this.Ta(a));b.b("runtime","before-start-ticking",()=>this.Db());b.b("runtime","debug-highlight",a=>this.Hb(a));b.b("runtime",
"enable-device-orientation",()=>this.ob());b.b("runtime","enable-device-motion",()=>this.nb());b.b("runtime","add-stylesheet",a=>this.Cb(a));b.b("runtime","alert",a=>this.ra(a));b.b("runtime","hide-cordova-splash",()=>this.Nb());const e=new Set(["input","textarea","datalist"]);window.addEventListener("contextmenu",a=>{const g=a.target;e.has(g.tagName.toLowerCase())||A(g)||a.preventDefault()});const l=b.g;window.addEventListener("selectstart",w);window.addEventListener("gesturehold",w);l.addEventListener("selectstart",
w);l.addEventListener("gesturehold",w);window.addEventListener("touchstart",w,{passive:!1});"undefined"!==typeof PointerEvent?(window.addEventListener("pointerdown",w,{passive:!1}),l.addEventListener("pointerdown",w)):l.addEventListener("touchstart",w);this.R=0;window.addEventListener("mousedown",a=>{1===a.button&&a.preventDefault()});window.addEventListener("mousewheel",F,{passive:!1});window.addEventListener("wheel",F,{passive:!1});window.addEventListener("resize",()=>this.dc());window.addEventListener("fullscreenchange",
()=>this.J());window.addEventListener("webkitfullscreenchange",()=>this.J());window.addEventListener("mozfullscreenchange",()=>this.J());window.addEventListener("fullscreenerror",a=>this.sa(a));window.addEventListener("webkitfullscreenerror",a=>this.sa(a));window.addEventListener("mozfullscreenerror",a=>this.sa(a));b.ja()&&window.addEventListener("focusout",()=>{{const k=document.activeElement;if(k){var a=k.tagName.toLowerCase();var g=new Set("email number password search tel text url".split(" "));
a="textarea"===a?!0:"input"===a?g.has(k.type.toLowerCase()||"text"):A(k)}else a=!1}a||(document.scrollingElement.scrollTop=0)});self.C3WrapperOnMessage=a=>this.ec(a);this.Ea=new Set;this.nc=new WeakSet;this.lc=!1}Db(){"cordova"===this.f.a?(document.addEventListener("pause",()=>this.xa(!0)),document.addEventListener("resume",()=>this.xa(!1))):document.addEventListener("visibilitychange",()=>this.xa(document.hidden));return{isSuspended:!(!document.hidden&&!I)}}Ka(){window.addEventListener("focus",()=>
this.L("window-focus"));window.addEventListener("blur",()=>{this.L("window-blur",{parentHasFocus:L()});this.R=0});window.addEventListener("focusin",e=>{e=e.target;(D.has(e.tagName.toLowerCase())||A(e))&&this.L("keyboard-blur")});window.addEventListener("keydown",e=>this.Sa("keydown",e));window.addEventListener("keyup",e=>this.Sa("keyup",e));window.addEventListener("dblclick",e=>this.ua("dblclick",e,h));window.addEventListener("wheel",e=>this.Rb(e));"undefined"!==typeof PointerEvent?(window.addEventListener("pointerdown",
e=>{this.qa(e);this.K("pointerdown",e)}),this.f.j&&"undefined"!==typeof window.onpointerrawupdate&&self===self.top?(this.S=new self.mb(()=>this.vb(),5),this.S.$a=!0,window.addEventListener("pointerrawupdate",e=>this.Sb(e))):window.addEventListener("pointermove",e=>this.K("pointermove",e)),window.addEventListener("pointerup",e=>this.K("pointerup",e)),window.addEventListener("pointercancel",e=>this.K("pointercancel",e))):(window.addEventListener("mousedown",e=>{this.qa(e);this.va("pointerdown",e)}),
window.addEventListener("mousemove",e=>this.va("pointermove",e)),window.addEventListener("mouseup",e=>this.va("pointerup",e)),window.addEventListener("touchstart",e=>{this.qa(e);this.V("pointerdown",e)}),window.addEventListener("touchmove",e=>this.V("pointermove",e)),window.addEventListener("touchend",e=>this.V("pointerup",e)),window.addEventListener("touchcancel",e=>this.V("pointercancel",e)));const b=()=>this.ya();window.addEventListener("pointerup",b,!0);window.addEventListener("touchend",b,!0);
window.addEventListener("click",b,!0);window.addEventListener("keydown",b,!0);window.addEventListener("gamepadconnected",b,!0)}L(b,e){u(this,b,e||null,y)}u(){return this.f.u()}s(){return this.f.s()}dc(){const b=this.u(),e=this.s();this.L("window-resize",{innerWidth:b,innerHeight:e,devicePixelRatio:window.devicePixelRatio,isFullscreen:f.I()});this.f.ja()&&(-1!==this.D&&clearTimeout(this.D),this.Ua(b,e,0))}hc(b,e,l){-1!==this.D&&clearTimeout(this.D);this.D=setTimeout(()=>this.Ua(b,e,l),48)}Ua(b,e,l){const a=
this.u(),g=this.s();this.D=-1;a!=b||g!=e?this.L("window-resize",{innerWidth:a,innerHeight:g,devicePixelRatio:window.devicePixelRatio,isFullscreen:f.I()}):10>l&&this.hc(a,g,l+1)}bc(b){this.Ha=b.targetOrientation}ic(){const b=this.Ha;if(screen.orientation&&screen.orientation.lock)screen.orientation.lock(b).catch(e=>console.warn("[Construct 3] Failed to lock orientation: ",e));else try{let e=!1;screen.lockOrientation?e=screen.lockOrientation(b):screen.webkitLockOrientation?e=screen.webkitLockOrientation(b):
screen.mozLockOrientation?e=screen.mozLockOrientation(b):screen.msLockOrientation&&(e=screen.msLockOrientation(b));e||console.warn("[Construct 3] Failed to lock orientation")}catch(e){console.warn("[Construct 3] Failed to lock orientation: ",e)}}J(){const b=f.I();b&&"any"!==this.Ha&&this.ic();u(this,"fullscreenchange",{isFullscreen:b,innerWidth:this.u(),innerHeight:this.s()})}sa(b){console.warn("[Construct 3] Fullscreen request failed: ",b);u(this,"fullscreenerror",{isFullscreen:f.I(),innerWidth:this.u(),
innerHeight:this.s()})}xa(b){b?this.f.qb():this.f.Wa();u(this,"visibilitychange",{hidden:b})}Sa(b,e){"Backspace"===e.key&&w(e);const l=c.get(e.code)||e.code;z(this,b,{code:l,key:e.key,which:e.which,repeat:e.repeat,altKey:e.altKey,ctrlKey:e.ctrlKey,metaKey:e.metaKey,shiftKey:e.shiftKey,timeStamp:e.timeStamp},h)}Rb(b){u(this,"wheel",{clientX:b.clientX,clientY:b.clientY,pageX:b.pageX,pageY:b.pageY,deltaX:b.deltaX,deltaY:b.deltaY,deltaZ:b.deltaZ,deltaMode:b.deltaMode,timeStamp:b.timeStamp},h)}ua(b,e,
l){d(e)||z(this,b,{button:e.button,buttons:e.buttons,clientX:e.clientX,clientY:e.clientY,pageX:e.pageX,pageY:e.pageY,timeStamp:e.timeStamp},l)}va(b,e){if(!d(e)){var l=this.R;"pointerdown"===b&&0!==l?b="pointermove":"pointerup"===b&&0!==e.buttons&&(b="pointermove");z(this,b,{pointerId:1,pointerType:"mouse",button:e.button,buttons:e.buttons,lastButtons:l,clientX:e.clientX,clientY:e.clientY,pageX:e.pageX,pageY:e.pageY,width:0,height:0,pressure:0,tangentialPressure:0,tiltX:0,tiltY:0,twist:0,timeStamp:e.timeStamp},
h);this.R=e.buttons;this.ua(e.type,e,m)}}K(b,e){if(this.S&&"pointermove"!==b){var l=this.S;l.N||(-1!==l.F&&(self.clearTimeout(l.F),l.F=-1),l.ba=Date.now())}l=0;"mouse"===e.pointerType&&(l=this.R);z(this,b,{pointerId:e.pointerId,pointerType:e.pointerType,button:e.button,buttons:e.buttons,lastButtons:l,clientX:e.clientX,clientY:e.clientY,pageX:e.pageX,pageY:e.pageY,width:e.width||0,height:e.height||0,pressure:e.pressure||0,tangentialPressure:e.tangentialPressure||0,tiltX:e.tiltX||0,tiltY:e.tiltY||0,
twist:e.twist||0,timeStamp:e.timeStamp},h);"mouse"===e.pointerType&&(l="mousemove","pointerdown"===b?l="mousedown":"pointerup"===b&&(l="mouseup"),this.ua(l,e,m),this.R=e.buttons)}Sb(b){this.Ca=b;b=this.S;if(-1===b.F){var e=Date.now(),l=e-b.ba,a=b.kc;l>=a&&b.$a?(b.ba=e,b.N=!0,b.Za(),b.N=!1):b.F=self.setTimeout(b.pc,Math.max(a-l,4))}}vb(){this.K("pointermove",this.Ca);this.Ca=null}V(b,e){for(let l=0,a=e.changedTouches.length;l<a;++l){const g=e.changedTouches[l];z(this,b,{pointerId:g.identifier,pointerType:"touch",
button:0,buttons:0,lastButtons:0,clientX:g.clientX,clientY:g.clientY,pageX:g.pageX,pageY:g.pageY,width:2*(g.radiusX||g.webkitRadiusX||0),height:2*(g.radiusY||g.webkitRadiusY||0),pressure:g.force||g.webkitForce||0,tangentialPressure:0,tiltX:0,tiltY:0,twist:g.rotationAngle||0,timeStamp:e.timeStamp},h)}}qa(b){window!==window.top&&window.focus();this.Qa(b.target)&&document.activeElement&&!this.Qa(document.activeElement)&&document.activeElement.blur()}Qa(b){return!b||b===document||b===window||b===document.body||
"canvas"===b.tagName.toLowerCase()}ob(){this.Ya||(this.Ya=!0,window.addEventListener("deviceorientation",b=>this.Jb(b)),window.addEventListener("deviceorientationabsolute",b=>this.Kb(b)))}nb(){this.Xa||(this.Xa=!0,window.addEventListener("devicemotion",b=>this.Ib(b)))}Jb(b){u(this,"deviceorientation",{absolute:!!b.absolute,alpha:b.alpha||0,beta:b.beta||0,gamma:b.gamma||0,timeStamp:b.timeStamp,webkitCompassHeading:b.webkitCompassHeading,webkitCompassAccuracy:b.webkitCompassAccuracy},h)}Kb(b){u(this,
"deviceorientationabsolute",{absolute:!!b.absolute,alpha:b.alpha||0,beta:b.beta||0,gamma:b.gamma||0,timeStamp:b.timeStamp},h)}Ib(b){let e=null;var l=b.acceleration;l&&(e={x:l.x||0,y:l.y||0,z:l.z||0});l=null;var a=b.accelerationIncludingGravity;a&&(l={x:a.x||0,y:a.y||0,z:a.z||0});a=null;const g=b.rotationRate;g&&(a={alpha:g.alpha||0,beta:g.beta||0,gamma:g.gamma||0});u(this,"devicemotion",{acceleration:e,accelerationIncludingGravity:l,rotationRate:a,interval:b.interval,timeStamp:b.timeStamp},h)}cc(b){const e=
this.f.g;e.style.width=b.styleWidth+"px";e.style.height=b.styleHeight+"px";e.style.marginLeft=b.marginLeft+"px";e.style.marginTop=b.marginTop+"px";this.ab&&(e.style.display="",this.ab=!1)}Ob(b){const e=b.url;b=b.filename;const l=document.createElement("a"),a=document.body;l.textContent=b;l.href=e;l.download=b;a.appendChild(l);l.click();a.removeChild(l)}async Ub(b){var e=b.imageBitmapOpts;b=await self.C3_RasterSvgImageBlob(b.blob,b.imageWidth,b.imageHeight,b.surfaceWidth,b.surfaceHeight);e=e?await createImageBitmap(b,
e):await createImageBitmap(b);return{imageBitmap:e,transferables:[e]}}async Mb(b){return await self.C3_GetSvgImageSize(b.blob)}async Cb(b){await q(b.url)}ya(){var b=[...this.Ea];this.Ea.clear();if(!this.lc)for(const e of b)(b=e.play())&&b.catch(()=>{this.nc.has(e)||this.Ea.add(e)})}Nb(){navigator.splashscreen&&navigator.splashscreen.hide&&navigator.splashscreen.hide()}Hb(b){if(b.show){this.v||(this.v=document.createElement("div"),this.v.id="inspectOutline",document.body.appendChild(this.v));var e=
this.v;e.style.display="";e.style.left=b.left-1+"px";e.style.top=b.top-1+"px";e.style.width=b.width+2+"px";e.style.height=b.height+2+"px";e.textContent=b.name}else this.v&&(this.v.style.display="none")}Vb(){window.C3_RegisterSW&&window.C3_RegisterSW()}Ta(b){window.c3_postToMessagePort&&(b.from="runtime",window.c3_postToMessagePort(b))}Ab(b,e){return this.f.lb(this.M,{name:b,params:e})}ra(b){alert(b.message)}ec(b){"entered-fullscreen"===b?(f.Y(!0),this.J()):"exited-fullscreen"===b?(f.Y(!1),this.J()):
console.warn("Unknown wrapper message: ",b)}})}"use strict";async function R(f){if(f.jc)throw Error("already initialised");f.jc=!0;var d=f.da.pa("dispatchworker.js");f.Aa=await f.da.ha(d,f.c,{name:"DispatchWorker"});d=new MessageChannel;f.Ba=d.port1;f.Aa.postMessage({type:"_init","in-port":d.port2},[d.port2]);f.Fa=await T(f)}function S(f){return[f.Ba,f.Fa]}
async function T(f){const d=f.bb.length;var c=f.da.pa("jobworker.js");c=await f.da.ha(c,f.c,{name:"JobWorker"+d});const h=new MessageChannel,m=new MessageChannel;f.Aa.postMessage({type:"_addJobWorker",port:h.port1},[h.port1]);c.postMessage({type:"init",number:d,"dispatch-port":h.port2,"output-port":m.port2},[h.port2,m.port2]);f.bb.push(c);return m.port1}
self.kb=class{constructor(f){this.da=f;this.c=f.c;this.c="preview"===f.a?this.c+"workers/":this.c+f.ea;this.mc=Math.min(navigator.hardwareConcurrency||2,16);this.Aa=null;this.bb=[];this.Fa=this.Ba=null}};"use strict";window.C3_IsSupported&&(window.c3_runtimeInterface=new self.i({zc:!1,Ac:"workermain.js",G:["scripts/c3runtime.js"],fa:[],Ia:"",wc:"scripts/",Ja:[],fb:"html5"}));"use strict";
{function f(d){d.stopPropagation()}self.i.m(class extends self.ia{constructor(d){super(d,"button")}U(d,c){const h=document.createElement("input");var m=h;c.isCheckbox?(h.type="checkbox",m=document.createElement("label"),m.appendChild(h),m.appendChild(document.createTextNode("")),m.style.fontFamily="sans-serif",m.style.userSelect="none",m.style.webkitUserSelect="none",m.style.display="inline-block",m.style.color="black"):h.type="button";m.style.position="absolute";m.addEventListener("touchstart",f);
m.addEventListener("touchmove",f);m.addEventListener("touchend",f);m.addEventListener("mousedown",f);m.addEventListener("mouseup",f);m.addEventListener("keydown",f);m.addEventListener("keyup",f);h.addEventListener("click",()=>Q(this,"click",d,{isChecked:h.checked}));c.id&&(h.id=c.id);this.o(m,c);return m}Oa(d){return"input"===d.tagName.toLowerCase()?d:d.firstChild}na(d){return this.Oa(d)}o(d,c){const h=this.Oa(d);h.checked=c.isChecked;h.disabled=!c.isEnabled;d.title=c.title;d===h?h.value=c.text:d.lastChild.textContent=
c.text}})}"use strict";function U(f){window.C3_RegisterSW&&window.OfflineClientInfo&&window.OfflineClientInfo.SetMessageCallback(d=>u(f,"sw-message",d.data))}
function V(f){f=f.orientation;if(screen.orientation&&screen.orientation.lock)screen.orientation.lock(f).catch(d=>console.warn("[Construct 3] Failed to lock orientation: ",d));else try{let d=!1;screen.lockOrientation?d=screen.lockOrientation(f):screen.webkitLockOrientation?d=screen.webkitLockOrientation(f):screen.mozLockOrientation?d=screen.mozLockOrientation(f):screen.msLockOrientation&&(d=screen.msLockOrientation(f));d||console.warn("[Construct 3] Failed to lock orientation")}catch(d){console.warn("[Construct 3] Failed to lock orientation: ",
d)}}
self.i.m(class extends self.H{constructor(f){super(f,"browser");this.a="";G(this,[["get-initial-state",d=>this.ta(d)],["ready-for-sw-messages",()=>U(this)],["alert",d=>this.ra(d)],["close",()=>{navigator.app&&navigator.app.exitApp?navigator.app.exitApp():navigator.device&&navigator.device.exitApp?navigator.device.exitApp():window.close()}],["set-focus",d=>this.wa(d)],["vibrate",d=>{navigator.vibrate&&navigator.vibrate(d.pattern)}],["lock-orientation",d=>V(d)],["unlock-orientation",()=>{try{screen.orientation&&screen.orientation.unlock?
screen.orientation.unlock():screen.unlockOrientation?screen.unlockOrientation():screen.webkitUnlockOrientation?screen.webkitUnlockOrientation():screen.mozUnlockOrientation?screen.mozUnlockOrientation():screen.msUnlockOrientation&&screen.msUnlockOrientation()}catch(d){}}],["navigate",d=>{var c=d.type;if("back"===c)navigator.app&&navigator.app.backHistory?navigator.app.backHistory():window.history.back();else if("forward"===c)window.history.forward();else if("reload"===c)location.reload();else if("url"===
c){c=d.url;const h=d.target;d=d.exportType;self.cordova&&self.cordova.InAppBrowser?self.cordova.InAppBrowser.open(c,"_system"):"preview"===d||"windows-webview2"===d?window.open(c,"_blank"):this.Ec||(2===h?window.top.location=c:1===h?window.parent.location=c:window.location=c)}else"new-window"===c&&(c=d.url,d=d.tag,self.cordova&&self.cordova.InAppBrowser?self.cordova.InAppBrowser.open(c,"_system"):window.open(c,d))}],["request-fullscreen",d=>{if("windows-webview2"===this.a||"macos-wkwebview"===this.a)self.i.Y(!0),
this.f.za({type:"set-fullscreen",fullscreen:!0});else{const c={navigationUI:"auto"};d=d.navUI;1===d?c.navigationUI="hide":2===d&&(c.navigationUI="show");d=document.documentElement;d.requestFullscreen?d.requestFullscreen(c):d.mozRequestFullScreen?d.mozRequestFullScreen(c):d.msRequestFullscreen?d.msRequestFullscreen(c):d.webkitRequestFullScreen&&("undefined"!==typeof Element.ALLOW_KEYBOARD_INPUT?d.webkitRequestFullScreen(Element.ALLOW_KEYBOARD_INPUT):d.webkitRequestFullScreen())}}],["exit-fullscreen",
()=>{"windows-webview2"===this.a||"macos-wkwebview"===this.a?(self.i.Y(!1),this.f.za({type:"set-fullscreen",fullscreen:!1})):document.exitFullscreen?document.exitFullscreen():document.mozCancelFullScreen?document.mozCancelFullScreen():document.msExitFullscreen?document.msExitFullscreen():document.webkitCancelFullScreen&&document.webkitCancelFullScreen()}],["set-hash",d=>{location.hash=d.hash}]]);window.addEventListener("online",()=>{u(this,"online-state",{isOnline:!0})});window.addEventListener("offline",
()=>{u(this,"online-state",{isOnline:!1})});window.addEventListener("hashchange",()=>{u(this,"hashchange",{location:location.toString()})});document.addEventListener("backbutton",()=>{u(this,"backbutton")})}ta(f){this.a=f.exportType;return{location:location.toString(),isOnline:!!navigator.onLine,referrer:document.referrer,title:document.title,isCookieEnabled:!!navigator.cookieEnabled,screenWidth:screen.width,screenHeight:screen.height,windowOuterWidth:window.outerWidth,windowOuterHeight:window.outerHeight,
isScirraArcade:"undefined"!==typeof window.is_scirra_arcade}}ra(f){alert(f.message)}wa(f){f=f.isFocus;if("nwjs"===this.a){const d="nwjs"===this.a?nw.Window.get():null;f?d.focus():d.blur()}else f?window.focus():window.blur()}});"use strict";
{function f(c){c.stopPropagation()}function d(c){13!==c.which&&27!==c.which&&c.stopPropagation()}self.i.m(class extends self.ia{constructor(c){super(c,"text-input");O(this,"scroll-to-bottom",h=>this.Zb(h))}U(c,h){let m;const y=h.type;"textarea"===y?(m=document.createElement("textarea"),m.style.resize="none"):(m=document.createElement("input"),m.type=y);m.style.position="absolute";m.autocomplete="off";m.addEventListener("touchstart",f);m.addEventListener("touchmove",f);m.addEventListener("touchend",
f);m.addEventListener("mousedown",f);m.addEventListener("mouseup",f);m.addEventListener("keydown",d);m.addEventListener("keyup",d);m.addEventListener("click",q=>{q.stopPropagation();Q(this,"click",c)});m.addEventListener("dblclick",q=>{q.stopPropagation();Q(this,"dblclick",c)});m.addEventListener("input",()=>N(this,"change",c,{text:m.value}));h.id&&(m.id=h.id);this.o(m,h);return m}o(c,h){c.value=h.text;c.placeholder=h.placeholder;c.title=h.title;c.disabled=!h.isEnabled;c.readOnly=h.isReadOnly;c.spellcheck=
h.spellCheck;h=h.maxLength;0>h?c.removeAttribute("maxlength"):c.setAttribute("maxlength",h)}Zb(c){c.scrollTop=c.scrollHeight}})}"use strict";
{function f(d){d.stopPropagation()}self.i.m(class extends self.ia{constructor(d){super(d,"list");O(this,"set-selected-index",(c,h)=>this.ac(c,h.selectedIndex));O(this,"add-item",(c,h)=>this.Bb(c,h));O(this,"remove-item",(c,h)=>this.Wb(c,h));O(this,"set-item",(c,h)=>this.$b(c,h));O(this,"clear",c=>this.Eb(c));O(this,"load-state",(c,h)=>this.Pb(c,h))}U(d,c){const h=c.isDropdown,m=c.isMultiSelect,y=c.items,q=document.createElement("select");q.style.position="absolute";q.style.userSelect="none";q.style.webkitUserSelect=
"none";q.multiple=m;h||(q.size=2);for(const v of y)q.add(this.ma(v));q.addEventListener("touchstart",f);q.addEventListener("touchmove",f);q.addEventListener("touchend",f);q.addEventListener("mousedown",f);q.addEventListener("mouseup",f);q.addEventListener("click",v=>{v.stopPropagation();Q(this,"click",d,this.oa(q))});q.addEventListener("dblclick",v=>{v.stopPropagation();Q(this,"dblclick",d,this.oa(q))});q.addEventListener("change",()=>N(this,"change",d,this.oa(q)));c.id&&(q.id=c.id);this.o(q,c);return q}ma(d){const c=
document.createElement("option");c.text=d;return c}oa(d){const c=d.selectedIndex,h=[];for(let m=0,y=d.length;m<y;++m)d.options[m].selected&&h.push(m);return{selectedIndex:c,selectedIndices:h}}o(d,c){d.title=c.title;d.disabled=!c.isEnabled;d.multiple=!!c.isMultiSelect}ac(d,c){d.selectedIndex=c}Bb(d,c){const h=c.index;c=this.ma(c.text);0>h?d.add(c):d.add(c,h)}Wb(d,c){d.remove(c.index)}$b(d,c){d.options[c.index].text=c.text}Eb(d){d.innerHTML=""}Pb(d,c){d.innerHTML="";for(const h of c.items)d.add(this.ma(h));
d.selectedIndex=c.selectedIndex;for(const h of c.selectedIndices)if(c=d.options[h])c.selected=!0}})}"use strict";async function W(f,d){d=d.type;let c=!0;0===d?c=await X():1===d&&(c=await Y());u(f,"permission-result",{type:d,result:c})}
async function X(){if(!self.DeviceOrientationEvent||!self.DeviceOrientationEvent.requestPermission)return!0;try{return"granted"===await self.DeviceOrientationEvent.requestPermission()}catch(f){return console.warn("[Touch] Failed to request orientation permission: ",f),!1}}
async function Y(){if(!self.DeviceMotionEvent||!self.DeviceMotionEvent.requestPermission)return!0;try{return"granted"===await self.DeviceMotionEvent.requestPermission()}catch(f){return console.warn("[Touch] Failed to request motion permission: ",f),!1}}self.i.m(class extends self.H{constructor(f){super(f,"touch");B(this,"request-permission",d=>W(this,d))}});"use strict";
async function aa(f){if(!f.A)try{f.A=await navigator.wakeLock.request("screen"),f.A.addEventListener("release",()=>{console.log("[Construct 3] Screen wake lock released");f.A=null;u(f,"wake-lock-released")}),console.log("[Construct 3] Screen wake lock acquired"),u(f,"wake-lock-acquired")}catch(d){console.warn("[Construct 3] Failed to acquire screen wake lock: ",d),u(f,"wake-lock-error")}}
function Z(){var f=document.body;const d=f.style;d.setProperty("--temp-sai-top","env(safe-area-inset-top)");d.setProperty("--temp-sai-right","env(safe-area-inset-right)");d.setProperty("--temp-sai-bottom","env(safe-area-inset-bottom)");d.setProperty("--temp-sai-left","env(safe-area-inset-left)");f=getComputedStyle(f);f=[f.getPropertyValue("--temp-sai-top"),f.getPropertyValue("--temp-sai-right"),f.getPropertyValue("--temp-sai-bottom"),f.getPropertyValue("--temp-sai-left")].map(c=>{c=parseInt(c,10);
return isFinite(c)?c:0});d.removeProperty("--temp-sai-top");d.removeProperty("--temp-sai-right");d.removeProperty("--temp-sai-bottom");d.removeProperty("--temp-sai-left");return f}
self.i.m(class extends self.H{constructor(f){super(f,"platform-info");G(this,[["get-initial-state",()=>this.ta()],["request-wake-lock",()=>aa(this)],["release-wake-lock",()=>{this.A&&(this.A.release(),this.A=null)}]]);window.addEventListener("resize",()=>{u(this,"window-resize",{windowOuterWidth:window.outerWidth,windowOuterHeight:window.outerHeight,safeAreaInset:Z()})});this.A=null}ta(){return{screenWidth:screen.width,screenHeight:screen.height,windowOuterWidth:window.outerWidth,windowOuterHeight:window.outerHeight,
safeAreaInset:Z(),supportsWakeLock:!!navigator.wakeLock}}});
