'use strict';function t(h,f,e,k){h.f.ga(h.J,f,e,k,void 0)}function y(h,f,e,k){h.f.l?t(h,f,e,k):h.f.ub()._OnMessageFromDOM({type:"event",component:h.J,handler:f,dispatchOpts:k||null,data:e,responseId:null})}function A(h,f,e){h.f.b(h.J,f,e)}function E(h,f){for(const [e,k]of f)A(h,e,k)}window.ea=class{constructor(h,f){this.f=h;this.J=f}Fa(){}};
window.jb=class{constructor(h,f){this.Va=h;this.hc=f;this.B=-1;this.Y=-Infinity;this.mc=()=>{this.B=-1;this.Y=Date.now();this.K=!0;this.Va();this.K=!1};this.Wa=this.K=!1}};"use strict";function H(h,f){const e=f.elementId,k=h.R(e,f);h.h.set(e,k);f.isVisible||(k.style.display="none");f=h.ja(k);f.addEventListener("focus",()=>{L(h,"elem-focused",e)});f.addEventListener("blur",()=>{L(h,"elem-blurred",e)});h.W&&document.body.appendChild(k)}
function M(h,f,e){A(h,f,k=>{const l=h.h.get(k.elementId);return e(l,k)})}function L(h,f,e,k){k||(k={});k.elementId=e;t(h,f,k)}function N(h,f,e,k){k||(k={});k.elementId=e;y(h,f,k)}
window.da=class extends self.ea{constructor(h,f){super(h,f);this.h=new Map;this.W=!0;E(this,[["create",e=>H(this,e)],["destroy",e=>{{e=e.elementId;const k=this.h.get(e);this.W&&k.parentElement.removeChild(k);this.h.delete(e)}}],["set-visible",e=>{this.W&&(this.h.get(e.elementId).style.display=e.isVisible?"":"none")}],["update-position",e=>{if(this.W){var k=this.h.get(e.elementId);k.style.left=e.left+"px";k.style.top=e.top+"px";k.style.width=e.width+"px";k.style.height=e.height+"px";e=e.fontSize;null!==
e&&(k.style.fontSize=e+"em")}}],["update-state",e=>{{const k=this.h.get(e.elementId);this.m(k,e)}}],["focus",e=>this.sa(e)],["set-css-style",e=>{this.h.get(e.elementId).style[e.prop]=e.val}],["set-attribute",e=>{this.h.get(e.elementId).setAttribute(e.name,e.val)}],["remove-attribute",e=>{this.h.get(e.elementId).removeAttribute(e.name)}]]);M(this,"get-element",e=>e)}R(){throw Error("required override");}m(){throw Error("required override");}ja(h){return h}sa(h){const f=this.ja(this.h.get(h.elementId));
h.focus?f.focus():f.blur()}};"use strict";
{const h=/(iphone|ipod|ipad|macos|macintosh|mac os x)/i.test(navigator.userAgent);let f=0;function e(c){const a=document.createElement("script");a.async=!1;a.type="module";return c.qc?new Promise(d=>{const g="c3_resolve_"+f;++f;self[g]=d;a.textContent=c.tc+`\n\nself["${g}"]();`;document.head.appendChild(a)}):new Promise((d,g)=>{a.onload=d;a.onerror=g;a.src=c;document.head.appendChild(a)})}let k=!1,l=!1;function v(){if(!k){try{new Worker("blob://",{get type(){l=!0}})}catch(c){}k=!0}return l}let n=
new Audio;const x={"audio/webm; codecs=opus":!!n.canPlayType("audio/webm; codecs=opus"),"audio/ogg; codecs=opus":!!n.canPlayType("audio/ogg; codecs=opus"),"audio/webm; codecs=vorbis":!!n.canPlayType("audio/webm; codecs=vorbis"),"audio/ogg; codecs=vorbis":!!n.canPlayType("audio/ogg; codecs=vorbis"),"audio/mp4":!!n.canPlayType("audio/mp4"),"audio/mpeg":!!n.canPlayType("audio/mpeg")};n=null;async function B(c){c=await I(c);return(new TextDecoder("utf-8")).decode(c)}function I(c){return new Promise((a,
d)=>{const g=new FileReader;g.onload=m=>a(m.target.result);g.onerror=m=>d(m);g.readAsArrayBuffer(c)})}const F=[];let z=0;window.RealFile=window.File;const C=[],G=new Map,u=new Map;let J=0;const D=[];self.runOnStartup=function(c){if("function"!==typeof c)throw Error("runOnStartup called without a function");D.push(c)};const K=new Set(["cordova","playable-ad","instant-games"]);let b=!1;window.j=class c{constructor(a){this.l=a.vc;this.M=null;this.c="";this.aa=a.sc;this.P={};this.za=this.$a=null;this.X=
[];this.L=this.g=this.Ca=null;this.v=-1;this.lc=()=>this.Qb();this.Za=[];this.a=a.ab;!this.l||"undefined"!==typeof OffscreenCanvas&&navigator.userActivation&&v()||(this.l=!1);K.has(this.a)&&this.l&&(console.warn("[C3 runtime] Worker mode is enabled and supported, but is currently disabled in WebViews. Reverting to DOM mode."),this.l=!1);this.Z=this.i=null;"html5"!==this.a&&"playable-ad"!==this.a||"file"!==location.protocol.substr(0,4)||alert("Exported games won't work until you upload them. (When running on the file: protocol, browsers block many features from working for security reasons.)");
this.b("runtime","cordova-fetch-local-file",d=>this.Cb(d));this.b("runtime","create-job-worker",()=>this.Db());"cordova"===this.a?document.addEventListener("deviceready",()=>this.La(a)):this.La(a)}Ha(){return h&&"cordova"===this.a}fa(){return h&&K.has(this.a)||navigator.standalone}async La(a){"macos-wkwebview"===this.a&&this.va({type:"ready"});if("playable-ad"===this.a){this.i=self.c3_base64files;this.Z={};await this.pb();for(let g=0,m=a.C.length;g<m;++g){var d=a.C[g].toLowerCase();this.Z.hasOwnProperty(d)?
a.C[g]={qc:!0,tc:this.Z[d]}:this.i.hasOwnProperty(d)&&(a.C[g]=URL.createObjectURL(this.i[d]))}}a.nc?this.c=a.nc:(d=location.origin,this.c=("null"===d?"file:///":d)+location.pathname,d=this.c.lastIndexOf("/"),-1!==d&&(this.c=this.c.substr(0,d+1)));a.xc&&(this.P=a.xc);d=new MessageChannel;this.M=d.port1;this.M.onmessage=g=>this._OnMessageFromRuntime(g.data);window.c3_addPortMessageHandler&&window.c3_addPortMessageHandler(g=>this.Nb(g));this.L=new self.hb(this);await O(this.L);"object"===typeof window.StatusBar&&
window.StatusBar.hide();"object"===typeof window.AndroidFullScreen&&window.AndroidFullScreen.immersiveMode();this.l?await this.wb(a,d.port2):await this.vb(a,d.port2)}la(a){a=this.P.hasOwnProperty(a)?this.P[a]:a.endsWith("/workermain.js")&&this.P.hasOwnProperty("workermain.js")?this.P["workermain.js"]:"playable-ad"===this.a&&this.i.hasOwnProperty(a.toLowerCase())?this.i[a.toLowerCase()]:a;a instanceof Blob&&(a=URL.createObjectURL(a));return a}async ca(a,d,g){if(a.startsWith("blob:"))return new Worker(a,
g);if(this.Ha()&&"file:"===location.protocol)return a=await this.ba(this.aa+a),new Worker(URL.createObjectURL(new Blob([a],{type:"application/javascript"})),g);a=new URL(a,d);if(location.origin!==a.origin){a=await fetch(a);if(!a.ok)throw Error("failed to fetch worker script");a=await a.blob();return new Worker(URL.createObjectURL(a),g)}return new Worker(a,g)}s(){return Math.max(window.innerWidth,1)}o(){return Math.max(window.innerHeight,1)}Ja(a){var d=this.L;return{baseUrl:this.c,windowInnerWidth:this.s(),
windowInnerHeight:this.o(),devicePixelRatio:window.devicePixelRatio,isFullscreen:c.F(),projectData:a.Dc,previewImageBlobs:window.cr_previewImageBlobs||this.i,previewProjectFileBlobs:window.cr_previewProjectFileBlobs,previewProjectFileSWUrls:window.cr_previewProjectFiles,swClientId:window.Bc||"",exportType:a.ab,isDebug:-1<self.location.search.indexOf("debug"),ife:!!self.Cc,jobScheduler:{inputPort:d.xa,outputPort:d.Ba,maxNumWorkers:d.jc},supportedAudioFormats:x,opusWasmScriptUrl:window.cr_opusWasmScriptUrl||
this.aa+"opus.wasm.js",opusWasmBinaryUrl:window.cr_opusWasmBinaryUrl||this.aa+"opus.wasm.wasm",isiOSCordova:this.Ha(),isiOSWebView:this.fa(),isFBInstantAvailable:"undefined"!==typeof self.FBInstant}}async wb(a,d){var g=this.la(a.wc);this.$a=await this.ca(g,this.c,{type:"module",name:"Runtime"});this.g=document.createElement("canvas");this.g.style.display="none";g=this.g.transferControlToOffscreen();document.body.appendChild(this.g);window.c3canvas=this.g;this.$a.postMessage(Object.assign(this.Ja(a),
{type:"init-runtime",isInWorker:!0,messagePort:d,canvas:g,workerDependencyScripts:a.Ea||[],engineScripts:a.C,projectScripts:a.cb,mainProjectScript:a.bb,projectScriptsStatus:self.C3_ProjectScriptsStatus}),[d,g,...P(this.L)]);this.X=C.map(m=>new m(this));this.Ia();self.c3_callFunction=(m,q)=>this.Ca.xb(m,q);"preview"===this.a&&(self.goToLastErrorScript=()=>this.ga("runtime","go-to-last-error-script"))}async vb(a,d){this.g=document.createElement("canvas");this.g.style.display="none";document.body.appendChild(this.g);
window.c3canvas=this.g;this.X=C.map(p=>new p(this));this.Ia();var g=a.C.map(p=>"string"===typeof p?(new URL(p,this.c)).toString():p);Array.isArray(a.Ea)&&g.unshift(...a.Ea);g=await Promise.all(g.map(p=>this.na(p)));await Promise.all(g.map(p=>e(p)));g=self.C3_ProjectScriptsStatus;const m=a.bb,q=a.cb;for(let [p,r]of q)if(r||(r=p),p===m)try{r=await this.na(r),await e(r),"preview"!==this.a||g[p]||this.Ra(p,"main script did not run to completion")}catch(w){this.Ra(p,w)}else if("scriptsInEvents.js"===p||
p.endsWith("/scriptsInEvents.js"))r=await this.na(r),await e(r);"preview"===this.a&&"object"!==typeof self.yc.zc?(this.U(),console.error("[C3 runtime] Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax."),alert("Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax.")):(a=Object.assign(this.Ja(a),{isInWorker:!1,messagePort:d,canvas:this.g,runOnStartupFunctions:D}),this.Na(),this.za=self.C3_CreateRuntime(a),await self.C3_InitRuntime(this.za,
a))}Ra(a,d){this.U();console.error(`[Preview] Failed to load project main script (${a}): `,d);alert(`Failed to load project main script (${a}). Check all your JavaScript code has valid syntax. Press F12 and check the console for error details.`)}Na(){this.U()}U(){const a=window.oc;a&&(a.parentElement.removeChild(a),window.oc=null)}async Db(){const a=await Q(this.L);return{outputPort:a,transferables:[a]}}ub(){if(this.l)throw Error("not available in worker mode");return this.za}ga(a,d,g,m,q){this.M.postMessage({type:"event",
component:a,handler:d,dispatchOpts:m||null,data:g,responseId:null},q)}ib(a,d){const g=J++,m=new Promise((q,p)=>{u.set(g,{resolve:q,reject:p})});this.M.postMessage({type:"event",component:a,handler:"js-invoke-function",dispatchOpts:null,data:d,responseId:g},void 0);return m}["_OnMessageFromRuntime"](a){const d=a.type;if("event"===d)return this.Ib(a);if("result"===d)this.Ub(a);else if("runtime-ready"===d)this.Vb();else if("alert-error"===d)this.U(),alert(a.message);else if("creating-runtime"===d)this.Na();
else throw Error(`unknown message '${d}'`);}Ib(a){const d=a.component,g=a.handler,m=a.data,q=a.responseId;if(a=G.get(d))if(a=a.get(g)){var p=null;try{p=a(m)}catch(r){console.error(`Exception in '${d}' handler '${g}':`,r);null!==q&&this.T(q,!1,""+r);return}if(null===q)return p;p&&p.then?p.then(r=>this.T(q,!0,r)).catch(r=>{console.error(`Rejection from '${d}' handler '${g}':`,r);this.T(q,!1,""+r)}):this.T(q,!0,p)}else console.warn(`[DOM] No handler '${g}' for component '${d}'`);else console.warn(`[DOM] No event handlers for component '${d}'`)}T(a,
d,g){let m;g&&g.transferables&&(m=g.transferables);this.M.postMessage({type:"result",responseId:a,isOk:d,result:g},m)}Ub(a){const d=a.responseId,g=a.isOk;a=a.result;const m=u.get(d);g?m.resolve(a):m.reject(a);u.delete(d)}b(a,d,g){let m=G.get(a);m||(m=new Map,G.set(a,m));if(m.has(d))throw Error(`[DOM] Component '${a}' already has handler '${d}'`);m.set(d,g)}static D(a){if(C.includes(a))throw Error("DOM handler already added");C.push(a)}Ia(){for(const a of this.X)if("runtime"===a.J){this.Ca=a;return}throw Error("cannot find runtime DOM handler");
}Nb(a){this.ga("debugger","message",a)}Vb(){for(const a of this.X)a.Fa()}static F(){return!!(document.fullscreenElement||document.webkitFullscreenElement||document.mozFullScreenElement||b)}static V(a){b=!!a}Sa(){-1===this.v&&this.Za.length&&(this.v=requestAnimationFrame(this.lc))}nb(){-1!==this.v&&(cancelAnimationFrame(this.v),this.v=-1)}Qb(){this.v=-1;for(const a of this.Za)a();this.Sa()}ua(){this.Ca.ua()}fb(a){return/^(?:[a-z\-]+:)?\/\//.test(a)||"data:"===a.substr(0,5)||"blob:"===a.substr(0,5)}gb(a){return!this.fb(a)}async na(a){return"cordova"===
this.a&&(a.startsWith("file:")||"file:"===location.protocol&&this.gb(a))?(a.startsWith(this.c)&&(a=a.substr(this.c.length)),a=await this.ba(a),URL.createObjectURL(new Blob([a],{type:"application/javascript"}))):a}async Cb(a){const d=a.filename;switch(a.as){case "text":return await this.eb(d);case "buffer":return await this.ba(d);default:throw Error("unsupported type");}}Ga(a){const d=window.cordova.file.applicationDirectory+"www/"+a.toLowerCase();return new Promise((g,m)=>{window.resolveLocalFileSystemURL(d,
q=>{q.file(g,m)},m)})}async eb(a){a=await this.Ga(a);return await B(a)}ha(){if(F.length&&!(8<=z)){z++;var a=F.shift();this.qb(a.filename,a.uc,a.pc)}}ba(a){return new Promise((d,g)=>{F.push({filename:a,uc:m=>{z--;this.ha();d(m)},pc:m=>{z--;this.ha();g(m)}});this.ha()})}async qb(a,d,g){try{const m=await this.Ga(a),q=await I(m);d(q)}catch(m){g(m)}}va(a){if("windows-webview2"===this.a)window.chrome.webview.postMessage(JSON.stringify(a));else if("macos-wkwebview"===this.a)window.webkit.messageHandlers.C3Wrapper.postMessage(JSON.stringify(a));
else throw Error("cannot send wrapper message");}async pb(){const a=[];for(const [d,g]of Object.entries(this.i))a.push(this.ob(d,g));await Promise.all(a)}async ob(a,d){if("object"===typeof d)this.i[a]=new Blob([d.str],{type:d.type}),this.Z[a]=d.str;else{let g=await this.tb(d);g||(g=this.rb(d));this.i[a]=g}}async tb(a){try{return await (await fetch(a)).blob()}catch(d){return console.warn("Failed to fetch a data: URI. Falling back to a slower workaround. This is probably because the Content Security Policy unnecessarily blocked it. Allow data: URIs in your CSP to avoid this.",
d),null}}rb(a){a=this.cc(a);return this.mb(a.data,a.rc)}cc(a){var d=a.indexOf(",");if(0>d)throw new URIError("expected comma in data: uri");var g=a.substring(d+1);d=a.substring(5,d).split(";");a=d[0]||"";const m=d[2];g="base64"===d[1]||"base64"===m?atob(g):decodeURIComponent(g);return{rc:a,data:g}}mb(a,d){var g=a.length;let m=g>>2,q=new Uint8Array(g),p=new Uint32Array(q.buffer,0,m),r,w;for(w=r=0;r<m;++r)p[r]=a.charCodeAt(w++)|a.charCodeAt(w++)<<8|a.charCodeAt(w++)<<16|a.charCodeAt(w++)<<24;for(g&=
3;g--;)q[w]=a.charCodeAt(w),++w;return new Blob([q],{type:d})}}}"use strict";
{const h=self.j;function f(b){return b.sourceCapabilities&&b.sourceCapabilities.firesTouchEvents||b.originalEvent&&b.originalEvent.sourceCapabilities&&b.originalEvent.sourceCapabilities.firesTouchEvents}const e=new Map([["OSLeft","MetaLeft"],["OSRight","MetaRight"]]),k={dispatchRuntimeEvent:!0,dispatchUserScriptEvent:!0},l={dispatchUserScriptEvent:!0},v={dispatchRuntimeEvent:!0};function n(b){return new Promise((c,a)=>{const d=document.createElement("link");d.onload=()=>c(d);d.onerror=g=>a(g);d.rel=
"stylesheet";d.href=b;document.head.appendChild(d)})}function x(b){return new Promise((c,a)=>{const d=new Image;d.onload=()=>c(d);d.onerror=g=>a(g);d.src=b})}async function B(b){b=URL.createObjectURL(b);try{return await x(b)}finally{URL.revokeObjectURL(b)}}function I(b){return new Promise((c,a)=>{let d=new FileReader;d.onload=g=>c(g.target.result);d.onerror=g=>a(g);d.readAsText(b)})}async function F(b,c,a){if(!/firefox/i.test(navigator.userAgent))return await B(b);var d=await I(b);d=(new DOMParser).parseFromString(d,
"image/svg+xml");const g=d.documentElement;if(g.hasAttribute("width")&&g.hasAttribute("height")){const m=g.getAttribute("width"),q=g.getAttribute("height");if(!m.includes("%")&&!q.includes("%"))return await B(b)}g.setAttribute("width",c+"px");g.setAttribute("height",a+"px");d=(new XMLSerializer).serializeToString(d);b=new Blob([d],{type:"image/svg+xml"});return await B(b)}function z(b){do{if(b.parentNode&&b.hasAttribute("contenteditable"))return!0;b=b.parentNode}while(b);return!1}const C=new Set(["input",
"textarea","datalist","select"]),G=new Set(["canvas","body","html"]);function u(b){G.has(b.target.tagName.toLowerCase())&&b.preventDefault()}function J(b){(b.metaKey||b.ctrlKey)&&b.preventDefault()}self.C3_GetSvgImageSize=async function(b){b=await B(b);if(0<b.width&&0<b.height)return[b.width,b.height];{b.style.position="absolute";b.style.left="0px";b.style.top="0px";b.style.visibility="hidden";document.body.appendChild(b);const c=b.getBoundingClientRect();document.body.removeChild(b);return[c.width,
c.height]}};self.C3_RasterSvgImageBlob=async function(b,c,a,d,g){b=await F(b,c,a);const m=document.createElement("canvas");m.width=d;m.height=g;m.getContext("2d").drawImage(b,0,0,c,a);return m};let D=!1;document.addEventListener("pause",()=>D=!0);document.addEventListener("resume",()=>D=!1);function K(){try{return window.parent&&window.parent.document.hasFocus()}catch(b){return!1}}h.D(class extends self.ea{constructor(b){super(b,"runtime");this.Xa=!0;this.A=-1;this.Da="any";this.Ta=this.Ua=!1;this.ya=
this.O=this.u=null;b.b("canvas","update-size",d=>this.$b(d));b.b("runtime","invoke-download",d=>this.Lb(d));b.b("runtime","raster-svg-image",d=>this.Rb(d));b.b("runtime","get-svg-image-size",d=>this.Jb(d));b.b("runtime","set-target-orientation",d=>this.Zb(d));b.b("runtime","register-sw",()=>this.Sb());b.b("runtime","post-to-debugger",d=>this.Pa(d));b.b("runtime","go-to-script",d=>this.Pa(d));b.b("runtime","before-start-ticking",()=>this.Ab());b.b("runtime","debug-highlight",d=>this.Eb(d));b.b("runtime",
"enable-device-orientation",()=>this.lb());b.b("runtime","enable-device-motion",()=>this.kb());b.b("runtime","add-stylesheet",d=>this.zb(d));b.b("runtime","alert",d=>this.oa(d));b.b("runtime","hide-cordova-splash",()=>this.Kb());const c=new Set(["input","textarea","datalist"]);window.addEventListener("contextmenu",d=>{const g=d.target;c.has(g.tagName.toLowerCase())||z(g)||d.preventDefault()});const a=b.g;window.addEventListener("selectstart",u);window.addEventListener("gesturehold",u);a.addEventListener("selectstart",
u);a.addEventListener("gesturehold",u);window.addEventListener("touchstart",u,{passive:!1});"undefined"!==typeof PointerEvent?(window.addEventListener("pointerdown",u,{passive:!1}),a.addEventListener("pointerdown",u)):a.addEventListener("touchstart",u);this.N=0;window.addEventListener("mousedown",d=>{1===d.button&&d.preventDefault()});window.addEventListener("mousewheel",J,{passive:!1});window.addEventListener("wheel",J,{passive:!1});window.addEventListener("resize",()=>this.ac());window.addEventListener("fullscreenchange",
()=>this.G());window.addEventListener("webkitfullscreenchange",()=>this.G());window.addEventListener("mozfullscreenchange",()=>this.G());window.addEventListener("fullscreenerror",d=>this.pa(d));window.addEventListener("webkitfullscreenerror",d=>this.pa(d));window.addEventListener("mozfullscreenerror",d=>this.pa(d));b.fa()&&window.addEventListener("focusout",()=>{{const m=document.activeElement;if(m){var d=m.tagName.toLowerCase();var g=new Set("email number password search tel text url".split(" "));
d="textarea"===d?!0:"input"===d?g.has(m.type.toLowerCase()||"text"):z(m)}else d=!1}d||(document.scrollingElement.scrollTop=0)});self.C3WrapperOnMessage=d=>this.bc(d);this.Aa=new Set;this.kc=new WeakSet;this.ic=!1}Ab(){"cordova"===this.f.a?(document.addEventListener("pause",()=>this.ta(!0)),document.addEventListener("resume",()=>this.ta(!1))):document.addEventListener("visibilitychange",()=>this.ta(document.hidden));return{isSuspended:!(!document.hidden&&!D)}}Fa(){window.addEventListener("focus",()=>
this.I("window-focus"));window.addEventListener("blur",()=>{this.I("window-blur",{parentHasFocus:K()});this.N=0});window.addEventListener("focusin",c=>{c=c.target;(C.has(c.tagName.toLowerCase())||z(c))&&this.I("keyboard-blur")});window.addEventListener("keydown",c=>this.Oa("keydown",c));window.addEventListener("keyup",c=>this.Oa("keyup",c));window.addEventListener("dblclick",c=>this.qa("dblclick",c,k));window.addEventListener("wheel",c=>this.Ob(c));"undefined"!==typeof PointerEvent?(window.addEventListener("pointerdown",
c=>{this.ma(c);this.H("pointerdown",c)}),this.f.l&&"undefined"!==typeof window.onpointerrawupdate&&self===self.top?(this.O=new self.jb(()=>this.sb(),5),this.O.Wa=!0,window.addEventListener("pointerrawupdate",c=>this.Pb(c))):window.addEventListener("pointermove",c=>this.H("pointermove",c)),window.addEventListener("pointerup",c=>this.H("pointerup",c)),window.addEventListener("pointercancel",c=>this.H("pointercancel",c))):(window.addEventListener("mousedown",c=>{this.ma(c);this.ra("pointerdown",c)}),
window.addEventListener("mousemove",c=>this.ra("pointermove",c)),window.addEventListener("mouseup",c=>this.ra("pointerup",c)),window.addEventListener("touchstart",c=>{this.ma(c);this.S("pointerdown",c)}),window.addEventListener("touchmove",c=>this.S("pointermove",c)),window.addEventListener("touchend",c=>this.S("pointerup",c)),window.addEventListener("touchcancel",c=>this.S("pointercancel",c)));const b=()=>this.ua();window.addEventListener("pointerup",b,!0);window.addEventListener("touchend",b,!0);
window.addEventListener("click",b,!0);window.addEventListener("keydown",b,!0);window.addEventListener("gamepadconnected",b,!0)}I(b,c){t(this,b,c||null,v)}s(){return this.f.s()}o(){return this.f.o()}ac(){const b=this.s(),c=this.o();this.I("window-resize",{innerWidth:b,innerHeight:c,devicePixelRatio:window.devicePixelRatio,isFullscreen:h.F()});this.f.fa()&&(-1!==this.A&&clearTimeout(this.A),this.Qa(b,c,0))}dc(b,c,a){-1!==this.A&&clearTimeout(this.A);this.A=setTimeout(()=>this.Qa(b,c,a),48)}Qa(b,c,a){const d=
this.s(),g=this.o();this.A=-1;d!=b||g!=c?this.I("window-resize",{innerWidth:d,innerHeight:g,devicePixelRatio:window.devicePixelRatio,isFullscreen:h.F()}):10>a&&this.dc(d,g,a+1)}Zb(b){this.Da=b.targetOrientation}ec(){const b=this.Da;if(screen.orientation&&screen.orientation.lock)screen.orientation.lock(b).catch(c=>console.warn("[Construct 3] Failed to lock orientation: ",c));else try{let c=!1;screen.lockOrientation?c=screen.lockOrientation(b):screen.webkitLockOrientation?c=screen.webkitLockOrientation(b):
screen.mozLockOrientation?c=screen.mozLockOrientation(b):screen.msLockOrientation&&(c=screen.msLockOrientation(b));c||console.warn("[Construct 3] Failed to lock orientation")}catch(c){console.warn("[Construct 3] Failed to lock orientation: ",c)}}G(){const b=h.F();b&&"any"!==this.Da&&this.ec();t(this,"fullscreenchange",{isFullscreen:b,innerWidth:this.s(),innerHeight:this.o()})}pa(b){console.warn("[Construct 3] Fullscreen request failed: ",b);t(this,"fullscreenerror",{isFullscreen:h.F(),innerWidth:this.s(),
innerHeight:this.o()})}ta(b){b?this.f.nb():this.f.Sa();t(this,"visibilitychange",{hidden:b})}Oa(b,c){"Backspace"===c.key&&u(c);const a=e.get(c.code)||c.code;y(this,b,{code:a,key:c.key,which:c.which,repeat:c.repeat,altKey:c.altKey,ctrlKey:c.ctrlKey,metaKey:c.metaKey,shiftKey:c.shiftKey,timeStamp:c.timeStamp},k)}Ob(b){t(this,"wheel",{clientX:b.clientX,clientY:b.clientY,pageX:b.pageX,pageY:b.pageY,deltaX:b.deltaX,deltaY:b.deltaY,deltaZ:b.deltaZ,deltaMode:b.deltaMode,timeStamp:b.timeStamp},k)}qa(b,c,
a){f(c)||y(this,b,{button:c.button,buttons:c.buttons,clientX:c.clientX,clientY:c.clientY,pageX:c.pageX,pageY:c.pageY,timeStamp:c.timeStamp},a)}ra(b,c){if(!f(c)){var a=this.N;"pointerdown"===b&&0!==a?b="pointermove":"pointerup"===b&&0!==c.buttons&&(b="pointermove");y(this,b,{pointerId:1,pointerType:"mouse",button:c.button,buttons:c.buttons,lastButtons:a,clientX:c.clientX,clientY:c.clientY,pageX:c.pageX,pageY:c.pageY,width:0,height:0,pressure:0,tangentialPressure:0,tiltX:0,tiltY:0,twist:0,timeStamp:c.timeStamp},
k);this.N=c.buttons;this.qa(c.type,c,l)}}H(b,c){if(this.O&&"pointermove"!==b){var a=this.O;a.K||(-1!==a.B&&(self.clearTimeout(a.B),a.B=-1),a.Y=Date.now())}a=0;"mouse"===c.pointerType&&(a=this.N);y(this,b,{pointerId:c.pointerId,pointerType:c.pointerType,button:c.button,buttons:c.buttons,lastButtons:a,clientX:c.clientX,clientY:c.clientY,pageX:c.pageX,pageY:c.pageY,width:c.width||0,height:c.height||0,pressure:c.pressure||0,tangentialPressure:c.tangentialPressure||0,tiltX:c.tiltX||0,tiltY:c.tiltY||0,
twist:c.twist||0,timeStamp:c.timeStamp},k);"mouse"===c.pointerType&&(a="mousemove","pointerdown"===b?a="mousedown":"pointerup"===b&&(a="mouseup"),this.qa(a,c,l),this.N=c.buttons)}Pb(b){this.ya=b;b=this.O;if(-1===b.B){var c=Date.now(),a=c-b.Y,d=b.hc;a>=d&&b.Wa?(b.Y=c,b.K=!0,b.Va(),b.K=!1):b.B=self.setTimeout(b.mc,Math.max(d-a,4))}}sb(){this.H("pointermove",this.ya);this.ya=null}S(b,c){for(let a=0,d=c.changedTouches.length;a<d;++a){const g=c.changedTouches[a];y(this,b,{pointerId:g.identifier,pointerType:"touch",
button:0,buttons:0,lastButtons:0,clientX:g.clientX,clientY:g.clientY,pageX:g.pageX,pageY:g.pageY,width:2*(g.radiusX||g.webkitRadiusX||0),height:2*(g.radiusY||g.webkitRadiusY||0),pressure:g.force||g.webkitForce||0,tangentialPressure:0,tiltX:0,tiltY:0,twist:g.rotationAngle||0,timeStamp:c.timeStamp},k)}}ma(b){window!==window.top&&window.focus();this.Ma(b.target)&&document.activeElement&&!this.Ma(document.activeElement)&&document.activeElement.blur()}Ma(b){return!b||b===document||b===window||b===document.body||
"canvas"===b.tagName.toLowerCase()}lb(){this.Ua||(this.Ua=!0,window.addEventListener("deviceorientation",b=>this.Gb(b)),window.addEventListener("deviceorientationabsolute",b=>this.Hb(b)))}kb(){this.Ta||(this.Ta=!0,window.addEventListener("devicemotion",b=>this.Fb(b)))}Gb(b){t(this,"deviceorientation",{absolute:!!b.absolute,alpha:b.alpha||0,beta:b.beta||0,gamma:b.gamma||0,timeStamp:b.timeStamp,webkitCompassHeading:b.webkitCompassHeading,webkitCompassAccuracy:b.webkitCompassAccuracy},k)}Hb(b){t(this,
"deviceorientationabsolute",{absolute:!!b.absolute,alpha:b.alpha||0,beta:b.beta||0,gamma:b.gamma||0,timeStamp:b.timeStamp},k)}Fb(b){let c=null;var a=b.acceleration;a&&(c={x:a.x||0,y:a.y||0,z:a.z||0});a=null;var d=b.accelerationIncludingGravity;d&&(a={x:d.x||0,y:d.y||0,z:d.z||0});d=null;const g=b.rotationRate;g&&(d={alpha:g.alpha||0,beta:g.beta||0,gamma:g.gamma||0});t(this,"devicemotion",{acceleration:c,accelerationIncludingGravity:a,rotationRate:d,interval:b.interval,timeStamp:b.timeStamp},k)}$b(b){const c=
this.f.g;c.style.width=b.styleWidth+"px";c.style.height=b.styleHeight+"px";c.style.marginLeft=b.marginLeft+"px";c.style.marginTop=b.marginTop+"px";this.Xa&&(c.style.display="",this.Xa=!1)}Lb(b){const c=b.url;b=b.filename;const a=document.createElement("a"),d=document.body;a.textContent=b;a.href=c;a.download=b;d.appendChild(a);a.click();d.removeChild(a)}async Rb(b){var c=b.imageBitmapOpts;b=await self.C3_RasterSvgImageBlob(b.blob,b.imageWidth,b.imageHeight,b.surfaceWidth,b.surfaceHeight);c=c?await createImageBitmap(b,
c):await createImageBitmap(b);return{imageBitmap:c,transferables:[c]}}async Jb(b){return await self.C3_GetSvgImageSize(b.blob)}async zb(b){await n(b.url)}ua(){var b=[...this.Aa];this.Aa.clear();if(!this.ic)for(const c of b)(b=c.play())&&b.catch(()=>{this.kc.has(c)||this.Aa.add(c)})}Kb(){navigator.splashscreen&&navigator.splashscreen.hide&&navigator.splashscreen.hide()}Eb(b){if(b.show){this.u||(this.u=document.createElement("div"),this.u.id="inspectOutline",document.body.appendChild(this.u));var c=
this.u;c.style.display="";c.style.left=b.left-1+"px";c.style.top=b.top-1+"px";c.style.width=b.width+2+"px";c.style.height=b.height+2+"px";c.textContent=b.name}else this.u&&(this.u.style.display="none")}Sb(){window.C3_RegisterSW&&window.C3_RegisterSW()}Pa(b){window.c3_postToMessagePort&&(b.from="runtime",window.c3_postToMessagePort(b))}xb(b,c){return this.f.ib(this.J,{name:b,params:c})}oa(b){alert(b.message)}bc(b){"entered-fullscreen"===b?(h.V(!0),this.G()):"exited-fullscreen"===b?(h.V(!1),this.G()):
console.warn("Unknown wrapper message: ",b)}})}"use strict";async function O(h){if(h.fc)throw Error("already initialised");h.fc=!0;var f=h.$.la("dispatchworker.js");h.wa=await h.$.ca(f,h.c,{name:"DispatchWorker"});f=new MessageChannel;h.xa=f.port1;h.wa.postMessage({type:"_init","in-port":f.port2},[f.port2]);h.Ba=await Q(h)}function P(h){return[h.xa,h.Ba]}
async function Q(h){const f=h.Ya.length;var e=h.$.la("jobworker.js");e=await h.$.ca(e,h.c,{name:"JobWorker"+f});const k=new MessageChannel,l=new MessageChannel;h.wa.postMessage({type:"_addJobWorker",port:k.port1},[k.port1]);e.postMessage({type:"init",number:f,"dispatch-port":k.port2,"output-port":l.port2},[k.port2,l.port2]);h.Ya.push(e);return l.port1}
self.hb=class{constructor(h){this.$=h;this.c=h.c;this.c="preview"===h.a?this.c+"c3/workers/":this.c+h.aa;this.jc=Math.min(navigator.hardwareConcurrency||2,16);this.wa=null;this.Ya=[];this.Ba=this.xa=null}};"use strict";window.C3_IsSupported&&(window.c3_runtimeInterface=new self.j({vc:!0,wc:"workermain.js",C:["scripts/c3runtime.js"],cb:[],bb:"",sc:"scripts/",Ea:[],ab:"html5"}));"use strict";
{function h(f){f.stopPropagation()}self.j.D(class extends self.da{constructor(f){super(f,"button")}R(f,e){const k=document.createElement("input");var l=k;e.isCheckbox?(k.type="checkbox",l=document.createElement("label"),l.appendChild(k),l.appendChild(document.createTextNode("")),l.style.fontFamily="sans-serif",l.style.userSelect="none",l.style.webkitUserSelect="none",l.style.display="inline-block",l.style.color="black"):k.type="button";l.style.position="absolute";l.addEventListener("touchstart",h);
l.addEventListener("touchmove",h);l.addEventListener("touchend",h);l.addEventListener("mousedown",h);l.addEventListener("mouseup",h);l.addEventListener("keydown",h);l.addEventListener("keyup",h);k.addEventListener("click",()=>N(this,"click",f,{isChecked:k.checked}));e.id&&(k.id=e.id);this.m(l,e);return l}Ka(f){return"input"===f.tagName.toLowerCase()?f:f.firstChild}ja(f){return this.Ka(f)}m(f,e){const k=this.Ka(f);k.checked=e.isChecked;k.disabled=!e.isEnabled;f.title=e.title;f===k?k.value=e.text:f.lastChild.textContent=
e.text}})}"use strict";function R(h){window.C3_RegisterSW&&window.OfflineClientInfo&&window.OfflineClientInfo.SetMessageCallback(f=>t(h,"sw-message",f.data))}
function S(h){h=h.orientation;if(screen.orientation&&screen.orientation.lock)screen.orientation.lock(h).catch(f=>console.warn("[Construct 3] Failed to lock orientation: ",f));else try{let f=!1;screen.lockOrientation?f=screen.lockOrientation(h):screen.webkitLockOrientation?f=screen.webkitLockOrientation(h):screen.mozLockOrientation?f=screen.mozLockOrientation(h):screen.msLockOrientation&&(f=screen.msLockOrientation(h));f||console.warn("[Construct 3] Failed to lock orientation")}catch(f){console.warn("[Construct 3] Failed to lock orientation: ",
f)}}
self.j.D(class extends self.ea{constructor(h){super(h,"browser");this.a="";E(this,[["get-initial-state",f=>{this.a=f.exportType;return{location:location.toString(),isOnline:!!navigator.onLine,referrer:document.referrer,title:document.title,isCookieEnabled:!!navigator.cookieEnabled,screenWidth:screen.width,screenHeight:screen.height,windowOuterWidth:window.outerWidth,windowOuterHeight:window.outerHeight,isScirraArcade:"undefined"!==typeof window.is_scirra_arcade}}],["ready-for-sw-messages",()=>R(this)],
["alert",f=>this.oa(f)],["close",()=>{navigator.app&&navigator.app.exitApp?navigator.app.exitApp():navigator.device&&navigator.device.exitApp?navigator.device.exitApp():window.close()}],["set-focus",f=>this.sa(f)],["vibrate",f=>{navigator.vibrate&&navigator.vibrate(f.pattern)}],["lock-orientation",f=>S(f)],["unlock-orientation",()=>{try{screen.orientation&&screen.orientation.unlock?screen.orientation.unlock():screen.unlockOrientation?screen.unlockOrientation():screen.webkitUnlockOrientation?screen.webkitUnlockOrientation():
screen.mozUnlockOrientation?screen.mozUnlockOrientation():screen.msUnlockOrientation&&screen.msUnlockOrientation()}catch(f){}}],["navigate",f=>{var e=f.type;if("back"===e)navigator.app&&navigator.app.backHistory?navigator.app.backHistory():window.history.back();else if("forward"===e)window.history.forward();else if("reload"===e)location.reload();else if("url"===e){e=f.url;var k=f.target;f=f.exportType;"windows-uwp"===f&&"undefined"!==typeof Windows?Windows.System.Launcher.launchUriAsync(new Windows.Foundation.Uri(e)):
self.cordova&&self.cordova.InAppBrowser?self.cordova.InAppBrowser.open(e,"_system"):"preview"===f||"windows-webview2"===f?window.open(e,"_blank"):this.Ac||(2===k?window.top.location=e:1===k?window.parent.location=e:window.location=e)}else"new-window"===e&&(e=f.url,k=f.tag,"windows-uwp"===f.exportType&&"undefined"!==typeof Windows?Windows.System.Launcher.launchUriAsync(new Windows.Foundation.Uri(e)):self.cordova&&self.cordova.InAppBrowser?self.cordova.InAppBrowser.open(e,"_system"):window.open(e,k))}],
["request-fullscreen",f=>{if("windows-webview2"===this.a||"macos-wkwebview"===this.a)self.j.V(!0),this.f.va({type:"set-fullscreen",fullscreen:!0});else{const e={navigationUI:"auto"};f=f.navUI;1===f?e.navigationUI="hide":2===f&&(e.navigationUI="show");f=document.documentElement;f.requestFullscreen?f.requestFullscreen(e):f.mozRequestFullScreen?f.mozRequestFullScreen(e):f.msRequestFullscreen?f.msRequestFullscreen(e):f.webkitRequestFullScreen&&("undefined"!==typeof Element.ALLOW_KEYBOARD_INPUT?f.webkitRequestFullScreen(Element.ALLOW_KEYBOARD_INPUT):
f.webkitRequestFullScreen())}}],["exit-fullscreen",()=>{"windows-webview2"===this.a||"macos-wkwebview"===this.a?(self.j.V(!1),this.f.va({type:"set-fullscreen",fullscreen:!1})):document.exitFullscreen?document.exitFullscreen():document.mozCancelFullScreen?document.mozCancelFullScreen():document.msExitFullscreen?document.msExitFullscreen():document.webkitCancelFullScreen&&document.webkitCancelFullScreen()}],["set-hash",f=>{location.hash=f.hash}]]);window.addEventListener("online",()=>{t(this,"online-state",
{isOnline:!0})});window.addEventListener("offline",()=>{t(this,"online-state",{isOnline:!1})});window.addEventListener("hashchange",()=>{t(this,"hashchange",{location:location.toString()})});document.addEventListener("backbutton",()=>{t(this,"backbutton")});"undefined"!==typeof Windows&&Windows.UI.Core.SystemNavigationManager.getForCurrentView().addEventListener("backrequested",f=>{f.handled=!0;t(this,"backbutton")})}oa(h){alert(h.message)}sa(h){h=h.isFocus;if("nwjs"===this.a){const f="nwjs"===this.a?
nw.Window.get():null;h?f.focus():f.blur()}else h?window.focus():window.blur()}});"use strict";
{function h(e){e.stopPropagation()}function f(e){13!==e.which&&27!==e.which&&e.stopPropagation()}self.j.D(class extends self.da{constructor(e){super(e,"text-input");M(this,"scroll-to-bottom",k=>this.Wb(k))}R(e,k){let l;const v=k.type;"textarea"===v?(l=document.createElement("textarea"),l.style.resize="none"):(l=document.createElement("input"),l.type=v);l.style.position="absolute";l.autocomplete="off";l.addEventListener("touchstart",h);l.addEventListener("touchmove",h);l.addEventListener("touchend",
h);l.addEventListener("mousedown",h);l.addEventListener("mouseup",h);l.addEventListener("keydown",f);l.addEventListener("keyup",f);l.addEventListener("click",n=>{n.stopPropagation();N(this,"click",e)});l.addEventListener("dblclick",n=>{n.stopPropagation();N(this,"dblclick",e)});l.addEventListener("input",()=>L(this,"change",e,{text:l.value}));k.id&&(l.id=k.id);this.m(l,k);return l}m(e,k){e.value=k.text;e.placeholder=k.placeholder;e.title=k.title;e.disabled=!k.isEnabled;e.readOnly=k.isReadOnly;e.spellcheck=
k.spellCheck;k=k.maxLength;0>k?e.removeAttribute("maxlength"):e.setAttribute("maxlength",k)}Wb(e){e.scrollTop=e.scrollHeight}})}"use strict";
{function h(f){f.stopPropagation()}self.j.D(class extends self.da{constructor(f){super(f,"list");M(this,"set-selected-index",(e,k)=>this.Yb(e,k.selectedIndex));M(this,"add-item",(e,k)=>this.yb(e,k));M(this,"remove-item",(e,k)=>this.Tb(e,k));M(this,"set-item",(e,k)=>this.Xb(e,k));M(this,"clear",e=>this.Bb(e));M(this,"load-state",(e,k)=>this.Mb(e,k))}R(f,e){const k=e.isDropdown,l=e.isMultiSelect,v=e.items,n=document.createElement("select");n.style.position="absolute";n.style.userSelect="none";n.style.webkitUserSelect=
"none";n.multiple=l;k||(n.size=2);for(const x of v)n.add(this.ia(x));n.addEventListener("touchstart",h);n.addEventListener("touchmove",h);n.addEventListener("touchend",h);n.addEventListener("mousedown",h);n.addEventListener("mouseup",h);n.addEventListener("click",x=>{x.stopPropagation();N(this,"click",f,this.ka(n))});n.addEventListener("dblclick",x=>{x.stopPropagation();N(this,"dblclick",f,this.ka(n))});n.addEventListener("change",()=>L(this,"change",f,this.ka(n)));e.id&&(n.id=e.id);this.m(n,e);return n}ia(f){const e=
document.createElement("option");e.text=f;return e}ka(f){const e=f.selectedIndex,k=[];for(let l=0,v=f.length;l<v;++l)f.options[l].selected&&k.push(l);return{selectedIndex:e,selectedIndices:k}}m(f,e){f.title=e.title;f.disabled=!e.isEnabled;f.multiple=!!e.isMultiSelect}Yb(f,e){f.selectedIndex=e}yb(f,e){const k=e.index;e=this.ia(e.text);0>k?f.add(e):f.add(e,k)}Tb(f,e){f.remove(e.index)}Xb(f,e){f.options[e.index].text=e.text}Bb(f){f.innerHTML=""}Mb(f,e){f.innerHTML="";for(const k of e.items)f.add(this.ia(k));
f.selectedIndex=e.selectedIndex;for(const k of e.selectedIndices)if(e=f.options[k])e.selected=!0}})};
